contiki-ng/contiki-ng

Makefile.identify-target
Makefile.include
examples/sensniff/Makefile

For some cross-platform examples, we need to tweak things based on the target platform. For this reason, target identification needs to happen early in the build process, before inclusion of the top-level `Makefile.include`.
Up to now, we had simply been replicating the target-identification code in example Makefiles, leading to code-replication, inconsistency, and on occasion bugs (e.g. ignoring Makefile.target or environment variables).
This pull proposes moving target identification to a separate top-level `Makefile.identify-target`. Example Makefiles can include this early on "as a library" (e.g. the way the sensniff Makefile changes in this pull). If the example Makefile does not need target identification, the top-level `Makefile.include` will always include …

 Move target identification code to separate Makefile

---

examples/sensniff/sensniff.c

Minor fix to the sensniff firmware. Merely changes an error debug statement to always print. Removes the #if DEBUG clutter

Change debug statement

---

arch/cpu/msp430/f1xxx/clock.c
arch/cpu/msp430/f5xxx/clock.c
arch/dev/cc1200/cc1200.c
arch/dev/cc2420/cc2420.c
arch/platform/jn516x/dev/micromac-radio.c
arch/platform/jn516x/platform.c
arch/platform/sky/platform.c
os/contiki-main.c
os/contiki.h
os/sys/energest.c
os/sys/energest.h

* Adds new energest type `ENERGEST_TYPE_DEEP_LPM` as discussed in #108.
* Adds function to get the total energest time: `ENERGEST_GET_TOTAL_TIME()`. This is essentially the sum of the times in different CPU modes (CPU + LPM + DEEP_LPM).
* Adds configurable type `ENERGEST_TIME_T` to support for clocks with wrapping time as time source for energest.
* Removes include of `energest.h` from `contiki.h` to avoid circular dependencies.
* Fixes some typos.

New energest type for deep sleep plus configurable type for Energest time source

---

arch/platform/cc2538dk/contiki-conf.h
arch/platform/cooja/contiki-conf.h
arch/platform/openmote-cc2538/contiki-conf.h
arch/platform/srf06-cc26xx/contiki-conf.h
arch/platform/zoul/contiki-conf.h

slip-radio and rpl-border-router have this example-specific putchar which is used to do mux/demux when SLIP is used over the same interface as debug char i/o. As far as I can tell, among our current platforms only sky uses it, so I am moving it to the platform-specific part of the respective examples in #132 and #133. Once those two have been merged, those macros will be obsolete, and this pull removes them.
In terms of the diff, this pull here is orthogonal to the two mentioned above, however there is no point merging this one before merging the above two.

Remove obsolete SLIP_foo_CONF_NO_PUTCHAR

---

examples/rpl-border-router/Makefile
examples/rpl-border-router/border-router.c
examples/rpl-border-router/embedded/Makefile
examples/rpl-border-router/embedded/border-router-embedded.c
examples/rpl-border-router/native/Makefile
examples/rpl-border-router/native/border-router-native.c

This has two benefits:
* enables compiling the BR in Cooja -- Cooja requires a `.c` project file sitting in the same dir as the makefile and the firmware
* makes for cleaner compilation, now with all artifacts in the common dir, no more need to `cp`

Border-router: move border-router.c to top level for cleaner compilation

---

examples/rpl-border-router/README.md
examples/rpl-border-router/embedded/README.md
examples/rpl-border-router/native/README.md
examples/rpl-udp/README.md
examples/slip-radio/README.md

This updates and adds missing README.md, with main focus on RPL BR, slip-radio and rpl-udp, with the main aim to help the user know what is meant for use with what.

More README.md work for the examples

---

examples/rpl-udp/Makefile
examples/rpl-udp/README.md
examples/rpl-udp/cc2538-node.resc
examples/rpl-udp/rpl-udp.resc

This PR adds Renode scripts and integration via Makefile, as discussed with Joakim.
This is specific to rpl-udp example on CC2538DK, but may be used for other binaries and boards as well, with little adjustments.
To run Renode in this setup run `make renode TARGET=cc2538dk`.

Renode example in rpl-udp demo

---

examples/6tisch/sixtop/node-sixtop.c

I found a bug in `example/6tisch/sixtop/node-sixtop.c`, which will be resolved by this commit.

sixtop: bugfix adding a missing 'static' modifier

---

.gitignore

We moved doxygen documentation, so build artifacts are no longer being ignored. This commit sets .gitignore all documentation output in its new location.
This should IMHO be included in this release.

Gitignore doxygen output files in their new location

---

os/net/rpl-lite/rpl-conf.h
os/net/rpl-lite/rpl-const.h
os/net/rpl-lite/rpl-dag.h
os/net/rpl-lite/rpl-neighbor.h
os/net/rpl-lite/rpl-timers.h
os/net/rpl-lite/rpl-types.h

Some files were unintentionally excluded from the documentation -- this PR fixes this. Also adds some brief description of rpl-lite types.

Doxygen improvements for rpl-lite

---

os/net/mac/tsch/tsch.c

This PR resolves a particularly annoying bug that happens under some occations, for instance a lost sync just before trying to send KA. (This has been seen in cooja on repeated occasions)
In cooja this results in segfault, and on taret it results in data abort exception.
The reason is the fail-to-check-for-NULL-pointer in the code that sends the KA. I don't know if there might be a race condition since this apparently happens when tsch_is_associated is set, but there still is no timesouce. However, since the tsch_queue_get_time_source explicitly returns NULL in some cases, the calling code should check for NULL.

Avoid tsch crash when losing timesource

---

arch/platform/cc2538dk/dev/board.h
arch/platform/openmote-cc2538/board.h
arch/platform/srf06-cc26xx/launchpad/cc1310/board.h
arch/platform/srf06-cc26xx/launchpad/cc1350/board.h
arch/platform/srf06-cc26xx/launchpad/cc2650/board.h
arch/platform/srf06-cc26xx/sensortag/cc1350/board.h
arch/platform/srf06-cc26xx/sensortag/cc2650/board.h
arch/platform/srf06-cc26xx/srf06/cc13xx/board.h
arch/platform/srf06-cc26xx/srf06/cc26xx/board.h
arch/platform/zoul/firefly-reva/board.h
arch/platform/zoul/firefly/board.h
arch/platform/zoul/orion/board.h
arch/platform/zoul/remote-reva/board.h
arch/platform/zoul/remote-revb/board.h

At some point in the distant past those `#undef`s were necessary. Not any more, so this pull removes them.

Remove LED undefs

---

os/dev/leds.c

This pull request fixes a bug in the HAL for the LEDs (leds.c). 
The static variable `leds` did not get updated resulting to misbehaviour, such as `leds_toggle()` not working (led always stays on) and `leds_on()` turning off other leds.
The fix removes the static variable `leds` and, instead, uses `leds_arch_get()` to get the state of the leds.

Bugfix in HAL for LEDs (leds.c)

---

arch/cpu/cc2538/lpm.c
arch/cpu/cc26xx-cc13xx/lpm.c

Pull request #139 introduces the deep sleep enegest state, but does not actually use it. This PR adds code that tracks this new deep sleep state for CC26xx and CC2538.

Use ENERGEST_TYPE_DEEP_LPM energest state for CC2538 and CC26xx

---

os/net/rpl-classic/rpl-ns.c
os/net/rpl-lite/rpl-ns.c

In `rpl_ns_periodic` routing links had their lifetime decremented first, and then expired links were removed. The decrement period is 60s. This cause expiry within [period-60s;period[. With this fix, we first remove expired links and second, decrement the lifetimes. This results in an expiry delay within [period;period+60s[

RPL non-storing: ensure routing links are stored for at least their advertised lifetime

---

arch/platform/cc2538dk/platform.c
arch/platform/openmote-cc2538/platform.c
arch/platform/zoul/platform.c

This reworks netstack initialization on cc2538 platforms. Initialize linkaddr in phase 2 but set RF parameters only in phase 3, i.e., after `netstack_init` is called. Without this fix, Zoul fails to run with cc1200.

Netstack initializion fix

---

arch/platform/jn516x/lib/slip.c
examples/slip-radio/project-conf.h
examples/slip-radio/slip-net.c
examples/slip-radio/slip-radio.c
os/dev/slip.c
os/dev/slip.h

This pull recommends the following changes to SLIP-related code:
* We have three places in the tree where the SLIP framing code is duplicated:
* `slip_write()`: Outputs over SLIP an arbitrary number of bytes from a memory location. This is the one we keep.
* `slip_send()`: Outputs the L3 contents of `uip_buf`. Now simply calls .`slip_write(&uip_buf[UIP_LLH_LEN], uip_len);`.
* `slip_send_packet`: Provided by the slip-radio example. This is being removed and all calls now call `slip_write` instead.
* All calls to `slip_send` and `slip_write` were ignoring the return value, so the return type for both functions has been changed to `void`.
* SLIP statistics are now possible to turn on/off through a configuration define (were previously hard-coded to off).
* There was some dead code wrapped …

Various SLIP-related improvements

---

arch/cpu/cc26xx-cc13xx/rf-core/rf-ble.c
arch/cpu/cc26xx-cc13xx/rf-core/rf-ble.h

This pull enhances the arch-specific RF BLE driver for the cc26xx-cc13xx family.
There are four basic changes:
1. BLE MAC Address: The driver loads the actual hard-coded BLE MAC address of the device from the flash. The user can also specify a custom BLE MAC address by defining `BLE_ADDRESS_PTR`.
2. Adv Tx Power: The tx power for the advertisements is not hard-coded to +5 dBm anymore, but  configurable by the user via `rf_ble_set_tx_power()`.
3. BLE Adv Channels: The user can select any arbitrary subset of the three BLE advertisement channels to transmit the BLE advertisement packet.
4. Send Single BLE Advertisement: The user can transmit a single BLE advertisement with dynamic payload using `rf_ble_beacon_single()`.

Improvements in BLE Advertisements for cc26xx-cc13xx

---

arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
arch/cpu/cc26xx-cc13xx/ccxxware-conf.h
arch/platform/srf06-cc26xx/contiki-conf.h

This adds a new toggle to `contiki-conf.h` (`CCXXWARE_CONF_JTAG_INTERFACE_ENABLE`) which controls access to the JTAG debug interface on CC26xx/CC13xx platforms and enables it by default.
This addresses #200

Add JTAG interface configuration in contiki-conf.h for CCxx platforms

---

os/sys/log-conf.h
os/sys/log.h

Adds a configuration option `LOG_CONF_OUTPUT_PREFIX` to specify a custom output function to output the log level and module name in the beginning of each log line. This makes it possible to add a timestamp or use a different log module prefix format than the default.

Extend the logging module to support custom module prefix

---

os/net/ipv6/uip6.c

At the moment, trying to build with UIP_CONF_STATISTICS enabled leads to linking error. Looks like one variable too many was removed when migrating uIPv6 code from Contiki to Contiki-NG.

Readd back 'uip_stat' if UIP_STATISTICS is enabled

---

os/net/rpl-classic/rpl-private.h
os/net/rpl-classic/rpl-timers.c

The default lifetime of the multicast route in the DAO message is currently set to 3 times the default lifetime unit.
However, the DAO scheduling is based solely on the unicast route lifetime, which means that the multicast routes are removed before the renewing DAO is sent.
This PR provides a simple workaround by setting the multicast route lifetime equal to the unicast one.

Multicast routes are not renewed before the lifetime is elapsed

---

os/net/ipv6/multicast/esmrf.c
os/net/ipv6/multicast/roll-tm.c
os/net/ipv6/multicast/smrf.c

The multicast engines do not use UIP_LLH_LEN offset when accessing uip_buf, causing to malfunction when UIP_LLH_LEN is non-zero.
This PR also adds new debug traces to help debugging the engines :)

Use UIP_LLH_LEN in multicast engines and add more traces

---

os/net/rpl-classic/rpl-dag.c
os/net/rpl-classic/rpl-icmp6.c

When a node has joined a DODAG as an intermediate router then later becomes DODAG Root, additional cleanup tasks are needed :
* The default route must be removed
* Any DAO retransmission must be cancelled
* Incoming DAO Ack should be ignored
Additionally, when doing a local repair, any pending DAO retransmission must be cancelled too, as there is no more a preferred parent to send it to.

Additional cleanup when becoming DODAG Root (rpl-classic)

---

os/net/ipv6/sicslowpan.c

Sicslowpan places the UDP header at the wrong place when decompressing a packet when UIP_LLH_LEN is non-zero.
This is due to IPPAYLOAD_BUF macro adding a second time UIP_LLH_LEN : The buffer received by uncompress_hdr_iphc() is already offset by UIP_LLH_LEN as buffer is assigned to UIP_IP_BUF, which starts at UIP_LLH_LEN.

Sicslowpan UDP decompression fails when UIP_LLH_LEN != 0

---

os/net/ipv6/tcpip.c
os/net/ipv6/uip6.c

The current remove_ext_hdr() do remove the extension header, but keep the protocol field of the IPv6 header unchanged. This force the calling function to manually set the protocol field afterwards.
With this PR, remove_ext_hdr() updates also the protocol field which is much safer.

Update protocol field in remove_ext_hdr()

---

.travis.yml
examples/libs/data-structures/Makefile
examples/libs/data-structures/data-structures.c
os/lib/circular-list.c
os/lib/circular-list.h
os/lib/dbl-circ-list.c
os/lib/dbl-circ-list.h
os/lib/dbl-list.c
os/lib/dbl-list.h
os/lib/queue.h
os/lib/stack.h
tests/01-compile-base/Makefile
tests/02-compile-arm-ports-01/Makefile
tests/03-compile-arm-ports-02/Makefile
tests/07-simulation-base/31-data-structures-sky.csc
tests/07-simulation-base/code-data-structures/Makefile
tests/07-simulation-base/code-data-structures/project-conf.h
tests/07-simulation-base/code-data-structures/test-data-structures.c
tests/07-simulation-base/js/data-structures.js
tests/08-native-runs/01-test-data-structures.sh
tests/08-native-runs/Makefile

This pull adds libraries for:
* Stacks
* Queues
* Circular, singly-linked lists
* Doubly-linked lists
* Circular, doubly-linked lists
The libraries for stacks and queues are merely wrappers around our existing list library, since it already provides all necessary functions.
The remaining ones are implemented from scratch and have no such dependency.
This pull also adds an example demonstrating / testing the above.
Closes #208

Add libraries and example for common data structures

---

.gitignore

`make TARGET=foo DEFINES=bar savedefines` will create a file called `Makefile.foo.defines`. This needs gitignored.

Gitignore saved defines

---

arch/cpu/nrf52832/Makefile.nrf52832

When building for nrf52dk, `make clean` does not remove `nrf52832.a`. This commit fixes this.

Remove nrf52832.a on make clean

---

arch/cpu/arm/cortex-m/cm3/Makefile.cm3
arch/cpu/cc2538/Makefile.cc2538
arch/cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
arch/cpu/cc26xx-cc13xx/rf-core/prop-mode.c

For reasons discussed long ago and that have to do with how `ld` handles weak symbols, it was decided that it was preferable to link using an explicit list of object files, instead of adding object files to an archive first and then linking using this archive. This was applied for the CC2538, but not for CC13xx/CC26xx.
This pull applies this link logic to all CM3s. For this to work with the Contiki-NG build system, we need `.SECONDEXPANSION:`, so this pull moves that to the common CM3 Makefile.

Link without using an archive file

---

tests/00-doxygen/Makefile
tests/Makefile.compile-test

This cleans up CI tests artifacts, i.e., uses more consistent extensions (which are gitignored)

CI tests: cleaner compilation artifacts

---

arch/platform/srf06-cc26xx/contiki-conf.h

I broke the CC13xx/CC26xx bootloader configuration with #219. This pull fixes this.

Include board.h after configuration is fully known

---

arch/platform/native/contiki-conf.h
arch/platform/native/platform.c

This PR contains bunch of small improvements for the native platform :
* Allow to change the duration of the select timeout (useful on low performance routers)
* Make the stdin select callback configurable (otherwise keeping stdin open prevent putting the process in background)
* Allow to change UIP_CONF_BYTE_ORDER
* Change uip_stats_t from short to int (memory is not a constaint on native, and 16bits counter is too short)

Various native platform updates

---

os/net/rpl-classic/rpl-icmp6.c
os/net/rpl-lite/rpl.c

When a RPL Router has several global addresses, the address advertised in the target option of the outgoing DAO should be the address related to the DODAG network. Currently the code is selecting the first global address, without checking if it's compatible with the DODAG prefix.
This fix add a filter in the address selection code to return an address with the DODAG prefix only. The fix is also made for rpl-lite.

Always select a global address within the DODAG

---

examples/platform-specific/cc26xx/cc26xx-web-demo/cc26xx-web-demo.c
examples/platform-specific/cc26xx/cc26xx-web-demo/net-uart.c

This patch fixes a missing include of `strings.h` in two files that make use of the `strncasecmp` function in the cc26xx-web-demo; the missing includes makes the build of the demo fail.

Include strings.h to access strncasecmp

---

arch/platform/sky/sky-def.h

I believe frame filtering for frames v2 used to work on cc2420/MSPSim on earlier TSCH versions, where the format was from IEEE 802.15.4e-2012. Now with the new IEEE 802.15.4-2015 I suspect this might be broken. In MSPSim at least, it is. All other platforms already disable HW frame filtering, because chips do not understand the new format.
This disables HW frame filtering for TSCH on Sky.

Disable TSCH HW frame filtering on platform sky

---

examples/nullnet/nullnet-broadcast.c
examples/nullnet/nullnet-unicast.c

Adds sanity check to input callback. Without it, the function might be called even with empty payload, e.g. when receiving a TSCH keep-alive.

NullNet examples: check paylaod size before reading it

---

os/services/shell/shell-commands.c

This has already gotten enough people confused... with this PR the logging module will start as usual even when the shell is used. Use the shell command "log all 0" to disable logging at runtime.

Shell: do not disable logging at init

---

examples/rpl-udp/cc2538-node.resc

The cc2538-node.resc script was vulnerable to changing the position of
the vector table.
It also had a wrong hardcoded value. Now it will automatically verify
the position of the `vectors` symbol and set the vtor position
accordingly.

Renode: fix vector table offset in the script.

---

arch/cpu/arm/common/usb/cdc-acm/cdc-acm-descriptors.c
arch/cpu/arm/common/usb/descriptors.h
arch/cpu/cc2538/usb/cdc-acm-descriptors.c
arch/cpu/cc2538/usb/common/descriptors.h

When compiling a custom example, I've encountered the following error which prevented me from compiling:
```
In file included from ../../arch/cpu/cc2538/usb/common/usb-core.c:6:0:
../../arch/cpu/cc2538/usb/common/descriptors.h:9:53: error: duplicate 'const' declaration specifier [-Werror=duplicate-decl-specifier]
extern const struct usb_st_configuration_descriptor const *configuration_head;
```
This fix removes the double const (`const const *`) and changes the pointer to a `const * const` pointer, which was probably intended.
As I am not that familiar with the code, it is best that this fix is double checked.

Deleted duplicate const specifiers

---

arch/platform/srf06-cc26xx/platform.c

As discussed in #187, the CC13xx/CC26xx platform code goes to sleep very aggressively: Unless we have explicitly requested a peripheral to stay on, the code will turn it off when entering a low power mode.
Leaving the UART on during low power increases energy consumption by quite a lot, so the default platform code allows it to go to sleep. This basically means that we lose UART RX in low power, in other words the shell won't work.
This pull implements a temporary workaround: If we are building with Shell support, the platform code will automatically request UART RX while in low-power mode. This makes all affected platforms behave as per the Shell tutorial (which we should update, really, to state that enabling the Shell will increase energy consumption for some platforms).
Fixes #187

Allow Shell operaction for CC13xx/CC26xx

---

Makefile.include
arch/platform/cc2538dk/Makefile.cc2538dk
arch/platform/cooja/Makefile.cooja
arch/platform/jn516x/Makefile.jn516x
arch/platform/native/Makefile.native
arch/platform/nrf52dk/Makefile.nrf52dk
arch/platform/openmote-cc2538/Makefile.openmote-cc2538
arch/platform/sky/Makefile.sky
arch/platform/srf06-cc26xx/Makefile.srf06-cc26xx
arch/platform/zoul/Makefile.zoul

This pull adds `os/net/mac/framer` to `MODULES` in the top-level `Makefile.include`, since we always need it. The pull also removes unnecessary `MODULES` from various platform Makefiles.
Closes #298

Tidy-up MODULES

---

Makefile.include

Makefile.include: support assembly file extensions .s in addition to .S

---

arch/platform/srf06-cc26xx/Makefile.srf06-cc26xx

Fix BOARDS string in srf06-cc26xx platform makefile to accurately reflect all valid values of the BOARD variable.

Fix BOARDS string in srf06-cc26xx platform makefile

---

Makefile.include

#321 broke the build system under GNU Make v3.81. Absolutely nothing will build.
```
$ make TARGET=zoul
CC        ../../arch/cpu/cc2538/cc2538.lds
CC        hello-world.c
LD        hello-world.elf
/usr/local/gcc-arm-none-eabi-5_2-2015q4/bin/../lib/gcc/arm-none-eabi/5.2.1/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol flash_cca_lock_page; defaulting to 0000000000202000
arm-none-eabi-objcopy -O ihex hello-world.elf hello-world.i16hex
arm-none-eabi-objcopy: error: the input file 'hello-world.elf' has no sections
make: *** [hello-world.i16hex] Error 1
rm hello-world.o
```
```
$ make -version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or …
```

Fix build under GNU make v3.81

---

os/net/mac/tsch/tsch-private.h

GCC assumes extern, but other toolchains complain about multiple variable definition at files including this header.
Reported by @serdarkose

Add missing extern keyword

---

examples/coap/coap-example-client.c

A bugfix in line with the discussion in #334 reported.

coap-example: made endpoint static in process

---

arch/platform/srf06-cc26xx/cfs-coffee-arch.h
arch/platform/srf06-cc26xx/common/xmem.c
arch/platform/srf06-cc26xx/launchpad/Makefile.launchpad
arch/platform/srf06-cc26xx/sensortag/Makefile.sensortag
examples/storage/cfs-coffee/Makefile
examples/storage/cfs-coffee/README.md

We add cfs support for srf06-cc26xx's ext-flash to contiki-ng, and test it on `sensortag` and `launchpad`, the test project in example/storage/cfs-coffee, and all test passed.  And we also add the tested platforms to the example's README.

add cfs support for srf06-cc26xx

---

arch/platform/jn516x/dev/micromac-radio.c

- use only vMMAC_SetChannelAndPower()
- remove redundant call in init()

JN516x SDK 4170 build 1745 does not have vMMAC_SetChannel() function

---

arch/platform/srf06-cc26xx/platform.c

Incorrect pre-processor conditional results in cc13xx/cc26xx devices loading the wrong MAC address.
Fixes #354

Fix link layer address retrieval from flash

---

os/net/mac/tsch/sixtop/sixp-nbr.c
os/net/nbr-table.c
os/net/nbr-table.h
os/net/routing/rpl-lite/rpl-dag.c

In addition, this PR also fixes potential issues with multiple initialization of nbr-table.
Fixes #349

Only initialize rpl-neighbor module once

---

os/services/shell/shell-commands.c
os/services/shell/shell.h

Two (relatively) major things and two trivial things.
1. `ping` command without any argument causes NULL-pointer dereference.
1.  Since `log` command help message doesn't fit the buffer in `SHELL_OUTPUT()`, the new line character (`\n`) is gone. Due to this, `ping` command help message doesn't appear in the next line of `log` command help.
1. TAB is used in `shell.h`
1. The shell output message, "Invalid IPv6", would better have "Address" after "IPv6"

shell improvements

---

examples/mqtt-client/Makefile
examples/mqtt-client/README.md
examples/mqtt-client/arch/cpu/cc2538/builtin-sensors.c
examples/mqtt-client/arch/cpu/cc2538/builtin-sensors.h
examples/mqtt-client/arch/cpu/cc26xx-cc13xx/builtin-sensors.c
examples/mqtt-client/arch/cpu/cc26xx-cc13xx/builtin-sensors.h
examples/mqtt-client/arch/platform/cc2538dk/Makefile.cc2538dk
examples/mqtt-client/arch/platform/cc2538dk/als-extend.c
examples/mqtt-client/arch/platform/cc2538dk/als-extend.h
examples/mqtt-client/arch/platform/cc2538dk/mqtt-client-extensions.c
examples/mqtt-client/arch/platform/openmote-cc2538/Makefile.openmote-cc2538
examples/mqtt-client/arch/platform/openmote-cc2538/mqtt-client-extensions.c
examples/mqtt-client/arch/platform/srf06-cc26xx/Makefile.srf06-cc26xx
examples/mqtt-client/arch/platform/srf06-cc26xx/mqtt-client-extensions.c
examples/mqtt-client/arch/platform/zoul/Makefile.zoul
examples/mqtt-client/arch/platform/zoul/mqtt-client-extensions.c
examples/mqtt-client/mqtt-client.c
examples/mqtt-client/mqtt-client.h
examples/mqtt-client/project-conf.h
examples/platform-specific/cc2538-common/mqtt-demo/Makefile
examples/platform-specific/cc2538-common/mqtt-demo/Makefile.target
tests/02-compile-arm-ports-01/Makefile
tests/03-compile-arm-ports-02/Makefile

This pull proposes a cross-platform MQTT client example and deletes the respective example under `cc2538-common`.
The example will work on all platforms that support the button HAL. With a little hacking it also works with native.
Easiest way to test is to run a mosquitto broker on a linux/OSX device and by setting `MQTT_CLIENT_CONF_BROKER_IP_ADDR` to the v6 address of said device.
Still somewhat of a WiP / need to test for various boards, but I thought I'd throw it out here for comment.
Requires #365

Cross-platform MQTT client example

---

arch/platform/srf06-cc26xx/launchpad/cc1310/board.h
arch/platform/srf06-cc26xx/launchpad/cc1350/board.h
arch/platform/srf06-cc26xx/launchpad/cc2650/board.h

Launchpad LED colour mappings are incorrect. This pull fixes this.

Fix launchpad LED colour mappings

---

os/net/mac/tsch/tsch-rpl.c
os/net/routing/rpl-lite/rpl-dag.c

Do not reset link stats on RPL local repair. There is no reason to assume these need a reset. RPL operates a layer above. By not doing the reset, we allow local repair and global repair to go through a bit faster (no need to rebuilt fresh link estimates).
In the particular case of TSCH+RPL, make sure to reset link stats when leaving the TSCH network, right before a local repair. TSCH link statistics tend to get broken under de-synchronized operation.

RPL local repair

---

os/net/ipv6/sicslowpan.c

This PR does simply two things:
- use `LOG_DBG_` instead of `LOG_DBG` to print hex decimals of a packet
- replace TABs with spaces

sicslowpan: fix debug messages and remove TABs

---

os/services/shell/shell-commands.c

The following three `PT_THREAD` implementations should be surrounded by `#if UIP_CONF_IPV6_RPL` and `#endif` since the corresponding commands are enabled only if `UIP_CONF_IPV6_RPL` is true.
- `cmd_rpl_set_root()`
- `cmd_rpl_local_repair()`
- `cmd_rpl_global_repair()`
```C
[shell-command.c]
718 struct shell_command_t shell_commands[] = {
(snip)
725 #if UIP_CONF_IPV6_RPL
726   { "rpl-set-root",         cmd_rpl_set_root,         "'> rpl-set-root 0/1 [prefix]': Sets node as root (1) or not (0). A /64 prefix can be optionally specified." },
727   { "rpl-local-repair",     cmd_rpl_local_repair,     "'> rpl-local-repair': Triggers a RPL local repair" },
728   { "rpl-global-repair",    cmd_rpl_global_repair,    "'> rpl-global-repair': Triggers a RPL global repair" },
729 #endif /* …
```

shell: add missing UIP_CONF_IPV6_RPL guard

---

tests/17-tun-rpl-br/01-border-router-cooja.csc
tests/17-tun-rpl-br/01-border-router-cooja.sh
tests/17-tun-rpl-br/02-border-router-cooja-tsch.csc
tests/17-tun-rpl-br/02-border-router-cooja-tsch.sh
tests/17-tun-rpl-br/03-border-router-sky.csc
tests/17-tun-rpl-br/03-border-router-sky.sh
tests/17-tun-rpl-br/04-border-router-traceroute.csc
tests/17-tun-rpl-br/04-border-router-traceroute.sh
tests/17-tun-rpl-br/07-native-border-router-cooja.sh
tests/17-tun-rpl-br/test-border-router.sh
tests/17-tun-rpl-br/test-native-border-router.sh
tests/Makefile.script-test

This makes all simulations real-time for more predictable run-time. Wait times for topology formation are adjusted, from 20s to now 60s or 120s (in the TSCH case). This is an attempt at making the BR tests non-flaky again.

Border router tests: make all simulations real-time

---

arch/cpu/cc26xx-cc13xx/cc26xx.ld
examples/platform-specific/cc26xx/cc26xx-web-demo/project-conf.h

As previously discussed in the Contiki issue tracker, the size of memory reserved for stack region on CC26xx is inadequately small.
For example, the cc26xx-web-demo to process some simple CoAP requests use 768 bytes of stack (measured with the stack check library). It has >1000 bytes of stack memory actually available, so it doesn't crash, but this is still bad. Custom applications developed on top of this demo may compile and link, give their developers false sense of security, but then fail at runtime.
This PR proposes to increase it to 1024 bytes (In SPHERE, we're using ~2000 bytes). With the new "build all" script I tested that this setting does not cause build failures on any examples - all examples that build with 256 byte setting also build with 1024 byte setting.

CC26xx: increase size of the region reserved for stack from 256 bytes to 1024 bytes

---

os/net/mac/tsch/Makefile.tsch

I cannot immediately see the reason why this Makefile is required.

Remove obsolete Makefile

---

os/net/routing/rpl-lite/rpl-dag.c
os/net/routing/rpl-lite/rpl.h
os/services/shell/shell-commands.c

This is one more PR related to #128. Basically helps fixing a network through a DTSN increment as a shell command. This will ask the whole network to resend DAO. Compared to global repair:
+ No transition to new version means nodes remain connected at all times. In a global repair, nodes may transiently have no preferred parent.
- Slower (no Trickle reset) and less of a clean-slate rebuild (topology remains unchanged, only route registrations are refreshed)

Shell: added ability to trigger a RPL DTSN increment

---

tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh

- LWM2M standalone test did not build using the expected source code
- LWM2M standalone test could leave running background processes
- the LWM2M tests now use periodic checks to faster finish successful tests
- the tests now clean before building to ensure the tests are executed with the correct configuration.

Fixed some issues with the LWM2M IPSO and standalone regression tests

---

arch/cpu/native/Makefile.native
arch/platform/native/Makefile.native

Default `AROPTS` are `rcf`. `ar` on OS X does not like `f`, but there is no reason to remove `c` (in fact it's good to have it cause it suppresses some ar output that personally annoys me 😄 ).
Currently we specify `AROPTS` for OS X in two places: The CPU makefile and the platform makefile, and the two don't even agree.
This pull deletes the snippet from the platform makefile and sets OSX `AROPTS` to  `rc` in the cpu makefile.

Tidy-up AROPTS for cpu native

---

arch/cpu/native/Makefile.native
arch/cpu/native/int-master.c

This PR "implements" master interrupt manipulation on native. This allows a number of things to build for this platform

Emulate interrupt manipulation on native

---

os/net/routing/rpl-lite/rpl-conf.h
os/net/routing/rpl-lite/rpl-icmp6.c
os/net/routing/rpl-lite/rpl-timers.c
os/net/routing/rpl-lite/rpl.c
os/net/routing/rpl-lite/rpl.h

This PR aims to change the RPL_LEAF_ONLY flag present in RPL-Lite to be a run-time flag so that it can be changed dynamically. The flag is used to force a node to be just a leaf inside the RPL topology, by basically advertsing an infinite rank in the DIO.

Change RPL_LEAF_ONLY flag to a run-time flag

---

examples/coap/coap-example-client.c
examples/coap/coap-example-server.c
examples/coap/plugtest-server.c
examples/ipso-objects/example-server.c
examples/platform-specific/cc26xx/cc26xx-web-demo/coap-server.c
examples/platform-specific/cc26xx/very-sleepy-demo/very-sleepy-demo.c
examples/platform-specific/jn516x/rpl/coap-dongle-node/dongle-node.c
examples/platform-specific/jn516x/rpl/coap-dr1175-node/dr1175-node.c
examples/platform-specific/jn516x/rpl/coap-dr1199-node/dr1199-node.c
examples/platform-specific/jn516x/tsch/tx-power-verification/node/node.c
examples/platform-specific/jn516x/tsch/uart1-test-node/uart1-test-node.c
examples/platform-specific/nrf52dk/coap-demo/coap-client/coap-client.c
examples/platform-specific/nrf52dk/coap-demo/coap-server/coap-server.c
os/contiki-main.c
os/net/app-layer/coap/coap-engine.c
os/net/app-layer/coap/coap.c
os/net/app-layer/coap/module-macros.h
os/services/lwm2m/lwm2m-engine.c

This PR proposes to auto-initialize the CoAP module whenever it is included, so that one does not have to call `coap_engine_init()` in addition to adding the module.

CoAP: auto-initialize module

---

os/net/app-layer/coap/coap-engine.c

The block offset is stored in a signed variable in calls to CoAP handlers and too large block offsets will overflow into negative values.
The fixes the issue reported in #425.

Added check for block offset overflow in CoAP block2 requests.

---

examples/platform-specific/cc26xx/cc26xx-web-demo/Makefile
examples/platform-specific/cc26xx/cc26xx-web-demo/cetic-6lbr-client.c
examples/platform-specific/cc26xx/cc26xx-web-demo/project-conf.h
tests/02-compile-arm-ports-01/Makefile

The cc26xx 6lbr client example was meant for RPL Classic.
This PR:
* Fixes compilation of the example for RPL Classic
* Only compiles the example when RPL Classic is enabled
* Adds a compile test for this example with RPL Classic
Fixes #442

Fixing cc26xx 6lbr client example

---

os/net/ipv6/uiplib.c

This fixes `uiplib_ipaddr_snprint()` to null-terminate the output string when printing the unspecified IPv6 address (::).

uiplib: ensure output string is null-terminated when printing the unspecified address

---

arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
arch/platform/jn516x/Makefile.jn516x
arch/platform/sky/Makefile.common
arch/platform/zoul/Makefile.zoul
os/services/rpl-border-router/native/Makefile.native
tools/docker/Dockerfile
tools/vagrant/bootstrap.sh

This simply adds `rlwrap` to `make login` and the native BR, giving us shell command history for free. With this, we can use move the cursor while in shell via directional arrows. UP gives the last command. CTRL+R does a search. History persists across executions. There are probably more features :)
Also adds the tool to Docker and Vagrant scripts.
The PR adds `rlwrap` to Linux (tested) and OSX (not tested, do not merge before somebody confirms it works!).
If we merge this, the following wiki pages will need updating:
* https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation-on-Linux
* https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation-on-OS-X

Shell client with history

---

examples/hello-world/hello-world.c

Programming a device with the hello-world example and then connect to the device via serial port to see the output normally shows nothing since the example only prints the message once after boot. This might be confusing for new users.
This PR adds a periodic timer to print the message periodically and also replaces the `printf()` with a call to the logging API.

Added a periodic timer to the hello-world example

---

arch/cpu/cc26xx-cc13xx/cc13xx-cc26xx-conf.h

After having locked myself out of my kit for the gazzillionth time and after multiple complaints by our users, I have decided to change the CC13x0/CC26x0 ROM bootloader default to 'enabled'.
But I have also updated the wiki page with clear instructions that it needs disabled for production/deployment images...
Closes #390

Enable the CC13x0/CC26x0 ROM bootloader by default

---

Makefile.include

Well this really is just a proposal. I found the current `distclean` output too verbose to be readable:
```
...
make openmote-cc2538 clean
make[1]: Entering directory '/home/simon/contiki-ng/examples/hello-world'
rm -f *.d *.e *.o contiki-ng-openmote-cc2538.a *.elf *.bin *.lst *.hex *.i16hex
rm -rf obj_openmote-cc2538
rm -f hello-world-openmote-cc2538.map
rm -f hello-world.openmote-cc2538
make[1]: Leaving directory '/home/simon/contiki-ng/examples/hello-world'
make sky clean
make[1]: Entering directory '/home/simon/contiki-ng/examples/hello-world'
rm -f *.d *.e *.o contiki-ng-sky.a *.firmware *.ihex
rm -rf obj_sky
rm -f hello-world-sky.map
rm -f hello-world.sky
make[1]: Leaving directory '/home/simon/contiki-ng/examples/hello-world'
...
```
With this PR:
```
...
make openmote-cc2538 clean …
```

Make distclean: less verbose output

---

os/services/shell/shell-commands.c

This fixes a null pointer reference if the shell command `rpl-status` is called when the device has no preferred parent.

Check if a preferred parent exists before showing status in shell command 'rpl-status'

---

os/net/app-layer/coap/coap-block1.c
os/net/app-layer/coap/coap-blocking-api.c
os/net/app-layer/coap/coap-callback-api.c
os/net/app-layer/coap/coap-observe-client.c
os/net/app-layer/coap/coap-observe.c
os/net/app-layer/coap/coap-res-well-known-core.c
os/net/app-layer/coap/coap-separate.c
os/net/app-layer/coap/coap-timer-default.c
os/net/app-layer/coap/coap-transactions.c
os/net/app-layer/coap/tinydtls-support/dtls-support.c
os/services/lwm2m/lwm2m-device.c
os/services/lwm2m/lwm2m-engine.c
os/services/lwm2m/lwm2m-firmware.c
os/services/lwm2m/lwm2m-plain-text.c
os/services/lwm2m/lwm2m-rd-client.c
os/services/lwm2m/lwm2m-security.c
os/services/lwm2m/lwm2m-server.c
os/services/lwm2m/lwm2m-tlv-writer.c

Shorter log module names for CoAP/LWM2M/DTLS for nicer log output

---

os/net/routing/nullrouting/nullrouting.c

For consistency with nullnet and nullmac.

Nullrouting: lowercase string description

---

examples/storage/antelope-shell/Makefile
examples/storage/cfs-coffee/Makefile

Fixed the Makefiles of the storage examples as they did not support Zoul and missed a dk in the cc2538dk platform.

fixed platforms to build for in Makefile

---

os/storage/antelope/db-options.h

This PR makes it possible to run Antelope using the default configuration on some platforms with relatively small file system areas. Previously, the shell-db example would not work on Zoul Firefly without reducing DB_COFFEE_RESERVE_SIZE by a large amount. Thanks to @joakimeriksson for reporting the problem.

Improved default file size in Antelope

---

Makefile.include

Just a small commit to fix a typo on the usage string which could have caused confusion.

Fixed typo for savetarget target in usage string

---

examples/lwm2m-ipso-objects/Makefile
examples/lwm2m-ipso-objects/README.md
examples/lwm2m-ipso-objects/example-server.c
examples/lwm2m-ipso-objects/serial-protocol.c

The server-example in lwm2m-ipso-object example was using old APIs for listing routes and CoAP blocking requests. This updates the example to use the latest APIs.

Updated lwm2m-ipso-object server-example for latest RPL/CoAP APIs

---

arch/platform/zoul/dev/dht22.c
arch/platform/zoul/dev/dht22.h
examples/platform-specific/zoul/Makefile
examples/platform-specific/zoul/test-dht22.c

The DHT22 driver did not work.
The example in `examples/platform-specific/zoul/test-dht22.c` was not compiling because of wrong types.
However, also with fixed types the driver was not able to read the sensor properly. The output of the example above was just `Failed to read the sensor`.
The culprits were some parameters slightly off, and a misplaced pin reading. 
Now it is fixed.
(Tested with "ReMote rev b" and "Grove Temperature and Humidity Sensor Pro").

Fixed driver for DHT22 sensor in zoul platform 

---

os/net/link-stats.c
os/net/routing/rpl-classic/rpl-mrhof.c
os/net/routing/rpl-lite/rpl-mrhof.c

As discussed in https://github.com/contiki-ng/contiki-ng/issues/499 , and as reported by other users in the past, the added churn from squared ETX can cause the network to never converge to a stable state. This happens in scenarios with high congestion or poor links, where link estimates keep changing, and the changes are amplified by squaring.
This PR disabled the feature by default. A rule of thumbs is to always start without, and if the network operate stably, try enabling it to push the reliability further. But in more noisy/dense environments, stick to the default.

RPL Lite: disable MRHOF ETX squaring by default

---

Makefile.include

This pull extends the usage string to include some more make targets specified in `Makefile.include`

Extend usage string

---

tools/tools-utils.c

It is currently impossible to specify a baudrate of 230400 because of this missing case statement.

Add missing case statement

---

examples/libs/ipv6-uipbuf/Makefile
examples/libs/ipv6-uipbuf/README.md
examples/libs/ipv6-uipbuf/ipv6-uipbuf-cooja.csc
examples/libs/ipv6-uipbuf/ipv6-uipbuf-sky.csc
examples/libs/ipv6-uipbuf/project-conf.h
examples/libs/ipv6-uipbuf/udp-client.c
examples/libs/ipv6-uipbuf/udp-server.c
examples/rpl-udp/udp-client.c
os/net/link-stats.c
tests/03-compile-arm-ports-02/Makefile

I believe the `uipbuf_set_attr` example did cause confusion, by sending some unreliable packets. When not ACKed at MAC, can have bad consequences on link estimates, as ETX will be updated with `ETX_NOACK_PENALTY`. Also, the example is intended as a minimal RPL UDP example and seems to be the starting point to many users, so I think this is not the ideal place to document `uipbuf_set_attr`.

rpl-udp example: remove uipbuf tuning of MAC retries

---

os/services/rpl-border-router/native/slip-dev.c
tests/17-tun-rpl-br/09-native-border-router-cooja-frag.sh
tests/17-tun-rpl-br/test-native-border-router.sh

`memcpy` was used where `memmove` was required. Caused a bug whenever the amount of data left in Tx buffer was greater than what we just sent. Depending on timing of calls to `slip_flushbuf`, the node might end up sending broken packets.
As a result, fragmentation with more than two packets did not work on NBR+slip-radio in Cooja.
This PR adds a CI test accordingly.

Native border router SLIP fix

---

Makefile.include
arch/cpu/native/Makefile.native

OSX requires a different linker flag to enable linker warnings as errors. The native platform will now set the correct linker flag when compiling under OSX. Also made it possible to disable this feature and allow linker warnings by building with `WERROR` set to 0.

Added a configurable linker flag to enable linker warnings as errors

---

os/net/mac/ble/ble-l2cap.c
os/services/ip64/ip64-arp.c

Despite the recent introduction of the `-Wno-unused-const-variable` flag in commit 15a3f32b29
and waiting for the new version of the compilers suggested in #517, we can nevertheless remove already some bugs and unused codes caught by more recent versions of arm-none-eabi-gcc (currently in Debian unstable 15:6.3.1+svn253039-1+b1 6.3.1 20170620 instead of the 5.2.1 20151202 revision 231848 in the docker).

Warnings gcc6.3.1

---

.gitignore

Currently, after a `make -C tests/` and a `make -C tests/compile-all/`, the git repository is not clean :
```
user@5e5ef3811f69:~/contiki-ng$ git status
On branch develop
Your branch is up-to-date with 'official/develop'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   tools/jn516x/serialdump-linux
modified:   tools/sky/serialdump-linux
Untracked files:
(use "git add <file>..." to include in what will be committed)
tests/18-coap-lwm2m/Californium.properties
tests/18-coap-lwm2m/leshan-server-demo-1.0.0-SNAPSHOT-jar-with-dependencies.jar
no changes added to commit (use "git add" and/or "git commit -a")
```
Together with the PR #512, this PR will make the .gitignore …

ignore files produced during coap-lwm2m tests

---

os/net/ipv6/uiplib.c
os/net/ipv6/uiplib.h
os/net/routing/rpl-lite/rpl-neighbor.c
os/net/routing/rpl-lite/rpl-neighbor.h
os/services/shell/shell-commands.c
os/services/shell/shell.c
os/sys/log.c

This adds `uiplib_ipaddr_describe` for consistent printing of IPv6 addresses into a string, de-duplicating three code locations. 
Similarly, this adds `rpl_neighbor_describe` to print description of a RPL neighbor into a string. This enable a new shell command `rpl-status`, and might as well be used in the future by Web or CoAP servers to deliver RPL status.

snprintf-based logging for IPv6 and RPL neighbor

---

os/net/ipv6/uip-nd6.c

Prototype of memcmp is :
`int memcmp(const void *s1, const void *s2, size_t n);`
return value of memcmp is a positive or negative or null integer and so **should not be cast in an uint8_t**, the sign of a non-zero return value is determined by the sign of the difference of the first n bytes of the buffers s1 and s2
Currently, `make -C tests/09-ipv6` works on the docker because the Ubuntu 32 bits uses a version of memcmp that will return 1 0 or -1
but on a Debian 64 bits (GLIBC 2.27-3, gcc 7.3.0-19), I get :
```
$ cat tests/09-ipv6/summary 
01-ping-lla-csma-w-rpl                   TEST OK      1/1
02-ping-ula-csma-w-rpl                   TEST OK      1/1
03-ping-lla-tsch-w-rpl                   TEST OK      1/1
04-ping-ula-tsch-w-rpl                   TEST OK      1/1 …
```

Fix neighbor discovery bug

---

arch/platform/srf06-cc26xx/sensortag/cc2650/board.h
examples/platform-specific/cc26xx/cc26xx-web-demo/README.md
examples/platform-specific/cc26xx/cc26xx-web-demo/project-conf.h

Older CC2650 sensortags have a Winbond W25X40CL 4MBit SPI flash. Newer ones have a Macronix MX25R8035F 8MBit part. The parts have almost identical instruction sets and are both supported by our generic external flash driver. The key difference between the two parts is that they have different Manufacturer and Device IDs.
This commit allows us to switch between the two: We default to the new revision, and allow users to build for the older one by defining `SENSORTAG_CC2650_REV_1_2_0` to 1.
Current tags are version 1.5.1. Older tags are version 1.2.0. To identify older tags, look for "Rev: 1.2" printed on the PCB. They should also have a sticker that reads "Rev: 1.3.0" and "HW Rev 1.2.0".
Fixes #530

Differentiate flash part across sensortag/cc2650 versions

---

tests/08-native-runs/01-test-data-structures.sh
tests/17-tun-rpl-br/04-border-router-traceroute.sh
tests/17-tun-rpl-br/05-native-ping.sh
tests/17-tun-rpl-br/06-native-coap.sh
tests/17-tun-rpl-br/test-border-router.sh
tests/17-tun-rpl-br/test-native-border-router.sh
tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh
tests/utils.sh

pgrep pattern shoud be smaller than 15 characters
Indeed `CODE=test-data-structures` can't be killed with `pgrep $CODE | xargs kill -` as we can see with 
```
user@81958babe9d8:~/contiki-ng$ make -C tests/08-native-runs/
make: Entering directory '/home/user/contiki-ng/tests/08-native-runs'
========== Running script test 01-test-data-structures.sh ==========
Starting native node
Closing native node
test-data-structures             TEST OK
========== Summary ==========
test-data-structures             TEST OK
make: Leaving directory '/home/user/contiki-ng/tests/08-native-runs'
```
and then 
```
user@81958babe9d8:~/contiki-ng$ top
top - 18:51:02 up 3 days, 11:45,  0 users,  load average: 0.70, 0.50, 0.52
Tasks:   4 total,   2 running,   2 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.2 us, …
```

node killed at the end of 08-native-runs tests

---

os/net/app-layer/coap/coap-callback-api.c
os/net/app-layer/coap/coap-callback-api.h

Hi All!
Right now the function `coap_send_request` does not give any feedback in case there is no available transaction available to use (if `coap_new_transaction` returns NULL). Therefore, the applications on top cannot know if the request is actually been sent or not. 
Therefore, this small PR makes the `coap_send_request` return 1 if there is a transaction available and 0 otherwise, so that applications running on top can know if the request is actually sent.

Feedback in CoAP send request 

---

arch/dev/ext-flash/ext-flash.c
arch/dev/ext-flash/ext-flash.h
os/net/ipv6/uiplib.c
os/net/ipv6/uiplib.h

The documentation for `/arch/dev/ext-flash` and ` os/net/ipv6/uiplib.[ch]` was placing the modules at the wrong position in the doxygen module hierarchy. This pull fixes this, and adds a little bit of content to both.

Improve doxygen module structure and content

---

examples/libs/shell/Makefile

Dear all,
The shell example introduced recently in 77939f421 does not link for the sky platform : 
```
user@3cdf6ad03a12:~/contiki-ng$ make -C examples/libs/shell/ -j TARGET=sky BOARD=default all
make: Entering directory '/home/user/contiki-ng/examples/libs/shell'
mkdir obj_sky
CC        example.c
...
LD        example.sky
/usr/local/bin/../lib/gcc/msp430/4.7.2/../../../../msp430/bin/ld: example.sky section `.rodata' will not fit in region `rom'
/usr/local/bin/../lib/gcc/msp430/4.7.2/../../../../msp430/bin/ld: section .vectors loaded at [0000ffe0,0000ffff] overlaps section .rodata loaded at [0000f4e4,0001031a]
/usr/local/bin/../lib/gcc/msp430/4.7.2/../../../../msp430/bin/ld: region `rom' overflowed by 1222 bytes
/usr/local/bin/../lib/gcc/msp430/4.7.2/mmpy-16/libcrt0.a(_copy_data.o): In …
```

exclude sky platform for examples/libs/shell

---

Makefile.include
Makefile.tools
tests/Makefile
tests/Makefile.compile-test

So, if the top-level command was something other than `make` (e.g. `gmake`, or `/<path>/make` from some different location), the sub-make invocations will use the same version of make, instead of whatever happens to be in the path.
This also changes make's behaviour slightly, in that some flags are automatically passed to the sub-make.

Use $(MAKE) instead of make to invoke recursively

---

tests/17-tun-rpl-br/04-border-router-traceroute.sh
tests/17-tun-rpl-br/test-border-router.sh
tests/17-tun-rpl-br/test-native-border-router.sh

Some minor modifications related to the recent 2605a5174
tunslip6 is already a dependency of the target ''make -C examples/rpl-border-router connect-router-cooja TARGET=zoul''
This PR removes the strange logs in https://travis-ci.org/contiki-ng/contiki-ng/jobs/384851974 
```
========== Running script test 01-border-router-cooja.sh ==========
Starting Cooja simulation 01-border-router-cooja.csc
Starting tunslip6
make[1]: Entering directory '/home/user/contiki-ng/tools'
make[1]: *** No rule to make target 'tunslip6'.  Stop.
make[1]: Leaving directory '/home/user/contiki-ng/tools'
```

minor modifications related to tools/serial-io/tunslip6

---

.gitignore
tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh
tests/18-coap-lwm2m/08-lwm2m-qmode-ipso-test.sh
tests/18-coap-lwm2m/09-lwm2m-qmode-standalone-test.sh

The leshan server with qmode enabled introduced in 1dfa62fc88 is downloaded in tests/18-coap-lwm2m/09-lwm2m-qmode-standalone-test.sh but it's not the one that is actually used in the test...
Update also the .gitignore

Leshan server qmode fix

---

os/net/app-layer/coap/coap-uip.c

It did not correctly mark the CoAP endpoint as secure when a port was specified.
Thanks to Carlos Gonzalo Peces for reporting the issue.

coap: bug fix when parsing secure CoAP endpoint with a specified port.

---

.travis.yml
tools/docker/Dockerfile

With this PR, any change to the Docker directory will force Travis runs to build the new Docker image, and run all tests from the new image. In case of a merge to develop, the new image is automatically pushed to Dockerhub, i.e, available with a pull from other jobs.
This also moves the Contiki-NG Docker image form `simonduq/conitki-ng` to `contiker/contiki-ng`. Credentials to push there are handled as Travis encrypted environment variables. Only readable for updates of any `contiki-ng/contiki-ng` branch, but not from forks or PRs.
Closes #543

Docker image update from Travis

---

.travis.yml

As it turns out, https://github.com/contiki-ng/contiki-ng/pull/554, failed to push the new Dockerfile to Dockerhub. No real harm, in that this does not break anything, but let's get this fixed.
The issue was in the test for changes in the `tools/docker` directory, done as follows:
```
git diff --name-only $TRAVIS_BRANCH...HEAD -- tools/docker | wc -l
```
This worked fine in PRs, but failed to detect the Dockerfile change on the merge CI run.
This PR fixes the issue by using this instead:
```
git diff --name-only $TRAVIS_COMMIT_RANGE -- tools/docker | wc -l
```
I tested this on my own repo, as follows:
* Do a PR that changes the Dockerfile: https://travis-ci.org/simonduq/contiki-ng/builds/387999221
The PR test issues:
```
Docker image changed, build from Dockerfile
```
* Merge the PR: …

Travis Docker push fix

---

arch/cpu/cc26xx-cc13xx/rf-core/prop-mode.c
arch/cpu/cc26xx-cc13xx/rf-core/rf-core.c
arch/cpu/cc26xx-cc13xx/rf-core/rf-core.h

Hello,
now after some problems with the pull request the correct one.
After i testes these pull request from contiki contiki-os/contiki#2161 and it gave at high traffic a huge improvement for me, it should be even changed at contiki-ng.
It only implements the rx full IRQ handling, even the points regarding the bypass of the rf on checks should not apply to it.
Please check the request.
Regards,
Martin

rx full IRQ handling for cc13xx/cc26xx

---

.travis.yml

Currently, when building the docker image fails, the normal test will continue anyway. This PR aborts the test early whenever the image failed to build.

CI: fail test in case building Docker image failed

---

tools/serial-io/tunslip6.c

e5c7437 fixed a bug that was preventing multiple instances of tunslip6 from running. This same commit however broke tunslip6 on Mac OS, as documented in contiki-os/contiki#1560 as well as in contiki-ng/contiki-ng#466
Basically the commit in question merely removed some code. This commit puts that code back in, but makes it conditional for Mac OS.
Fixes #466

Specify default tun/tap name on Mac OS

---

LICENSE.md
README.md

This commit changes the LICENSE.md text such that it can get automatically detected by licensee. This will make the license appear in the project's overview on github.
Additional information that was previously in LICENSE.md is moved to the README.

Enable license auto-detection on github

---

os/net/app-layer/coap/coap-blocking-api.c
os/net/app-layer/coap/coap-blocking-api.h
os/net/app-layer/coap/coap-callback-api.c
os/net/app-layer/coap/coap-callback-api.h
os/net/app-layer/coap/coap-request-state.h
os/services/lwm2m/lwm2m-rd-client.c

This pull request unifies the `coap_request_state` structs into only one for both two APIs with all the common elements. Then, each API has its own extra elements, which are the process and protothread in the case of the blocking-API and the callback function for the callback API. 
Also, status codes are added to have more information about the request. Using these codes one can know if the request is timed out, if it has gotten a response, if there is a block error, etc. 
The LwM2M rd client is also updated to use these codes. Right now it can only check if the response is NULL or not in the callbacks, not being able to distinguish between a timeout, a block error or a finished request. This also allows to remove the `recover_from_delay` mechanism, since the callback will be called with …

CoAP: unified request_state for both blocking and callback APIs and add status codes 

---

os/net/ipv6/uip-icmp6.c

This patch just moves log message output from the beginning to the end of the function.
It prints `UIP_IP_BUF->destipaddr`, but this is updated in the middle of this function. Before this fix, the address was NOT the destination of the ICMPv6 packet, but was whatever destination that previous operation wrote to uip_buf.

Fix log output from uip_icmp6_send function.

---

os/storage/antelope/aql-adt.c
os/storage/antelope/aql-lexer.c
os/storage/antelope/aql-parser.c
os/storage/antelope/aql.h
os/storage/antelope/db-options.h
os/storage/antelope/lvm.c
os/storage/antelope/lvm.h
os/storage/antelope/relation.c

Addresses the issues pointed out in #594, #595, #596, #597, #598, and #599.
The attack vector, as pointed out in the reports, is limited to when an attacker has access to insert DB queries directly, which should not be allowed for multiple reasons. Still, the reports will help remove some crashes on invalid input.
Next on the agenda is to create a new set of tests for storage (including tests for the aforementioned issues), but this will be addressed in a later PR.
Thanks to @cve-reporting for the report, and sorry for the late reply -- a long vacation just ended.
Fixes #594 
Fixes #595
Fixes #596 
Fixes #597 
Fixes #598 
Fixes #599

Fix Antelope issues with memory checking

---

os/services/ipso-objects/ipso-temperature.c

With this change resource /3303/0/5700 (Temperature Sensor Value) could be
read and observe without error. 
Tested with TARGET=cc2538dk and Leshan Version 1.0.0-SNAPSHOT
Signed-off-by: Kiril Petrov <contiki@geomi.org>

Fix get_temp_value for lwm2m-ipso-object example

---

os/net/app-layer/coap/coap-transactions.c

I'm new to Contiki, but I think I found a bug in the CoAP implementation.
When sending a CON request for which no ACK is received, this is what I observe:
1. Packet is sent
2. Wait for ~3 s
3. Packet is retransmitted
4. Wait for ~6 s
5. Packet is retransmitted
6. Wait for ~12 s
7. Packet is retransmitted
8. Wait for ~24 s
9. Packet is retransmitted
10. Transaction times out
Between steps 9 and 10, I would expect the system to wait for ~48 s, but that does not happen. I think this is a bug.
This pull request proposes a simple fix.

Fix bug in CoAP retransmission policy

---

os/net/routing/rpl-classic/rpl-dag-root.c
os/net/routing/rpl-classic/rpl-dag.c
os/net/routing/rpl-classic/rpl-ext-header.c
os/net/routing/rpl-classic/rpl-icmp6.c
os/net/routing/rpl-classic/rpl-mrhof.c
os/net/routing/rpl-classic/rpl-nbr-policy.c
os/net/routing/rpl-classic/rpl-of0.c
os/net/routing/rpl-classic/rpl-timers.c
os/net/routing/rpl-classic/rpl.c

Debugging could only be enabled pr. file at compile time. Refactor to use sys/log.h module. Also removes some regular printfs.
Some questions though:
* Replacing `PRINTLLADDR((uip_lladdr_t *) _)` with `LOG_DBG_LLADDR(_)`, i've seen it in rpl-lite but i'm wondering if this is correct?
* Where variables are used exclusively withing a `LOG_DBG_ENABLED` block should the definition be within the `#if` block or should i add another `#if` at the top of function with the variable declaration (see https://github.com/contiki-ng/contiki-ng/compare/develop...lafka:lafka-debug-fix?expand=1#diff-98a2a62e3c8b2de1cc3b9efe231c97fbR67)
* `handle_periodic_timer` in `rpl-nbr-policy.c`, should this really be there? it changes functionality based on LOG_LEVEL

Use LOG_ constants infavour of PRINTF for rpl-classic

---

arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx

I think everyone when getting started with CC26xx/CC13xx has seen this error message.
```
In file included from ../../../arch/platform/srf06-cc26xx/./contiki-conf.h:79:0,
from ../../../os/contiki.h:37,
from node.c:39:
../../../arch/platform/srf06-cc26xx/srf06/cc26xx/board.h:58:17: fatal error: ioc.h: No such file or directory
#include "ioc.h"
^
compilation terminated.
```
This patch aims to replace it with something more descriptive.

Generate a descriptive error message in case cc26xxware/cc13xxware does not exist

---

arch/cpu/arm/Makefile.arm

For ARM platforms, the `-Werror` flag is set unconditionally. This breaks the build with nonstandard configurations, and is inconsistent with the behavior on other platforms.

Set -Werror only if WERROR is set

---

arch/cpu/cc26xx-cc13xx/cc13xx-cc26xx-conf.h

Make cc26xx radio driver configurable in prop mode
It's already possible to override the default radio driver when operating in IEEE mode. This patch opens up for users defining their own radio driver when using prop mode. This is useful when overriding certain radio driver functions.

Make cc26xx radio driver configurable in prop mode operation

---

os/net/routing/rpl-classic/rpl.c

Compiling with RPL_CONF_WITH_PROBING := 0 was not possible due to `urgent_probing_target`
not present.

RPL-CLASSIC: Add guard for urgent probing

---

os/net/ipv6/resolv.c

When receiving a DNS response, the TTL field is parsed and used to determine when a record should be flagged as expired. This parsing seems to assume the TTL is stored in an _uint8_t_ array, while it is actually in an _uint16_t_ array - and thus record expirations are incorrect. This PR fixes this.
Some extra scrutiny might be warranted here, since this code is  ~6 years old, and as far as I can tell it has always been like this... 🤔 
Disclaimer: I currently live in contiki - not tested on contiki-ng

Set correct DNS record expiration time

---

os/net/routing/rpl-lite/rpl-conf.h
os/net/routing/rpl-lite/rpl-dag.c

This gives the developer the tools to validate a dio before using it to init the dag. If 0 is returned then the dag will not be initiated.
Main use case for this is preventing the device from joining certain networks.
**Some background:** 
We are creating a product that has a local server that the nodes in the network need to communicate with. The server has a whitelist of devices that are allowed to communicate with it. It is possible that more then one network is running (one in company a, the other in company b across the street for example). If the server tells the device it will not communicate with it because it is not whitelisted the device should leave the network and try another one. This validation function will allow us to control if the device should join the network or not, …

Add option to validate dio before init dag

---

os/net/routing/rpl-classic/rpl-dag-root.c

RPL classic currently fails to compile for TARGET sky.
```
CC        ../../os/net/routing/rpl-classic/rpl-dag-root.c
../../os/net/routing/rpl-classic/rpl-dag-root.c: In function ‘set_global_address’:
../../os/net/routing/rpl-classic/rpl-dag-root.c:71:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
../../os/net/routing/rpl-classic/rpl-dag-root.c:71:5: note: use option -std=c99 or -std=gnu99 to compile your code
```
We can fix this by compiling with `-std=c99` or `-std=gnu99`, or we can remove the initial declaration from within the for loop. This pull chooses the latter since this is what we do consistently elsewhere in the code.

Fix RPL classic compilation for TARGET sky

---

arch/platform/srf06-cc26xx/contiki-conf.h
examples/platform-specific/cc26xx/ble-ipv6/project-conf.h

This removed BUTTON_SENSOR_CONF_ENABLE_SHUTDOWN and button_sensor definitions: they are dead code since changing to the button HAL.

Remove some dead code from srf06-cc26xx config files

---

arch/cpu/cc26xx-cc13xx/cc13xx-cc26xx-def.h

The CC26xx/CC13xx nodes have problems joining TSCH networks. The usual way to solve it is by adding busywaiting, which is ugly.
Someone on Gitter suggested that increasing the polling frequency also works - thanks!

CC26xx/CC13xx: update the TSCH_CONF_ASSOCIATION_POLL_FREQUENCY parameter to make it associate faster

---

examples/benchmarks/rpl-req-resp/Makefile

examples/benchmarks/rpl-req-resp 
doesn't compile for TARGET =  native  nrf52dk  simplelink
and doesn't link for TARGET =  sky
Is this an omission of PLATFORMS_EXCLUDE and BOARDS_EXCLUDE ? I removed the ones I found in examples/6tisch/{6p-packet/  etsi-plugtest-2017/  simple-node/  sixtop/}

exclude some platforms from benchmarks

---

arch/platform/srf06-cc26xx/sensortag/hdc-1000-sensor.c
arch/platform/srf06-cc26xx/sensortag/hdc-1000-sensor.h
examples/lwm2m-ipso-objects/example-ipso-objects.c
examples/platform-specific/cc26xx/cc26xx-demo.c
examples/platform-specific/cc26xx/cc26xx-web-demo/cc26xx-web-demo.c

since commit f4a8cba37, 
HDC_1000_SENSOR_TYPE_HUMIDITY is renamed  HDC_1000_SENSOR_TYPE_HUMID
this PR removes a building error in examples/lwm2m-ipso-objects
```
example-ipso-objects.c: In function 'read_hum_value':
example-ipso-objects.c:80:39: error: 'HDC_1000_SENSOR_TYPE_HUMIDITY' undeclared (first use in this function); did you mean 'HDC_1000_SENSOR_TYPE_HUMID'?
*value = 10 * hdc_1000_sensor.value(HDC_1000_SENSOR_TYPE_HUMIDITY);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HDC_1000_SENSOR_TYPE_HUMID
example-ipso-objects.c:80:39: note: each undeclared identifier is reported only once for each function it appears in
make: *** [../../Makefile.include:355: example-ipso-objects.o] Error 1
```

minor refactoring of hdc-1000-sensor following commit f4a8cba37

---

tests/compile-all/build.sh

make -C tests/compile-all was emitting lots of
../../arch/platform/simplelink/Makefile.simplelink:28: *** Board 'launchpad/cc2650sensortag/cc1350' does not corresponding to any SimpleLink family. Make sure your BOARD variable is correct..  Stop.
because of a missing trailing space

remove bug in simplelink boards name

---

examples/multicast/root.c
os/net/ipv6/uip-nd6.c
os/services/lwm2m/lwm2m-tlv.c

most of the platforms have inttypes.h via the header contiki-conf.h 
but sky and simplelink do not include it by default
this PR adds inttypes.h when needed for these latter platforms...

missing header inttypes.h

---

arch/cpu/cc2538/dev/spi-arch.c
arch/cpu/cc26xx-cc13xx/dev/spi-arch.c
arch/cpu/simplelink-cc13xx-cc26xx/dev/spi-arch.c
arch/dev/ext-flash/ext-flash.c
arch/dev/ext-flash/ext-flash.h
os/dev/spi.c
os/dev/spi.h

The `spi_device_t` passed a parameter to SPI functions is not modified by the functions. So, it should be a constant.
This patch allows to store SPI configs, such as ext-flash default config, in ROM instead of RAM.

Add const to spi_device_t * parameter in SPI functions

---

arch/dev/cc1200/cc1200.c
arch/platform/cooja/dev/watchdog.c
arch/platform/jn516x/dev/micromac-radio.c
arch/platform/jn516x/dev/uart-driver.c
arch/platform/zoul/dev/cc1200-zoul-arch.c
arch/platform/zoul/dev/dht22.c
os/net/mac/csma/csma-output.c
os/net/mac/tsch/tsch-slot-operation.c
os/net/mac/tsch/tsch.c
os/net/mac/tsch/tsch.h
os/sys/rtimer.h

This PR does a few things:
* Adds common routines for busy-waiting, in `rtimer.h`, thus de-duplicating code
* Makes the busy-wait routing fully portable, i.e. also works in Cooja motes without explicit addition of Cooja-mt-yield instructions
* Reworks CSMA busy-wait logic

Reworked busy-wait routines

---

os/dev/spi.h

#671 removed the need for arch-specific SPI select and deselect. The respective prototypes should have been removed. This PR does so.

Remove obsolete function prototypes

---

tests/compile-all/build.sh

As per the title, instead of hard-coding boards per target (error prone and liable to going stale), we now automatically detect the list of boards by running `make TARGET=$target boards` inside the hello-world example.
Also, introduced some variables to hold paths - should make it easier to move the script elsewhere if we decide to.

Detect boards automatically in the build-all script

---

os/net/mac/tsch/tsch.h

Solves one of the issues reported in https://github.com/contiki-ng/contiki-ng/issues/705

Added missing 'extern' qualifier to tsch_timing_us

---

tests/03-compile-arm-ports-02/Makefile

Compiles TSCH with all logs enabled, as this can cause issues, as reported in https://github.com/contiki-ng/contiki-ng/issues/705

Add CI compile test for TSCH with logging

---

arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx

CC13x0/CC26x0 building: also fail with descriptive error message when cc13xxware/cc26xxware exists, but is empty

---

arch/cpu/cc26xx-cc13xx/rf-core/rf-core.c

The polling mode on CC26xx is not behaving as it should. The code that puts the radio in poll mode disables CPE0 on `RX_FRAME_IRQ`. However, we still get loads of CPE0 interrupts on  `IRQ_LAST_FG_COMMAND_DONE` and `IRQ_LAST_COMMAND_DONE` (apparently they are enabled by default).
Now, the ISR looks at the flag status, sees that the `RX_FRAME_IRQ` flag is set, calls     `process_poll(&rf_core_process);` which feeds the packet to the MAC protocol. This is not what we want. At best, it's just more energy consumed, at worst, it could break TSCH which expects to receive packets by itself instead of receiving them directly from the radio driver.
The need for the CPE0 interrupt in the polling mode at all is not clear to me. So I disabled it, tested this change for a while, and it does not seem to …

CC26xx RF: in polling mode, disable the CPE0 radio interrupt completely

---

examples/libs/timers/all-timers.c

The all timers example is trying to schedule an rtimer using `CLOCK_SECOND` as part of the trigger time calculation. This results in scheduling the rtimer to trigger at the wrong time in the future.
Reported and fixed by @miromico

Fixed all-timers example application

---

os/net/app-layer/coap/coap-conf.h
os/net/app-layer/coap/coap-observe.c

This is just a simple change, but it allows the user to disable a CoAP behavior that is a bit of my personal pet annoyance.
Now, I'm aware that the RFC 7641 uses MUST here. Let me cite it:
>    A server that transmits notifications mostly in non-confirmable
>    messages MUST send a notification in a confirmable message instead of
>    a non-confirmable message at least every 24 hours.  This prevents a
>    client that went away or is no longer interested from remaining in
>    the list of observers indefinitely.
> 
There are two problems with this:
1. The server may use some other mechanism to infer that there is a client willing to get data from it. In many IoT applications "being part of the RPL network is a sufficient condition for this. If not, there are tons of options for …

CoAP: allow observations that do not timeout

---

examples/mqtt-client/mqtt-client.c
examples/mqtt-client/project-conf.h
tests/08-native-runs/02-mqtt-client.sh

This adds a travis test for the MQTT client.
1. We start a mosquitto (MQTT) server
2. We then start an MQTT subscriber process
3. We start the MQTT client example, which will subscribe to a topic and periodically publish to a different topic.
4. We send a one-off publish to the topic the MQTT client is subscribed for.
Success criteria:
* MQTT client receives the publish message from 4
* The Mosquitto subscriber receives one or more publish messages from 3
Closes #715

Add MQTT client execution test

---

tools/docker/Dockerfile

This pull reduces the docker image build verbosity. We silence git, wget, npm, pip and unzip.
We try and miserably fail to silence apt-get, because apparently dpkg ignores apt-get's verbosity control. That's on their side not ours, but I still think we should run apt-get with -qq.
Nevertheless, this appears enough to keep our output log below the travis log limit.
#719 unresolved, but this can be considered anyway.

Reduce docker image build verbosity

---

arch/platform/nrf52dk/contiki-conf.h
os/contiki-main.c
os/net/ipv6/sicslowpan.c
os/net/mac/csma/csma-output.c
os/net/mac/tsch/tsch.c
os/net/queuebuf.h

Presently, `queubuf_init` is usually called twice at start up, once by the MAC layer and once by `sicslowpan.c`. This gets problematic if the MAC layer immediately begins to use the queuebuf since the second invocation of `queubuf_init` deletes all queued frames. The solution proposed in this PR is to move the initialization of the queuebuf to `contikimac-main.c`.

Fix to queuebuf initialization

---

os/services/rpl-border-router/native/slip-dev.c
os/services/rpl-border-router/native/tun-bridge.c

This PR clarifies error messages of the native BR, to more easily distinguish errors related to opening the serial device or the tun file.

Native border router: clearer error messages

---

arch/cpu/simplelink-cc13xx-cc26xx/cc13x0-cc26x0/cc13x0-cc26x0.lds
arch/cpu/simplelink-cc13xx-cc26xx/cc13x2-cc26x2/cc13x2-cc26x2.lds

Add (NOLOAD) to linker sections for DMA transfer records.  This prevents the sections from getting added to the flash area as well (but at the RAM address).

fixes contiki-ng/contiki-ng#756 simplelink target .bin files too big.

---

arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
arch/cpu/nrf52832/Makefile.nrf52832
arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx

Make it possible to overwrite `LDSCRIPT` from other Makefiles
Previously only possible to override linker script using from environment. This allows user to set linker script in their project makefile.

Allow configurable linker script

---

examples/lwm2m-ipso-objects/example-ipso-objects.c
os/services/lwm2m/lwm2m-rd-client.c
os/services/lwm2m/lwm2m-rd-client.h
os/services/lwm2m/lwm2m-server.c

Hi! 
This PR provides support for multiple server sessions in LwM2M, which means that the RD client is able to register and maintain the registration with several LwM2M servers at the same time. 
For this purpose, the struct `lwm2m_session_info` has been extended to contain all the necessary variables to manage each server in an independent way. Also all the functions from the API now take a `lwm2m_session_info_t` pointer as a parameter.  Finally, the state machine is ticked periodically as before using only one timer, but it iterates over all the `lwm2m_session_info` that are added to check the state and perform the corresponding actions.
By default, the `lwm2m-example-ipso-objects` will only try to connect to the default local server. But if the size of the mem block where the …

Add support for multiple server session in LwM2M

---

examples/benchmarks/rpl-req-resp/node.c
os/net/mac/tsch/tsch-adaptive-timesync.c

Required in these two files, as they use `PRI` macros (`printf` format for fixed-width integers)

Add missing inclusions of <inttypes.h>

---

Makefile.include
arch/cpu/arm/cortex-m/Makefile.cortex-m
arch/cpu/arm/cortex-m/cm3/Makefile.cm3
arch/cpu/arm/cortex-m/cm4/Makefile.cm4
arch/cpu/cc2538/Makefile.cc2538
arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
arch/cpu/msp430/Makefile.msp430
arch/cpu/nrf52832/Makefile.nrf52832
arch/cpu/simplelink-cc13xx-cc26xx/cc13x0-cc26x0/Makefile.cc13x0-cc26x0
arch/cpu/simplelink-cc13xx-cc26xx/cc13x2-cc26x2/Makefile.cc13x2-cc26x2
arch/platform/cc2538dk/Makefile.cc2538dk
arch/platform/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
arch/platform/cooja/Makefile.cooja
arch/platform/native/Makefile.native
arch/platform/nrf52dk/Makefile.nrf52dk
arch/platform/openmote-cc2538/Makefile.openmote-cc2538
arch/platform/simplelink/cc13xx-cc26xx/Makefile.cc13xx-cc26xx
arch/platform/sky/Makefile.common
arch/platform/sky/Makefile.sky
arch/platform/zoul/Makefile.zoul

This is a proposal to enable compiling with arbitrary arch paths, which is useful for platforms, dev, or cpu outside of the Contiki-NG tree. The PR introduces a variable `ARCH_PATH`, which by default points to `$(CONTIKI)/arch` but can be specified by the user so as to point to any location.
For instance:
```bash
make TARGET=<my-custom-target> ARCH_PATH=<path-to-my-custom-arch>
```

Build system: enable compiling with arch directory at arbitrary paths

---

arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1310/CC1310_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1312r1/CC1312R1_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1350-4/CC1350_LAUNCHXL_433.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1350/CC1350_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1352p-2/CC1352P_2_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1352p-4/CC1352P_4_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1352p1/CC1352P1_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1352r1/CC1352R1_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc2650/CC2650_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc26x2r1/CC26X2R1_LAUNCHXL.c

All LaunchPads drives the UART0_RX pin up, but is configured in the Board file to be pull-down. This PR aligns the UART RX pin configuration with the development board HW.

Fixed wrong PIN configuration for UART0_RX on LaunchPads

---

arch/platform/simplelink/cc13xx-cc26xx/platform.c

When logging info about channel and PANID a newline is added for each
logging statement. It should only add a newline for the first LOG_INFO.

Fix correct LOG_INFO in platform.c

---

arch/cpu/nrf52832/Makefile.nrf52832

#698 introduced some bugs to the nrf52dk build system. This pull fixes them.
* The `%.jlink` assumes a fixed location for the output hex file. This location is no longer valid, so we fix this.
* The new location of the hex file contains slashes in the path, so we change the sed delimiter to something other than the `/` character
* We include `Makefile.cm4` earlier. This allows us to use some Make variables defined therein.
* We improve rule dependencies: `%.jlink` and `%.flash`
Fixes #782

Fix the nrf52dk .jlink and .flash make targets

---

arch/platform/cooja/Makefile.cooja
arch/platform/cooja/int-master.c

It's copied from arch/cpu/native/int-master.c, which is just a no-op stub.
See #790

cooja: add int-master implementation.

---

examples/libs/ipv6-uipbuf/udp-client.c
examples/rpl-udp/udp-client.c

This PR removes some duplicate declaration and unused `#define`s.

UDP example code cleanup

---

Makefile.include

Aims to avoid the reported inconsistency (#696)
As as side note, output of `Skipping $@: not for the '$(TARGET)/$(BOARD)' platform!` looks strange for platforms with no boards, especially if the BOARD is e.g set from a shell. But I don't have a good idea how to improve it.

Do not allow to 'trick' the platform and board exclude checks

---

examples/6tisch/timesync-demo/Makefile
examples/6tisch/timesync-demo/README.md
examples/6tisch/timesync-demo/node.c
examples/6tisch/timesync-demo/project-conf.h
os/net/mac/tsch/tsch-slot-operation.c
os/net/mac/tsch/tsch-slot-operation.h
os/net/mac/tsch/tsch.h
os/services/shell/shell-commands.c

This PR introduces a new function `tsch_get_network_uptime_ticks()` and an application example and shell update that shows how to use it. See the discussion in #214 for some alternative ideas. This patch does not aim to synchronize the TSCH time with the wall-clock time, just to allow applications to use the already existing (network-local) TSCH notion of time. See the README.md file in `examples/6tisch/timesync-demo/` for more details.

Application level time synchronization example with TSCH

---

arch/platform/simplelink/cc13xx-cc26xx/sensortag/opt-3001-sensor.c
examples/platform-specific/cc26x0-cc13x0/Makefile

Fixes the opt3001 sensor in the simplelink sensortag package to return the correct value. #768  
Also makes the platform-specific/cc26x0-cc13x0 example build.

Fix a couple of simplelink platform bugs

---

os/net/netstack.h

Fixes https://github.com/contiki-ng/contiki-ng/issues/786
(the wiki page was also fixed accordingly)

Fix typos in comments

---

examples/mqtt-client/mqtt-client.c
os/net/app-layer/mqtt/mqtt.c

Fix mqtt string lengths greater than 255 and incorrect example keep-alive.
Minor issues that don't impact the function of the IBM quickstart client example.
Keep-alive in the example was provided to the library in units of timer ticks, which should be in seconds.
Also, the string length shift for the MSB field was wrong way in some instances.

Fix a few minor MQTT issues

---

arch/cpu/cc2538/dev/cc2538-rf.c
arch/cpu/cc26x0-cc13x0/rf-core/cc13xx-50kbps-tsch.c
arch/dev/cc1200/cc1200-802154g-863-870-fsk-50kbps.c
arch/dev/cc1200/cc1200-868-4gfsk-1000kbps.c
arch/dev/cc1200/cc1200.c
arch/dev/cc2420/cc2420-tsch-15ms.c
arch/platform/zoul/platform.c
os/dev/radio.h
os/net/mac/tsch/tsch-timeslot-timing.c
os/net/mac/tsch/tsch-types.h
os/net/mac/tsch/tsch.h

This adds missing documentation to TSCH-related radio API constants, and adds explicit types for timing in both micro-seconds and ticks.
Fixes https://github.com/contiki-ng/contiki-ng/issues/777
I looked into switching from array to struct elements as discussed in the issue above but eventually decided against, and added a typedef for arrays in both usec and ticks instead. The structs with 13 identical (uint16_t or clock_time_t) elements just didn't feel like much of any improvement vs typedefing the arrays, and would have required pointer arithmetic instead of the current indexed array accesses.

Document and clean up TSCH timeslot timing elements

---

arch/platform/cooja/rtimer-arch.h
os/sys/rtimer.h

This removes the watchdog refresh from the rtimer busy-wait macros. Partially addresses https://github.com/contiki-ng/contiki-ng/issues/835
I think removing the refresh should not break anything here. Before these macros, the only busy-wait done with watchdog refresh was in `cc1200.c` and this was meant to handle busy waiting during `transmit` at very low data rates. No data rate low enough to result in 1s airtime is supported in NG though, so this shouldn't be an issue.

Do not refresh watchdog in rtimer busy-wait macros

---

os/net/routing/rpl-classic/rpl-dag.c
os/net/routing/rpl-classic/rpl-timers.c

Running RPL with full logging enabled currently may cause problems, as NULL values are not always checked before using them for the logs.

RPL classic logging: be more careful to avoid dereferencing NULL pointers

---

arch/cpu/arm/Makefile.arm

Reference issue #774.
This fix takes care of compiling both .s and .S for me.
Using `gcc` rather than `as` in `arch/cpu/arm/Makefile.arm`  to compile asm files offers all of the available preprocessor goodies, so that's what I've chosen to implement.

Fixes contiki-ng/contiki-ng#774 Won't compile asm files

---

arch/platform/native/platform.c

native uart relied on input function from serial-line.c. This required input data to
be newline terminated in addition to ignoring carriage return.
This allows user to specify their function for handling serialport/stdin data.

native: Use selectable uart handler for native

---

os/net/mac/tsch/tsch.c

The former is not safe in interrupt context. It may be fixed later in `process.c` fix by @debug-ito , but there is just no need for `process_post()` in that specific place.

Replace process_post with process_poll in tsch.c

---

os/lib/trickle-timer.c

Fix for issue #887.
This modifies the trickle timer library to guard some functions to prevent undesirable behaviour with the library. It also adds a couple of lines to timer configurations to ensure a consistent state of a timer is maintained throughout it's lifetime.
There are four main changes:
- Guard the `trickle_timer_consistency()` function so it returns and does nothing if a timer is stopped
- Guard the `trickle_timer_inconsistency()` function so it returns and does nothing if a timer is stopped
- Explicitly set `tt->i_cur` to `TRICKLE_TIMER_IS_STOPPED` in `trickle_timer_config()` to ensure that a timer created by that function is in the 'stopped' state before it's started.
- Explicitly set `tt->cb` to `NULL` in `trickle_timer_config()` so an undefined function can never be used …

Implemented bug fix to trickle timer

---

os/net/routing/rpl-lite/rpl-neighbor.c
os/net/routing/rpl-lite/rpl.c

RPL-Lite fails to compile when `RPL_CONF_WITH_PROBING` is defined as 0.
```
$ git diff -- os/net/routing/rpl-lite/rpl-conf.h
diff --git a/os/net/routing/rpl-lite/rpl-conf.h b/os/net/routing/rpl-lite/rpl-conf.h
index 5d674fa96..5d37205b3 100644
--- a/os/net/routing/rpl-lite/rpl-conf.h
+++ b/os/net/routing/rpl-lite/rpl-conf.h
@@ -155,7 +155,7 @@
#ifdef RPL_CONF_WITH_PROBING
#define RPL_WITH_PROBING RPL_CONF_WITH_PROBING
#else
-#define RPL_WITH_PROBING 1
+#define RPL_WITH_PROBING 0
#endif
/*
```
```
CC        ../../os/net/routing/rpl-lite/rpl-neighbor.c
../../os/net/routing/rpl-lite/rpl-neighbor.c: In function 'remove_neighbor':
../../os/net/routing/rpl-lite/rpl-neighbor.c:199:30: error: 'rpl_dag_t {aka struct rpl_dag}' has no member named 'urgent_probing_target'
if(nbr == …
```

Fix RPL Lite compilation when probing is disabled

---

tests/07-simulation-base/15-cooja-multicast-11-hops-rollt-tm.csc
tests/07-simulation-base/16-cooja-multicast-11-hops-smrf.csc
tests/07-simulation-base/17-cooja-multicast-11-hops-esmrf.csc
tests/07-simulation-base/18-cooja-multicast-31-hops.csc

This fixes issue #897. It adds commands to the cooja mote types in the simulation file to ensure the tests are run on a clean build of contiki-ng, rather than using old build files from previous tests which can cause the wrong multicast driver to be tested.

Multicast Tests Fix

---

tests/08-native-runs/02-mqtt-client.sh
tests/14-rpl-lite/02-rpl-root-reboot-2.csc
tests/15-rpl-classic/02-rpl-root-reboot-2.csc
tests/17-tun-rpl-br/test-native-border-router.sh

This fixes a further issue raised in #897 whereby tests run on a local machine by entering the `tests` directory and running `make` would cause test fails due to unclean build directories. After these changes, local testing works as expected with the exception of out of tree tests, which fail of the out of tree directory is not properly configured.

Fixed issues Running Tests Locally

---

tests/13-ieee802154/code-6tisch/common.c

This PR replaces `NULL` methods of `test_mac_driver` with dummy ones. This change prevents a test failure observed in https://github.com/contiki-ng/contiki-ng/pull/858#issuecomment-467176105.
I had the same test failure on my machine. Here is the output:
```
$ contiker '(ulimit -c unlimited; make -C tests/13-ieee802154)'
make: Entering directory '/home/user/contiki-ng/tests/13-ieee802154'
Running test 01-panid-handling with random Seed 1............ OK
Running test 02-tsch-flush-nbr-queue with random Seed 1............. OK
Running test 03-cooja-test-sixtop with random Seed 1................... OK
Running test 04-cooja-test-sixp-pkt with random Seed 1......................./../tests/simexec.sh: line 67:  1499 Aborted                 (core dumped) java -Xshare:on -jar …
```

sixtop: add missing methods of test_mac_driver (tests/13-ieee802154)

---

Makefile.gcc
Makefile.include

This hopefully will make Contiki-NG more user friendly. The idea is to nudge users to upgrade / downgrade their toolchains when their currently installed version is one of those that don't work well with Contiki-NG.

build system: warn if using compiler versions known to be problematic

---

arch/cpu/simplelink-cc13xx-cc26xx/rf/ieee-mode.c

`RF_runImmediateCmd()` expects a pointer to the immediate command, but a reference to the pointer of the CCA request command is provided.

Fixed erroneous pointer cast in IEEE CCA request function

---

os/dev/watchdog.h
os/lib/circular-list.h
os/lib/dbl-circ-list.h
os/lib/dbl-list.h
os/lib/list.h
os/lib/queue.h
os/lib/stack.h
os/lib/trickle-timer.h
os/sys/ctimer.h
os/sys/etimer.h

This pull explicitly documents in the API docs some functions/libraries that are unsafe to use inside an interrupt context.
These changes to API documentation complement [this new wiki page](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Multitasking-and-scheduling)
Resolves #841

Explicitly document libraries that are unsafe to use within interrupts

---

arch/platform/cooja/contiki-conf.h
os/lib/assert.c
os/lib/assert.h
os/sys/cc-gcc.h
os/sys/cc.h

As reported in #959, our `os/lib/assert.h` will always get included instead of an `assert.h` that may be shipping with the toolchain. In some cases this is very undesirable and breaks builds, while I cannot immediately think of any use-cases where we may actually want to be doing this.
Currently, `assert.h` is provided by all relevant toolchains except our recommended msp430-gcc v4.7.0.
This pull recommends moving our own `assert.[ch]` to their own `os/lib/assert/` directory. This allows us to explicitly select them by adding them as a `MODULE` if required. In doing so:
* We can enable the respective functionality where the system does not provide it. We do so for all msp430 builds
* We can overwrite the system-provided header if there is reason to do so
@yatch I see you are using …

Provide non-returning assert() implementation

---

arch/cpu/cc2538/usb/usb-arch.c
arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
arch/cpu/nrf52832/ble/ble-mac.c

This pull removes calls to `watchdog_periodic()` from parts of the code that may get called inside an interrupt context.
There are two more calls that I identified as suspicious:
* `tsch-slot-operation::tsch_get_lock()`
https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/mac/tsch/tsch-slot-operation.c#L207
I am not so sure about this one, but I think this also happens inside an interrupt so I've removed it. Happy to put it back if it's safe.
* `sicslowpan.c::send_packet()`
https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/ipv6/sicslowpan.c#L1472
I think that one should be OK and I've left it there.
Fixes #835

Remove watchdog_periodic() calls that may happen inside an interrupt context

---

os/net/mac/tsch/tsch-slot-operation.c

TSCH: fix the reselection of the current_link in case it becomes NULL during a packet burst

---

os/net/ipv6/uip-icmp6.c

The old code seems to have assumed that the type of UIP_ICMP_BUF was
char* (or equivalent) while in fact it was struct uip_icmp_hdr*.
Thus when computing the address to UIP_ICMP_BUF[sizeof(struct
uip_icmp_hdr)], where sizeof(struct uip_icmp_hdr) = 4, it would
increment the pointer by 4*4 = 16 bytes, and not 4 bytes as would be
expected.

uip-icmp6: in echo_reply_input, pass the correct icmp payload pointer

---

os/sys/lc-addrlabels.h

According to GCC documentation, jumping into a statement expression with
a computed goto (using labels as values) has undefined behavior and
should be avoided.  However, this is exactly what is happening in the
current `LC_SET` implementation.
Fortunately, the statement expression which contains the label in `LC_SET`
can safely be removed since the operand is only evaluated once, and
multi-statement operations of the macro are already handled by a
`do-while(0)` construct.
For more information, see issue #986

lc-addrlabels: remove statement expression (fixes #986)

---

os/net/mac/tsch/tsch.c

Although `TSCH_LINK_NEIGHBOR_CALLBACK` is conditionally defined in `tsch.c`, this macro is not referred from anywhere.
```
$ pwd
/Users/yatch/Work/contiki-ng
$ find . -name \*.\[ch\] | xargs grep TSCH_LINK_NEIGHBOR_CALLBACK
./os/net/mac/tsch/tsch.c:#ifndef TSCH_LINK_NEIGHBOR_CALLBACK
./os/net/mac/tsch/tsch.c:#define TSCH_LINK_NEIGHBOR_CALLBACK(dest, status, num) uip_ds6_link_neighbor_callback(status, num)
./os/net/mac/tsch/tsch.c:#endif /* TSCH_LINK_NEIGHBOR_CALLBACK */
```
It seems this is a leftover from the refactoring work by https://github.com/contiki-ng/contiki-ng/pull/47.

TSCH: remove an unused macro in tsch.c

---

arch/cpu/simplelink-cc13xx-cc26xx/rf-settings/cc13x0/prop-settings.c

A bug was introduced in the CC1310 prop RF settings when fixing a bug
with BLE beaconing. In short, prop RF settings are shared between CC1310
and CC1350, and rfMode was set to RF_MODE_MULTIPLE which is only
supported on CC1350. This is now split between CC1310 and CC1350.

Fixed bug in CC1310 prop RF settings

---

.travis.yml
tests/06-script-base/01-test-lc-switch.sh
tests/06-script-base/02-test-lc-addrlabels.sh
tests/06-script-base/Makefile
tests/06-script-base/code-test-lc/Makefile
tests/06-script-base/code-test-lc/test.c
tests/06-script-base/run-test-lc.sh

This PR introduces simple tests for two LC implementations: `lc-switch` and `lc-addrlabels`.
Related Issue/PR:
- #986 
- #990

lc: add test for LC_ APIs (local continuations)

---

arch/platform/zoul/contiki-conf.h
tests/03-compile-arm-ports-02/Makefile

This pull:
* Makes it easy to switch between zoul radios (cc2538/cc1200) through the `ZOUL_CONF_USE_CC1200_RADIO` macro. When defined as non-zero, the configuration system selects sane default values for sub-ghz operation with the cc1200. Users can leave this macro defined as zero and configure sub-ghz operation manually
* Adds a new compile test for platform zoul / sub-ghz configuration
* Fixes the zoul sub-ghz sensniff compile test
Requires #974

Switch between zoul radios with a single define

---

os/net/ipv6/sicslowpan.c
os/net/ipv6/sicslowpan.h

Without this fix, setting SICSLOWPAN_CONF_COMPRESSION = SICSLOWPAN_COMPRESSION_IPV6 in a project-conf file leads to compilation failures because uncompress_hdr_iphc() is not defined.

make compilation with SICSLOWPAN_COMPRESSION_IPV6 possible

---

os/lib/memb.c
os/lib/memb.h

During formal verification of memb* functions it was discovered that
reference counting in the functions could be significantly simplified.
Here is the citation from the work:
"This verification case study also allowed to detect a potentially
harmful situation. The memb_free function used to decrement the count
associated to the given block, instead of setting it to 0. An awkward
consequence of this is that calling memb_free on a block with an unusual
count (e.g., greater than 2) would not actually free it. While this
should not happen under normal circumstances, we have decided to replace
that decrement operation by a set to 0. This choice makes memb_free both
simpler and more robust, easing the verification process..."
"Formal Verification of a Memory Allocation Module of Contiki with …

lib: memb: simplify handling of allocation status

---

examples/coap/coap-example-client/coap-example-client.c
examples/lwm2m-ipso-objects/example-server.c
os/net/app-layer/coap/coap-blocking-api.c

Currently there is no convenient way for the caller of COAP_BLOCKING_REQUEST
to tell if the request timed out.
This change calls the request_callback with a NULL pointer as the argument
on timeout. Thus the caller will be able to handle a timeout by checking
for NULL in the callback function.

coap-blocking-api: Signal timeout to the callback function

---

os/lib/memb.h
tests/06-script-base/03-test-memb.sh
tests/06-script-base/code-test-memb/Makefile
tests/06-script-base/code-test-memb/contiki.h
tests/06-script-base/code-test-memb/test-memb-api.c

This PR introduces simple tests for `memb` APIs. In addition, docstring in `memb.h` is updated.

Add tests for memb APIs

---

os/services/rpl-border-router/embedded/Makefile.embedded

When running `make connect-router` tunslip6 was unable to create a tunnel as the cc1350/launchpads or cc2650/launchpads, possibly several others, enmuerates as `ttyACM0`. For a tunnel to be created tunslip6 has to be ran manually as `tunslip6 -s /dev/ttyACM0 fd00::1`. PORT already can be specified as a variable when flashing the device `make PORT=/dev/ttyACM0 project.upload` or by adding it to the project's `Makefile`. This change makes it so that by specifying a PORT variable, it will be added to the tunslip6 options. This will let you specify whichever tty device you'd like when using `connect-router`, such as `make PORT=/dev/ttyACM0 connect-router`.
If PORT isn't specified it behaves as earlier.
I also found a typo in viewconf.c which makes it so the value of …

make connect-router for rpl-border-router can now use PORT variable

---

os/net/app-layer/coap/coap-conf.h
os/net/app-layer/coap/coap-observe.h

This is just a very minor thing, but it has annoyed me several times already.

allow to configure maximal URI length for CoAP observables

---

examples/platform-specific/cc26x0-cc13x0/very-sleepy-demo/project-conf.h
os/net/ipv6/uip-ds6.h

Reduces frequency of the timer to save energy.
We don't really need the data structure maintenance 10 times per second, at least not by default.

reduce the IPv6 data structure (DS) maintenance timer frequency

---

tools/serial-io/tunslip6.c

Unless we specify `-v[level]`, tunslip6 will default to `-v1`. This causes undesirable behaviour: The following embedded BR output lines will not get printed to console immediately (but they will if e.g. the BR resets):
```
[INFO: BR        ] Waiting for prefix
[INFO: BR        ] Server IPv6 addresses:
[INFO: BR        ]   fd00::212:4b00:7b5:a183
[INFO: BR        ]   fe80::212:4b00:7b5:a183
```
These lines will in fact get printed if we run `tunslip6` with `-v2`.
Now in the BR-related wiki page we describe that the `connect-router` make target will result in these lines getting printed, but it does not since it invokes `tunslip6` without specifying the verbosity level (so the call results in the default `-v1`). This causes user confusion.
These lines are IMHO very useful to see anyway, so …

Change default tunslip6 verbosity

---

arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx

This commit allows users of platform simplelink to program their devices using the .upload make target. This will only work for those simplelink boards that can actually be programmed using the cc2538-bsl script. As of the time of writing this commit, this can only be done with the old `x0` devices (cc13x0 and cc26x0), but not the newer `x2` devices. Changes to the BSL script itself likely required before these platforms can be supported.
Closes #1036

Add support for the .upload make target for platform simplelink

---

examples/multicast/multicast.csc

The csc file provided with the multicast example simulates a network of sky motes. This is broken, since the multicast example no longer supports sky. This commit creates a new example simulation that uses Cooja motes.
The diff is pretty ugly :D
Fixes #992

Replace the multicast example simulation file

---

arch/cpu/simplelink-cc13xx-cc26xx/dev/clock-arch.c
arch/cpu/simplelink-cc13xx-cc26xx/dev/clock-arch.h
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1310/CC1310_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1312r1/CC1312R1_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1350-4/CC1350_LAUNCHXL_433.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1350/CC1350_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1352p-2/CC1352P_2_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1352p-4/CC1352P_4_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1352p1/CC1352P1_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1352r1/CC1352R1_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc2650/CC2650_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc26x2r1/CC26X2R1_LAUNCHXL.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc1350/CC1350STK.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc2650/CC2650STK.c
arch/platform/simplelink/cc13xx-cc26xx/srf06/cc13x0/CC1350DK_7XD.c
arch/platform/simplelink/cc13xx-cc26xx/srf06/cc26x0/CC2650DK_7ID.c

It was discovered that the SysTick interrupt must be disabled before
dropping to some low-power mode. If not, then in some rare occasions a
race condition of the device entering/leaving the low-power mode and the
SysTick interrupt triggering may clobber the CPU context and put it in an
invalid state, and will in most cases crash the CPU.
A "proxy" standby policy is implemented which wraps the actual Power
driver standby policy with disabling and enabling the SysTick interrupt,
before and after. This ensure the SysTick is always disabled when
entering some low-power mode, regardless of which context that triggers
the standby policy.

[bugfix] Disable SysTick interrupt when dropping to some low-power mode

---

os/net/ipv6/tcp-socket.c

This commit fixes #1061.
`memcpy()` should not be used if the source and destination memory locations alias.
In `acked()` the expectation is clearly that the two buffers overlap.
In `tcp_socket_send()` it's a bit trickier. This issue was discovered because the MQTT library was using a single memory location for 2 things: the buffer that it uses to construct its output packet and the buffer that it passes to the TCP socket for the output data. The TCP API does not require that the 2 buffers that are passed to `tcp_socket_send()` are non-overlapping and I think this change is preferable to adding that constraint and fixing all potential occurrences of this issue, as:
- this allows for some memory to be saved
- while `memcpy()` is supposed to be faster than `memmove()`, I don't believe this …

Replace memcpy in tcp-socket

---

os/net/mac/tsch/tsch.c
os/net/routing/nullrouting/nullrouting.c
os/net/routing/routing.h
os/net/routing/rpl-classic/rpl.c
os/net/routing/rpl-classic/rpl.h
os/net/routing/rpl-lite/rpl.c

Should the network allowing to join new nodes through leaf nodes? I don't think so. There are a few potential problems created by the current approach.
- additional EB collisions especially in dense networks with many leafs or mobile leafs
- the leafs send EBs by default and therefore are less energy efficient
This PR disables joining through leaf nodes.

TSCH: do not send EB packets when in leaf mode

---

os/net/mac/tsch/tsch-adaptive-timesync.c
os/net/mac/tsch/tsch-adaptive-timesync.h
os/net/mac/tsch/tsch-queue.c
os/net/mac/tsch/tsch-slot-operation.c
os/net/mac/tsch/tsch.c

* Add `tsch_adaptive_timesync_reset()` function
* Rename `is_broadcast` to `do_wait_for_ack` to better reflect how it is used in code (and there can be non-ACK'able unicast messages, after all)
* Return `NULL` instead of `0` from `tsch_queue_add_packet`
* Allow to compile the code when `TSCH_EB_PERIOD` is set to 0

minor improvements and cleanups in TSCH

---

os/net/ipv6/sicslowpan.c

This PR fixes a number of problems with packet processing in the sicslowpan implementation. PR #900 should pass with the help of these changes.
For future work, it could be good to redesign the sicslowpan module, as it has become a bit convoluted.
Thanks to Tobias Scharnowski for reporting the issues with the add_fragment and store_fragment functions, and the possible use of previous packet data when reassembling a packet.

sicslowpan vulnerability fixes

---

.travis.yml

This introduces the workaround for Issue #1084. This workaround should have the minimal impact to our test environment on Travis-CI.

travis: specify Trusty explicitly to avoid Xenial

---

.travis.yml
tools/docker/Dockerfile

We currently try to change `net.ipv6.conf.all.disable_ipv6` to `0` by `.profile`, but it doesn't work.
```
$ docker run -ti contiker/contiki-ng
sysctl: setting key "net.ipv6.conf.all.disable_ipv6": Read-only file system
user@57f569a70c56:~/contiki-ng$
```
Here is another example:
```
$ docker run -ti contiker/contiki-ng sysctl net.ipv6.conf.all.disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
```
As per [the official documentation of Docker](https://docs.docker.com/engine/reference/commandline/run/), `--sysctl` should be passed to `docker run` for this purpose:
> The --sysctl sets namespaced kernel parameters (sysctls) in the container. For example, to turn on IP forwarding in the containers network namespace, run this command:
This PR proposes to remove the `sysctl` command from …

docker: fix an issue on net.ipv6.conf.all.disable_ipv6

---

os/net/mac/tsch/tsch-queue.c
os/net/mac/tsch/tsch-schedule.c
os/net/mac/tsch/tsch-slot-operation.c
os/net/mac/tsch/tsch-slot-operation.h
os/net/packetbuf.h
os/services/orchestra/orchestra-conf.h
os/services/orchestra/orchestra-rule-default-common.c
os/services/orchestra/orchestra-rule-eb-per-time-source.c
os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-ns.c
os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-storing.c
os/services/orchestra/orchestra.c
os/services/orchestra/orchestra.h

This increases the performance of Orchestra by reducing the number of collisions, especially helpful in dense networks.

add multiple channel option to Orchestra unicast slotframe

---

os/net/routing/rpl-classic/rpl-conf.h
os/net/routing/rpl-classic/rpl-dag.c
os/net/routing/rpl-lite/rpl-conf.h

RPL CLassic: only allow DAGs with a parent in rpl_has_joined

---

.travis.yml

This pull allows us to create and use a separate docker container image each time `tools/docker` gets changed. This means that `tools/docker` changes in one branch will not influence travis tests running against a different branch (potentially causing them to fail, as was the case for #1084 & #1085). Each branch will from now on simply pull and use (or build) the correct docker image.
Each image is tagged with the hash of the most recent commit that changed `tools/docker`. Let's call this `CONTIKER_TAG`. This is retrieved by running:
```
$ git log -1 --oneline -- tools/docker/ | cut -d" " -f1
5310e7ae5
```
Travis tests will attempt to pull `contiker/contiki-ng:$CONTIKER_TAG`.
Then:
* If the pull succeeds then the PR / branch does not change `tools/docker`
* If `tools/docker` changed then …

Add support for multiple docker containers

---

arch/cpu/native/Makefile.native

As referenced in issue #1134. Including this directory at such
a build stage means that the dir ends up being the first in the
search path, which can lead to conflicts with local files with
the same name.

Remove /usr/local/include from native Makefile

---

os/sys/ctimer.c
os/sys/ctimer.h
os/sys/etimer.c
os/sys/process.c

Some old files under `os/sys` use tabs instead of spaces here and there. This looks funny in my editor and annoys me every time I open them to take a look...
This PR fixes indentation and opportunistically applies some other code style improvements

Fix indentation and code style

---

arch/cpu/cc26x0-cc13x0/lpm.h

Working on the CC1310 I needed to change the LPM mode from the project_conf.h file. I hope this is not against the coding guidelines, I could not find any mention of configuration flags there, but since it is platform specific I am not completely sure. 
Maybe the configuration flag name should be something like `CC26XX_CC13XX_LPM_MODE_MAX_SUPPORTED_CONF` ?

cc26x0-cc13x0 CPU: make LPM_MODE_MAX_SUPPORTED a configurable flag

---

arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-def.h
os/net/mac/tsch/tsch-slot-operation.c

This addresses issue #1145 .
CC1310 uses slot length of 40000 usec instead of 10000 usec.
The base drift rate is different from 2.4 Ghz.
When the first EB is received, the next time to wake up calculation needs to include the base drift compensation.

Correct base drift for CC13XX SubGhz, Compensate base drift at association

---

os/net/link-stats.c

This should greatly improve network rebuilding time when the root node is rebooted or replaced.
Fixes #938

avoid adding link stats back to neighbors that are dead

---

os/net/ipv6/uip-ds6-route.c

Fix Issue #1177. More precisely, this fix is for https://github.com/contiki-ng/contiki-ng/issues/1177#issuecomment-576017558.
You can reproduce the issue using `examples/rpl-udp` with the following changes:
* add `MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC` to `Makefile`
* create `project-conf.h` having `#define LOG_CONF_WITH_ANNOTATE 1`

uip-ds6-route: add a missing 'const' qualifier

---

os/net/routing/rpl-lite/rpl-dag.c

Currently, in some cases the log message "found parent ... staying in DAG" may be printed and the `rpl_timers_unschedule_leaving()` function called when the node is in fact leaving the DAG. This happens for example when `rpl_local_repair()` is called, which removes the preferred parent before the state update.
This is not a serious problem, as the "We have no more parent" (line 344) branch is hit later anyway, but is confusing. The PR fixes this confusing logic.

fix rpl_dag_update_state() logic in case the preferred parent already has been cleared

---

os/net/mac/tsch/tsch-rpl.c

Fixes #890 and #877
Potentially fixes #608

keep TSCH timesource state consistent with RPL parent state

---

tools/vagrant/Vagrantfile
tools/vagrant/bootstrap.sh

This PR upgrades our vagrant image to Ubuntu 18.04
We also apply some improvements:
* We force Java to version 8
* We install various packages required in order for some tests to pass locally
The vagrant image is affected by #1069. This will be fixed separately

Upgrade and improve our vagrant image

---

arch/platform/cooja/contiki-conf.h
os/net/mac/tsch/tsch-conf.h
os/net/mac/tsch/tsch.c
os/net/mac/tsch/tsch.h
tests/17-tun-rpl-br/02-border-router-cooja-tsch.csc

Two things:
1. Do not start TSCH EB sending process when the TSCH_EB_PERIOD is set to zero. Otherwise, the timer runs every tick and wastes CPU resources.
2. Document that `tsch_set_eb_period(0)` is not sufficient to turn off EB sending if RPL is used.

TSCH EB timer and documentation fix

---

os/net/app-layer/mqtt/mqtt.c

If compiled without any optimization, this debug loop can result in an infinite loop.
Special thanks to H2020 Vessedia (https://vessedia.eu/) the vulnerability report.

MQTT: increase size of variable i to avoid potential infinite loop

---

.travis.yml
tests/Makefile.script-test
tools/docker/Dockerfile

Our testing system already builds Cooja when needed, so this pull removes the step to build it from `.travis.yml`.
Closes #1088

Don't build Cooja unless a travis test actually needs it

---

os/net/ipv6/uip-ds6.h

MPL requires more space for interface multicast addresses. This is done by setting `UIP_CONF_DS6_MADDR_NBU` in `mpl.h`. For whatever reason, this configuration macro was getting picked up when building with RPL Classic but not with Lite, resulting in the table of interface multicast addresses being smaller than what we need.
This pull fixes this.
Fixes #1147
@RCfesk

Add missing include

---

examples/mqtt-client/Makefile

There is no reason to disallow the cross-platform MQTT Client example for platform Cooja, but the platform is not listed under `PLATFORMS_ONLY`.
This pull fixes this.
Tested end-to-end inside docker, with:
* MQTT Client native cooja node
* Sky simulated BR inside Cooja
* tunslip6 outside Cooja talking to the simulated BR
* Mosquitto outside
Closes #1216

Allow the MQTT client example for platform Cooja

---

os/net/ipv6/uip6.c

This is a bug/vulnerability I discovered while working on a [paper on TCP specification conformance](https://arxiv.org/abs/2002.05400). One of the implementations we tested was uIP (standalone v1.0, so quite old), which generated segmentation faults when we ran a test regarding TCP's urgent pointer. We determined the cause within uIP (see below), but didn't submit a fix for it initially because we thought the project was inactive (judging from its [GitHub repo](https://github.com/adamdunkels/uip)).
If the UIP_URGDATA macro is zero (the default), the amount of urgent data is deducted from the uip_appdata pointer and from uip_len without any size check. This can cause out-of-bounds reads (for the former) and unsigned integer underflow (for the latter) when the urgent pointer points past the …

Fix out-of-bounds uIP data pointer on some TCP URG segments

---

os/net/app-layer/mqtt/mqtt.c

The MQTT functions mqtt_subscribe, mqtt_unsubscribe and mqtt_publish all have a parameter `uint16_t *mid` to provide the caller of these functions with the message id created for the event. However, these functions do not set this variable which is addressed by this PR.

MQTT: Provide the message id for subscribe, unsubscribe and publish

---

os/net/mac/tsch/tsch-adaptive-timesync.c

Add dummy implementation of `tsch_adaptive_timesync_get_drift_ppm` when adaptive timesync is disabled, otherwise examples that use the shell module do not link.

Fix Contiki-NG example building with TSCH adaptive timesync is disabled

---

os/net/mac/tsch/tsch-log.c
os/net/mac/tsch/tsch-log.h
os/net/mac/tsch/tsch-slot-operation.c
os/net/mac/tsch/tsch-slot-operation.h
os/net/mac/tsch/tsch.h

TSCH: fix channel_offset in the logs if taken from a packet, and refactor TSCH channel / channel_offset selection inside a slot

---

arch/cpu/simplelink-cc13xx-cc26xx/cc13xx-cc26xx-conf.h
arch/cpu/simplelink-cc13xx-cc26xx/rf/ieee-mode.c
arch/cpu/simplelink-cc13xx-cc26xx/rf/prop-mode.c
arch/cpu/simplelink-cc13xx-cc26xx/rf/sched.c

Before the TSCH driver can be developed, there are some fixes needed in the Simplelink platform. Discovered based on IEEE mode testing.

Simplelink radio fixes

---

.travis.yml

Currently travis does a shallow clone. This is likely to cause issues with the conditional docker image build logic. This commit removes the --depth argument altogether.

Do a full clone in Travis CI

---

.github/workflows/build.yml

This pull request adds support for github actinos. The intention is to run in parallel with travis CI or to replace it altogether.
This is WIP. We are partially setting up the GH actions framework, but there is still a lot left to be done:
* Need to add the ability to push containers to dockerhub - I may need some help with the secrets here
* Need to make sure we can run docker the way we want it to run
* Need to correctly communicate success/failure of the various steps to GH actions so we can get correct test outcomes.
I thought I'd throw this out here for review, ideas and thoughts.

Add support for github actions

---

arch/platform/cc26x0-cc13x0/common/xmem.c

As in title.
Disclaimer: I don't have a TI board so has not been tested on the supported platforms. But changes seems straightforward to me.

Minor xmem fixes for cc13x0/cc26x0

---

lgtm.yml

[LGTM](https://lgtm.com/) (now owned by GitHub) is a "code analysis platform for finding zero-days and preventing critical vulnerabilities". It is free for open source project and it can be configured to [run automatically on each PR](https://lgtm.com/help/lgtm/managing-automated-code-review) by installing the GitHub App to the repository. It can then leave comments indicating if a PR fixes or introduces alerts. In addition, queries can be run post-analysis using their CodeQL semantic engine.
This PR adds a simple config file necessary for LGTM to correctly build several examples for the native platform. An aggregate report will be produced. You can see an example analysis [here](https://lgtm.com/projects/g/alexandruioanp/ctk-copy/?mode=list&lang=cpp&severity=error%2Cwarning) (I had to …

Add LGTM config for native C extraction

---

arch/cpu/simplelink-cc13xx-cc26xx/rf/prop-mode.c
examples/6tisch/simple-node/project-conf.h
os/net/mac/tsch/tsch.c

Explanation of the changes:
* the `max_payload` function currently returns 0 when TSCH is not associated because the framer fails to create a frame in that case. This PR explicitly looks at whether that's the case and prints and  informative warning if so.
* `simple-node` example: the logs are very spammy, in particular the framer log, and generate a lot of text that is not relevant to the TSCH protocol itself. This PR reduced the framer and RPL log levels for that particular example, assuming its mainly meant to demonstrate TSCH.
* `simplelink-cc13xx-cc26xx/rf/prop-mode.c` - fix a typo

Improve quality of logging output in various files

---

arch/platform/simplelink/cc13xx-cc26xx/platform.c

As reported in #1292, platform simplelink does not currently toggle ENERGEST sleep/deep sleep states correctly. Unfortunately, we have no way to distinguish between LPM and DEEP_LPM without messing around with CoreSDK, which is something we should not do. But we can at least mark every entry to a low power state as entering `ENERGEST_TYPE_DEEP_LPM`.
Fixes #1292

Improve ENERGEST support for platform Simplelink

---

os/lib/dbg-io/strformat.c

The 'z' precision prefix is very useful when formatting values of type
size_t and it is part of the C99 standard.
So add support for this to the function format_str_v(). This function is
used for example when formatting log output.

Add support for 'z' precision prefix to format strings

---

os/net/mac/tsch/tsch-slot-operation.c

It may be possible that the radio driver advances directly from "no packet" to "pending packet" state between checks done by the TSCH code, skipping the "receiving packet" state.
This code change handles this corner-case corrently. Is in particular necessary for the new SimpleLink radio driver.

TSCH: improve the robustness of the packet reception check

---

os/sys/log.c
os/sys/log.h

This PR adds macros to support logging bytes at different log levels. When investigating new protocols, it is useful to be able to log the raw data received while debugging and to then disable this logging by changing the log level.

Add LOG_*_BYTES to simplify logging a string of bytes at different log levels

---

os/sys/log-conf.h
os/sys/log.h

When debugging it is useful for the log prefix to be coloured based on the log level. This helps spot error messages when printing a large number of messages at other levels.

Support color coding log prefixes based on log level

---

arch/cpu/arm/Makefile.arm

Add the OPTIMIZATIONS variable that allows the build environment to
override the default compilation optimization level on ARM. This can
be used to generate easily debuggable code, for example:
make OPTIMIZATIONS="-Og -g"
This flag can also be embedded in the Makefile of a platform or an
application to create multiple build configurations in combination with
BUILD_DIR_CONFIG

Allow overriding the default optimization levels

---

os/net/app-layer/mqtt/mqtt.h

Fixes https://github.com/contiki-ng/contiki-ng/issues/1335
MQTT payload sizes larger than 255 bytes are now handled correctly.
If the payload size is up to `MQTT_INPUT_BUFF_SIZE` bytes (default 512), it is handed to the application in one chunk:
```
tcp_input with 504 bytes of data:
MQTT - Read VHDR '30'
MQTT - Read Variable Byte Integer byte 245
MQTT - Read Variable Byte Integer byte 3
MQTT - Finished reading remaining length byte
MQTT - Read PUBLISH topic len 57
MQTT - topic_pos: 0 copy_bytes: 57
MQTT - Got topic '<TOPIC>'- Copied 442 payload bytes
MQTT - Copied bytes: 
30 2C BF D1 69 94 68 0B F3 07 CC F0 28 04 A2 00 FD 4B A9 FF 93 C0 26 80 10 60 9C A8 1B FD 28 28 0B 09 04 02 0C 00 06 1D 00 86 80 22 B8 5E 2A 00 50 01 38 48 41 51 C2 00 60 83 32 82 03 85 7E B0 06 40 25 94 46 96 10 C0 29 …
```

Fix bug with MQTT payloads > 255 bytes

---

arch/cpu/cc26x0-cc13x0/rf-core/rf-core.c

`printf` would cause linker to include unnecessary functions.

Fix `printf` vs `PRINTF` typo

---

arch/cpu/simplelink-cc13xx-cc26xx/rf/prop-mode.c

SimpleLink: fix receiving_packet() return value in the prop mode

---

examples/mqtt-client/mqtt-client.c
os/net/app-layer/mqtt/mqtt.c
tests/08-native-runs/mqtt-client.sh

In MQTT5, the PUBLISH VHDR contains property bytes as well (https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901106). Even if no properties are sent, a single 0 byte is included to encode the length of the non-existing properties. This then erroneously ends up in `payload_chunk`, which is meant to be the actual application payload. This PR ensures that `payload_chunk` points past the property-related parts of the packet.
This PR also enhances the MQTT test suite to check the integrity of the application payload.
Closes #1341.

[MQTT5] Fix application payload handling

---

os/net/ipv6/uip6.c

A TCP packet can contain a data offset that makes the statement <code>uip_len = uip_len - c - UIP_IPH_LEN</code> overflow, causing a crash later in tcp-socket.c when attempting to copy much more data than is possible.
This pull request adds a check to verify that the data offset is not too large in relation to the length of the input packet.

Verify the TCP data offset to avoid uip_len overflows.

---

arch/platform/simplelink/cc13xx-cc26xx/contiki-conf.h

Otherwise the nodes may freeze or reboot when logging is enabled. (Seems that there may be a problem with the watchdog as well, as one would expect them to always reboot instead of freezing...)

Simplelink: disable framer logging, as it can be called in interrupt context

---

arch/cpu/cc26x0-cc13x0/dev/cc26xx-uart.c

Removes the requirement for both UART TX and RX to be set, thus adding support for boards which only have one or the other. (Same PR as https://github.com/contiki-os/contiki/pull/2259)

Support uni-directional UART for cc26x0-cc13x0

---

arch/platform/native/platform.c

According to the comment about `SELECT_TIMEOUT` in `platform.c` for the
native platform it is used to configure the maximum time the scheduler
is allowed to sleep. The unit is specified to be **milliseconds**.
However, in reality the define was interpreted as number of **microseconds**
instead of milliseconds. The default value of 1000 made applications
wake up at least 1000 times per second instead of 1 when running
natively.
This fixes that bug and hopefully saves at least some CPU cycles.

Save some CPU cycles on the native platform

---

arch/platform/simplelink/cc13xx-cc26xx/platform.c

As in title.
Disclaimer: I don't have hardware to test this, but seems obvious enough (although surprising no one has noticed... 🤔 )

Make sure sensors-process runs when needed in simplelink platform

---

os/net/mac/tsch/tsch.c

The fix in eb_input was already discussed and agreed in #890 - somehow it slipped through the cracks.
The fix in the function `resynchronize` adds resetting of the `last_eb_nbr_addr`  variable. Otherwise, after trying to resync on an address it once, the variable will be equal to the time source address. If there are no other EB sending neighbor, the variable will always remain equal to the time source address, and subsequent resync calls will just try to resync on the same neighbor.

TSCH: fix filling and resetting of last_eb_nbr_addr

---

arch/platform/sky/contiki-conf.h
examples/snmp-server/project-conf.h

In this PR I enabled the Stack check on the sky port.
I believe that this was an old setting based on the comment.
If the comment is valid some unit test must fail.

Enabled stack check on sky

---

arch/cpu/simplelink-cc13xx-cc26xx/rf/prop-mode.c

The value of prop_radio.channel is zero at startup, so if the channel
was set to zero during the init code, then the frequency setup was
skipped.

Fix incorrect radio channel when channel is initially set to zero.

---

os/services/orchestra/orchestra-conf.h

The current implementation is particularly bad for the default unicast slotframe size of 17. Since `256 % 17` is 1, it means that `ORCHESTRA_LINKADDR_HASH2(a1, a2) == ORCHESTRA_LINKADDR_HASH2(a2, a1)`. This leads to slot allocation that is clearly not what the link-based rule was meant to provide, as both directions of the link now get the same timeslot.
The value of 264 is a good choice for the default size 17. It also a good choice for most other slotframe sizes: there are no prime numbers between 2 and 101 (including) that produce modulo 1 when used to divide 264.

Orchestra: upate the ORCHESTRA_LINKADDR_HASH2 function

---

arch/cpu/nrf52840/nrf52840-def.h

This PR enables TSCH hardware timestamps on nRF52840 to fix occasional TSCH desync issues, as well as the inability to use older nRF52840 preview development kits (PDK) in TSCH networks without them dropping out of sync almost immediately.
This contains the nRF52840 part of #1387, along with disabling `TSCH_CONF_TIMESYNC_REMOVE_JITTER` to align this platform with others using hardware timestamps.

TSCH: Enable hardware timestamps on nRF52840

---

os/services/lwm2m/lwm2m-rd-client.c
os/services/lwm2m/lwm2m-rd-client.h

Adds a preprocessor definition LWM2M_PROTOCOL_VERSION; set it to "1.0".  Extend query_data to include this with the key "lwm2m=".
Fixes #1389

Include LWM2M protocol version in registration message

---

os/dev/button-hal.c
os/dev/button-hal.h

This PR fixes a bug that prevents the button HAL from working properly in port/pin numbering mode when we have buttons connected to >1 ports (e.g. one button on some pin on port 0 and a different button on some pin of port 1).
Instead of using a single press/release handler for all buttons, we associate a separate handler for each port (each handler can already handle all pins within the same port). We expect the platform configuration to tell us how many different ports have buttons connected to them, and we default to 1.
Tested on Launchpad (raw pin numbering scheme) and on nRF52840 DK and Dongle (port/pin numbering scheme).
@alexstanoev 
Fixes #1317

Allow the button HAL to deal with buttons connected on different ports

---

tools/serial-io/tunslip6.c

This PR changes tunslip6's help message the way I think #1396 should have been changing it.
It also tidies up the usage message such that it too documents everything, in the same order as `-h`

Tidy up tunslip6 usage and help messages

---

os/net/mac/tsch/tsch-const.h

If the TSCH timeslot length is long and/or TSCH_DESYNC_THRESHOLD is small, the macro currently can return zero, which breaks TSCH operation.

TSCH: fix TSCH_CLOCK_TO_SLOTS macro used for deciding whether to leave the TSCH network

---

os/net/mac/tsch/tsch-conf.h

The new IEEE 802.15.4-2020 standard provided some more detail on how the frame pending bit should be used:
> When operating in TSCH mode, the frame pending bit can only be set if there is not a link scheduled in the following timeslot.
> At all other times, the frame pending bit shall be set to zero on transmission and ignored on reception.
It is not said whether this check should be done on both sides or just on the transmission side (which cannot be fully aware of the links scheduled on the receiver side).
Given that this feature may break hard cells (issue #994) and it is message and computationally complex to implement the lookahead in the schedule to be standard compatible, it is best to disable it by default.

TSCH: disable the burst bit by default

---

arch/cpu/nrf52840/ld/nrf52840.ld

The nRF52840 port is using incorrect lengths for both flash and RAM, resulting in reduced space being made available to the user application for the non-bootloader (dk) target. 
This pull request replaces them with the correct values in the linker script.
Discovered by @schuschu

nrf52840: Use correct flash and RAM length in dk linker script

---

arch/platform/nrf52840/rtt/segger-rtt-conf.h
arch/platform/nrf52840/rtt/segger-rtt.h

The nRF52840 port uses the gnu99 style of inline asm definitions in SEGGER RTT code (`asm` as opposed to `__asm__`) and thus fails to compile.
This PR fixes that and allows us to build successfully with NRF52840_USE_RTT=1 defined.

nrf52840: Fix build when using SEGGER RTT

---

tools/serial-io/tunslip6.c

This change adds a heuristic to `is_sensible_string` in tunslip6 that should catch edge-cases where a packet starts with printable characters and produces output similar to this:
```
`
Packet from SLIP of length 102 - write TUN
0000 be ef 00 40 3a 40 fd 00 00 00 00 00 00 00 f6 ce 36 9c a8 2f 3a 4d fd 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 81 00 1b 74 1d b2 00 01 d2 65 76 5f 00 00 00 00 29 db 0a 00 00 00 00 00 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 30 31 32 33 34 35 36 37
tunslip6: serial_to_tun: write: Invalid argument
ifconfig tun0 down
netstat -nr | awk '{ if ($2 == "tun0") print "route delete -net "$1; }' | sh
```
This can be triggered by running the following ping command:
```
$ ping fd00::f6ce:369c:a82f:3a4d -F 0xabeef …
```

Handle edge-case in tunslip6 causing crashes with certain flow label bytes

---

os/net/mac/tsch/tsch-schedule.c
os/net/mac/tsch/tsch-slot-operation.c
tests/07-simulation-base/26-cooja-rpl-tsch-orchestra-perfect-link.csc

There are two issues fixed by this PR:
1. in backup link selection, they are not prioritized by slotframe handle.
2. if the best link has no packets to send, the final decision to use either the best link of the backup link also does not take into account the slotframe handle. 
This lets the regression test pass with almost 100% packet ACK rate. The only loss appears to be very occasional (1 packet of 1500), because of the conflict by design between multiple Orchestra slotframes.

TSCH: fix backup link selection 

---

arch/platform/cc26x0-cc13x0/sensortag/board-buttons.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/button-sensor-arch.c

The button HAL is configured to use negative logic (active: low) for the sensortag's reed relay. This is incorrect, the reed is actually active high. This commit fixes the behaviour for both platforms that support sensortags.

Fix sensortag reed relay logic

---

tools/vagrant/bootstrap-vbox-with-x.sh

This PR provides the ability to optionally add the Xfce desktop environment to our Vagrant image when run with VirtualBox.
In order to make things work the user has to take some additional steps:
* Edit `tools/vagrant/Vagrantfile` and uncomment the following lines:
```
[...]
```
Within the commented block there is also a `  #   vb.memory = "1024"`. Leave that one commented.
* Create/Start/Provision the image as per the normal instructions
* Run `sudo ./contiki-ng/tools/vagrant/bootstrap-vbox-with-x.sh`.
This will install VirtualBox guest additions, X and the Xfce desktop environment.
* Start the image. This will now show the VirtualBox GUI.
* Login using username 'vagrant' and password 'vagrant'
* `sudo startx`
Wiki page will be updated once we have merged this.
ToDo: It should be …

Add optional support for X in our Vagrant image

---

arch/platform/cooja/contiki-conf.h

Cooja motes implement the button HAL API, but do not have the right defines in place, so it end up being unused.

add PLATFORM_HAS_BUTTON to coojamote header files

---

os/dev/radio.h

This pull recommends extensive radio API documentation improvements based on the proposal in #197 
Once we adopt these semantics for our radio API (with or without changes), we'll need to go back to our TSCH and CSMA implementations to make sure that the radio API is being used consistently between the two. And #197 renamed to reflect that.
Here is what I am proposing to improve the situation without making any changes to the API. We will almost certainly have to modify some radio drivers and also CSMA. Perhaps some changes required for TSCH here and there, but not 100% certain.
* `transmit()`: should be kept as simple as possible:
* It should not try to guess what the MAC layer may need to do next. It may, but should not be expected to put the radio in RX after TX. What I am proposing is …

Extend documentation of the radio API

---

arch/cpu/native/net/tun6-net.c
arch/platform/native/cfs-posix-dir.c

This PR avoids the warning '__builtin_strncpy output may be truncated' showing up on newer compilers if strncpy is used in a way that might leave the resulting string without the null-terminating character.
This handles just the native platform, there are a few other places in Contiki-NG that seem to have similar strncpy uses.

fix number of strncpy uses in the native platform

---

arch/platform/native/Makefile.native

Building examples on the native platform with a recent compiler is currently broken. This PR disables one particular warning to enable building them again.
The error message is as below:
```
atis@atis-laptop:~/work/pull/contiki-ng/examples/hello-world$ make TARGET=native
MKDIR     build/native/obj
CC        ../../arch/platform/native/./platform.c
CC        ../../arch/platform/native/./clock.c
CC        ../../arch/platform/native/dev/xmem.c
CC        ../../arch/platform/native/./cfs-posix.c
CC        ../../arch/platform/native/./cfs-posix-dir.c
In file included from /usr/include/string.h:495,
from ../../arch/platform/native/./cfs-posix-dir.c:37:
In function ‘strncpy’,
inlined from ‘cfs_readdir’ at ../../arch/platform/native/./cfs-posix-dir.c:69:3: …
```

native platform: disable the warning '__builtin_strncpy output may be truncated'

---

os/net/app-layer/coap/coap.c

Fixed bugs in coap_parse_message() function that caused read memory access beyond the message buffer due to insufficient verification of buffer pointer arithemtic operations result.

Fixed coap packet parser message buffer out-of-bounds read bugs.

---

.github/workflows/build.yml

Github Actions seem to fail due to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Update Github Actions: replace set-env with environment files

---

arch/platform/simplelink/cc13xx-cc26xx/launchpad/cc1312r1/Makefile.cc1312r1

Enable BSL support for CC1312r1

---

arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
arch/cpu/simplelink-cc13xx-cc26xx/dev/i2c-arch.c
arch/cpu/simplelink-cc13xx-cc26xx/dev/i2c-arch.h
arch/platform/simplelink/cc13xx-cc26xx/sensortag/bmp-280-sensor.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/hdc-1000-sensor.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/mpu-9250-sensor.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/opt-3001-sensor.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/tmp-007-sensor.c

All Simplelink sensortag sensing element drivers implement I2C transactions and bus manipulation internally using static functions. This creates a lot of code duplication.
This work in progress moves all those functions to a new module and makes them re-usable. It also changes all affected drivers to use those new functions.
This will be very handy once we have finalised our I2C HAL (#1242), since the new module implemented here is where we'd put all of the HAL's arch-specific functions.
~Requires #1283~

Add I2C manipulation module for platform Simplelink

---

arch/platform/simplelink/cc13xx-cc26xx/sensortag/hdc-1000-sensor.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/tmp-007-sensor.c

This PR addresses a couple of issues in the TMP007 and HDC1000 drivers, causing them to return invalid readings when using the Simplelink platform.
This addresses two of the issues reported in #1282.

Fix TMP007 and HDC1000 sensor readings on the Simplelink platform

---

arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc1350/Board.h
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc1350/CC1350STK.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc1350/CC1350STK.h
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc2650/Board.h
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc2650/CC2650STK.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc2650/CC2650STK.h
arch/platform/simplelink/cc13xx-cc26xx/sensortag/mpu-9250-sensor.c

The TI CC2650 and CC1350 SensorTags use alternate I2C pins for the MPU-9250. 
Currently the Simplelink platform does not support that, causing the MPU driver to read -0.01 for all axes.
This PR adds support for those pins, makes them available under `Board_I2C1`, and updates the MPU-9250 driver to use them.
Fixes #1282.

Support alternate I2C pins for SensorTags on Simplelink and use for MPU-9250

---

arch/platform/simplelink/cc13xx-cc26xx/sensortag/buzzer.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc1350/CC1350STK_fxns.c
arch/platform/simplelink/cc13xx-cc26xx/sensortag/cc2650/CC2650STK_fxns.c

This PR fixes the buzzer on CC2650 and CC1310 SensorTags on the Simplelink platform.
Fixes #1291.

Fix the SensorTag buzzer on Simplelink

---

Makefile.gcc

Older GCC versions generate broken executables for the nRF52840 platform. 
The resulting binaries appear functional but are unable to send or receive any packets.
#1449 has seen this happen with arm-none-eabi-gcc 4.9.3, and I can reproduce it with arm-none-eabi-gcc 5.2.1.
This PR warns anyone using a version of gcc older than 6.x with the nRF52840 platform and prompts them to update their toolchain.
Closes #1449.

Warn when using old GCC versions with platform nRF52840

---

.github/workflows/build.yml
os/net/app-layer/mqtt/mqtt-prop.c
tools/docker/Dockerfile

In this PR we are updating our old arm-gcc 5 to the latest version available at the moment arm-gcc 9
I expect this PR to break a few things. 
Example: The mqtt-client was not compiling with the following: "make BOARD=firefly DEFINES=MQTT_CONF_VERSION=5 TARGET=zoul"
This happened due to a new warning introduced on the GCC 9. "address-of-packed-member"
I expect that new warning will appear and they'll be fixed.
In order to support the new arm boards we need to update the arm-gcc.
The new nRF53 uses the Cortex-M33 that is not suppported by the current arm-gcc.

Updated arm-gcc to 9

---

tests/07-simulation-base/code-ipv6/receiver/udp-receiver.c
tests/07-simulation-base/code-ipv6/sender/udp-sender.c
tests/07-simulation-base/code-ipv6/sender/unicast-sender.c

Applied fixes proposed in #1458 on the develop branch

Removed unused vars from code-ipv6 tests (develop branch)

---

arch/platform/native/Makefile.native
arch/platform/native/platform.c

Changes:
-  fix compilation with SELECT_STDIN is set to 0
-  remove the -Wno-stringop-truncation flag - it's not recognized on older compilers, and is not necessary anymore now that strncpy uses have been fixed.

native platform minor changes

---

arch/cpu/nrf52840/rf/nrf52840-ieee.c

This PR adds a busy wait for the HFCLK during init to avoid hardware dependent race conditions (nrf boards seem to not be affected, custom boards with less reputable crystals are).

nRF52840 RF init HFCLK fix

---

os/net/ipv6/psock.h

There is a small typo in os/net/ipv6/psock.h.
Should read `structure` rather than `structrure`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, structrure -> structure

---

arch/cpu/simplelink-cc13xx-cc26xx/rf/prop-mode.c

The prop-mode.c driver for CC13XX platform is missing the
RADIO_PARAM_LAST_RSSI and RADIO_PARAM_LAST_LINK_QUALITY cases in the
get_value() function.  They are referenced in read_frame(), and are
present in the ieee-mode.c driver.  This commit just add them.

prop-mode.c missing LAST_RSSI and LAST_LINK_QUALITY paramters

---

arch/cpu/native/net/tun6-net.c

This PR fixes the bug shown below when trying to build `rpl-border-router` for `TARGET=native` on macos
```
~/contiki-ng/examples/rpl-border-router (develop)$ make TARGET=native
MKDIR     build/native/obj
CC        ../../arch/platform/native/./platform.c
CC        ../../arch/platform/native/./clock.c
CC        ../../arch/platform/native/dev/xmem.c
CC        ../../arch/platform/native/./cfs-posix.c
CC        ../../arch/platform/native/./cfs-posix-dir.c
CC        ../../arch/platform/native/dev/buttons.c
CC        ../../arch/cpu/native/net/tun6-net.c
../../arch/cpu/native/net/tun6-net.c:69:27: error: use of undeclared identifier 'IFNAMSIZ'
static char config_tundev[IFNAMSIZ + 1] = "tun0";
^
1 error generated.
make: *** [build/native/obj/tun6-net.o] Error 1
```

Fix native target builds on macos

---

arch/cpu/nrf52840/usb/Makefile.usb
arch/cpu/nrf52840/usb/usb-serial.c
arch/platform/nrf52840/config/sdk_config.h

Enabling the USB stack on boot works for the nRF52840 dongle, however, it can fail to enumerate on custom boards or on the DK when the native USB port is plugged in after boot.
This commit handles USB power events to enable and disable the nRF USB stack when the USB power state changes. This is necessary to make USB hotplugging work in any order.
Tested on both a DK and a dongle.

nrf52840: Implement USB power events for hotplug support

---

Makefile.gcc

The root cause for the compiler version warning added in #1462 was fixed by #1478 so this can be reverted safely.
This also closes #1449.
This PR also improves the gcc version detection for warnings as the current approach doesn't handle double digit versions correctly and misinterprets gcc 10 as 1.

Improve gcc version detection and revert obsolete make warning

---

README.md

This pull adds to our README shields.io badges with links to the various spaces we use for engagement with the community. Just because we can :)
I am showing two possible places here, one below the existing row of badges, or an alternative at the bottom. Choice up for debate!
Live view: https://github.com/g-oikonomou/contiki-ng/blob/contrib/social-badges/README.md

Add readme badges for community engagement spaces

---

arch/cpu/nrf52840/Makefile.nrf52840
arch/cpu/nrf52840/usb/Makefile.usb

#1501 introduced a bug where the nrf52840 platform will crash unless USB support is compiled in.
This is caused by a missing IRQ handler after enabling the power driver in sdk_config.h but not compiling in the relevant SDK sources.
This PR moves the power driver away from this conditional build.

nrf52840: Always build power driver

---

.gitignore
arch/platform/zoul/firefly-reva/board.h
arch/platform/zoul/firefly/board.h
arch/platform/zoul/orion/board.h
arch/platform/zoul/remote-reva/board.h
arch/platform/zoul/remote-revb/board.h

The current implementation of the board header files for zoul platforms prevents enabling/disabling dual radio usage via an application's project-conf.h file as [explained here](https://github.com/Zolertia/Resources/wiki/RE-Mote-2.4GHz-dual-antenna#enabling-both-radios-in-contiki) (which should be standard behavior IMO). A simple preprocessor check solves this issue. 
~Second (and unrelated), vscode keeps adding an annoying hidden config folder and I really think this belongs in the gitignore. However, it's so minor of a change that I didn't really think dedicating an entire pull request to it was warranted.~

Bugfix: remote dual rf

---

arch/cpu/nrf52840/clock.c
arch/cpu/nrf52840/dbg.c
arch/cpu/nrf52840/dev/uart0.c
arch/cpu/nrf52840/dev/watchdog.c
arch/cpu/nrf52840/nrf52840-conf.h
arch/cpu/nrf52840/rf/nrf52840-ieee.c
arch/platform/nrf52840/common/temperature-sensor.c
examples/sensniff/Makefile
examples/sensniff/README.md
examples/sensniff/nrf52840/target-conf.h
examples/sensniff/pool/nrf52840-io.h

This PR adds support for the nRF52840 to sensniff.
A few small issues popped up during this, and the fixes are part of this PR:
* Some device drivers had the wrong include order and were pulling in `nrf52840-conf.h` early.
* The UART baud rate was not configurable.
* The RF driver did not ramp up the radio after changing the channel, which is required to actually switch to it.
Both UART and USB transports are supported, with the USB transport used by default on the dongle and enabled by passing the usual `NRF52840_NATIVE_USB=1` make option for the dk.

Add nRF52840 support to sensniff

---

os/net/ipv6/sicslowpan.c

This PR adds a buffer boundary check before reading from hc06_ptr in a loop condition in the <code>uncompress_hdr_iphc</code> function. The behavior is visible when injecting certain packets into Contiki-NG when running in native mode with ASAN enabled.

Add buffer boundary check in sicslowpan

---

arch/cpu/nrf52840/usb/usb-dfu-trigger.c
arch/cpu/nrf52840/usb/usb-dfu-trigger.h
arch/cpu/simplelink-cc13xx-cc26xx/rf/rat.c

Those two doxygen modules were appearing at the top of the module tree:
https://contiki-ng.readthedocs.io/en/master/_api/modules.html
This PR moves to the a more suitable location in the tree

Move doxygen modules to the correct location

---

examples/sensniff/Makefile

This pull:
* Updates the `tools/sensniff` submodule to the latest version. This adds execute permission to the script and substitutes an obsolete function names for current ones. We change the shebang `python3`
* We update the respective example to call the script directly
Ticks off a box in #1453

Migrate sensniff to python3

---

arch/cpu/cc26x0-cc13x0/dev/contiki-watchdog.c

This PR:
1. Sets the INTEN bit in the WD CTL register via call to `ti_lib_watchdog_enable()`. The [Technical Reference Manual (TRM)](https://www.ti.com/lit/pdf/swcu117) states this must be set to enable the WDT (even though it works without it today). So this change is simply for conformity with TRM.
2. Remove unnecessary `ti_lib_watchdog_reload_set()` from init()
3. Fixes `watchdog_periodic()`: The current call to `ti_lib_watchdog_reload_set()` does nothing since the registers are locked. In addition, it is superfluous because `ti_lib_watchdog_int_clear()` actually resets the counter (see Table 15-5 in TRM) - it's this which avoids the WD triggering today. Since there is no interrupt registered, the actual time needed for a reboot to be triggered is 2 x the configured timeout-value (the …

Improve cc26xx/cc13xx watchdog

---

examples/benchmarks/result-visualization/run-analysis.py

So far, the result visualization example was only able to work with RPL Classic output. This simple change allows it to also be tested with RPL Lite.

result visualization example: update the example to also be able to parse RPL Lite output

---

os/net/ipv6/multicast/esmrf.c

Using MRHOF, the root rank is 128, otherwise 256.
To correctly identify the root (by rank) we need to adjust it depending on using / not using the MRHOF as an objective function.

Correctly identify the root when using MRHOF

---

tests/08-native-runs/mqtt-client.sh

The docker image now pulls in mosquitto 2.0 which has [different defaults](https://mosquitto.org/documentation/migrating-to-2-0/) and only binds to loopback interfaces. 
This in turn breaks the native MQTT tests in `08-native-runs`.
This PR restores the old behaviour of listening on all interfaces and allowing anonymous access in the test.

Fix native tests with mosquitto 2.0

---

tests/08-native-runs/mqtt-client.sh
tools/docker/Dockerfile

This PR installs all utilities needed to program devices supported by the nrf52840 platform on the docker image.
A couple of workarounds for upstream issues are in place:
* The 32-bit `nrfjprog` looks for `libjlinkarm_x86.so` but the library is called `libjlinkarm.so`.
* `nrfutil` has a broken dependency `pc_ble_driver_py` which causes pip to install an old version that's incompatible with Python 3. We upgrade it ignoring that dependency, as it's only needed for BLE OTA updates.
* `nrfutil` requires the `C.UTF-8` locale to be used.
Closes #1536
Requires #1550 first

Install nrfjprog and nrfutil in docker image

---

Makefile.include

Currently, the Contiki-NG build system always overrides the value of CXXFLAGS. This is not correct - it should append rather than override this variable, so that the users can set their own initial value.

Allow to set an initial CXXFLAGS value from the command line of application's Makefile

---

os/net/app-layer/snmp/snmp-engine.c

When looping over the <code>varbinds</code> array, the element index is checked against the maximum value only after reading the array from that index. This PR fixes the problem by moving the checks before the read.

Fix out-of-bounds read in SNMP

---

os/net/app-layer/snmp/snmp-ber.c

The <code>*length</code> value in  can be controlled through an input packet, but it is not validated correctly. An attacker can thus cause an overflow of the <code>used</code> variable. This PR changes the check to a comparison instead of a subtraction.
Thanks to Tobias Scharnowski from Ruhr-University Bochum for the initial reporting of a missing length check.

Fix the length field check for SNMP input packets

---

os/sys/cc-gcc.h
os/sys/cc.h

This PR adds the `CC_DEPRECATED("Deprecation message")` macro as a gcc-specific shortcut for `__attribute__((deprecated("Deprecation message")))` to be used when altering API functions.
Example usage:
`CC_DEPRECATED("Use other_method instead") void some_method(void);`
Resulting in the following warning (or error with -Werror):
`error: 'some_method' is deprecated: Use other_method instead [-Werror=deprecated-declarations]`

Add deprecation macro

---

examples/6tisch/timesync-demo/node.c
examples/mqtt-client/mqtt-client.c
examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/cc26x0-web-demo.c
examples/platform-specific/nrf52dk/mqtt-demo/mqtt-demo.c
os/net/ipv6/sicslowpan.c
os/net/ipv6/sicslowpan.h
os/net/ipv6/uipbuf.h

Adds these fields to the uipbuf, and replaces the function `sicslowpan_get_last_rssi()` which provided similar functionality, but was not as clean in API sense (also, I could not find it when required, so made this change before discovering it exists :P)

add UIPBUF_ATTR_RSSI and UIPBUF_ATTR_LINK_QUALITY attibutes to uipbuf

---

os/lib/heapmem.c

Add overflow guards to avoid having very large allocations appear as if they succeeded.

Fix overflow bug in the HeapMem module

---

os/net/routing/rpl-classic/rpl-dag.c
os/net/routing/rpl-lite/rpl-neighbor.c
os/net/routing/rpl-lite/rpl-neighbor.h
tests/07-simulation-base/08-ipv6-unicast.csc
tests/07-simulation-base/09-ipv6-broadcast.csc
tests/07-simulation-base/code-ipv6/receiver/project-conf.h
tests/07-simulation-base/code-ipv6/receiver/udp-receiver.c
tests/07-simulation-base/code-ipv6/sender/project-conf.h
tests/07-simulation-base/code-ipv6/sender/udp-sender.c
tests/07-simulation-base/code-ipv6/sender/unicast-sender.c
tests/07-simulation-base/ipv6.js

Also, removes the function `rpl_neighbor_is_reachable` of RPL lite, as it was not used in the code.
Fixes #1498.

RPL: do not assume that a neighbor is unreachable if IPv6 neighbor discovery status is not REACHABLE

---

arch/cpu/cc2538/dev/ecc-curve.h
arch/dev/sensor/bme280/bme280.c
arch/dev/sensor/bme280/bme280.h

I updated my local toolchain and noticed that the test to compile all arm targets was failling. Probably related to #1567.
The issue is better described here: https://gcc.gnu.org/gcc-10/porting_to.html
Basically from gcc 10 it defaults to -fno-common which does not allow variables to be declared in header files without the extern

Fixed variable declaration on headers on ARM GCC 10

---

arch/dev/sensor/dht11/dht11-sensor.c
arch/dev/sensor/dht11/dht11-sensor.h
examples/dev/dht11/Makefile
examples/dev/dht11/dht11.c
tests/02-compile-arm-ports/Makefile

In this PR I implemented the DHT11 sensor which is a low cost humidity and temperature sensor.
Product: https://www.mouser.dk/ProductDetail/OSEPP-Electronics/HUMI-01?qs=wNBL%252BABd93P6g2NY71n2BA%3D%3D
Datasheet: https://www.mouser.com/datasheet/2/758/DHT11-Technical-Data-Sheet-Translated-Version-1143054.pdf
There is an implementation of the DHT22 in the Contiki-NG code base but this implementation is very bound to the Zoul platform.
Since the sensor requires granularity of 1us and the rtimer granularity is not so small, a few tricks were used to get the timing right. I used an nrf 52840 DK to test this but since I'm using the rtimer functions to calculate ticks it should work in any platform.

DHT11 Sensor

---

arch/dev/radio/cc1200/cc1200-conf.h
arch/dev/radio/cc1200/cc1200.c
tests/02-compile-arm-ports/Makefile

Compilation with 15.4g mode on CC1200 was failing with recent GCC versions. This fixes it.
Also it makes `CC1200_802154G_CRC16` dependent on `CC1200_802154G`, so that the 15.4g checksum is used by default when 15.4g is enabled.

CC1200: 802.15.4g mode fixes/improvements, and compile test added

---

arch/cpu/arm/cortex-m/mutex-cortex.h

This PR fixes #1544 by adding a spinlock to the LDREXB+STREXB procedure. This avoids mutex lock fail in cases where we are  interrupted after LDREXB but ISR does not actually lock the mutex (see details in #1544). Note that this does not add a spinlock to the lock itself, if it is actually taken, we still immediately return.

Add spinlock on LDREXB/STREXB-pair for cortex mutex lock

---

arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-def.h
arch/cpu/cc26x0-cc13x0/rf-core/ieee-mode.c
arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
arch/cpu/simplelink-cc13xx-cc26xx/cc13xx-cc26xx-def.h
arch/cpu/simplelink-cc13xx-cc26xx/rf/ieee-mode.c
arch/cpu/simplelink-cc13xx-cc26xx/rf/prop-mode.c

The discussion and motivation for this is in #1528 .
TL;DR: 
1. Make the waiting time in read_frame() dependent on RADIO_BYTE_AIR_TIME multiplied by the sum of RADIO_CONST_PHY_OVERHEAD and MAX_PAYLOAD_LEN (and round the result up in rtimer ticks, and add some small guard time). It will work correctly and efficiency in different datarates, unlike the current approach which uses a constant time.
2. Set `cmd_rx_adv->maxPktLen` to the actual max frame size supported by the current config of the Contiki-NG network stack. Previously the value 2047 from the standard was used. This lead to receivers occasionally being on for a very long time while up to 2047 bytes were received, even when the packet would be dropped anyway because of the network stack not being able to process it.

CC radios: make waiting time in read_frame dependent on the maximum packet size instead of using hardcoded values and fix maxPktLen for CC13xx

---

tests/07-simulation-base/26-tsch-drift-z1.csc

This test is designed to fail until the clock deviation functionality is fixed in Cooja.
The following PR should be applied: https://github.com/contiki-ng/cooja/pull/50

Add test simulation for MspMote clock deviation functionality

---

os/net/ipv6/uip-ds6-nbr.c
os/net/ipv6/uip-ds6-nbr.h

Apart from being unused, this function always returned the first neighbor due to a bug.

Removed unused function uip_ds6_get_least_lifetime_neighbor()

---

os/net/routing/rpl-classic/rpl-icmp6.c

By sending a DIO with a too large length in the prefix info option, it is possible to cause a buffer overflow when copying the prefix in the <code>set_ip_from_prefix</code> function. In this PR, we insert a validation check that discards the DIO if this value is too large.

Verify DIO prefix info lengths in RPL-Classic

---

os/net/app-layer/snmp/snmp-api.h
tests/01-compile-base/Makefile
tests/04-compile-nxp-ports/Makefile

Targets: z1, sky and jn516x were not compiling the snmp-server due to syntax issues.

Fix snmp server compilation on z1, sky and jn516x

---

examples/slip-radio/Makefile
tests/02-compile-arm-ports/Makefile

On the nrf target the slip-arch requires UART and the nrf52840 dongle does not support it, so we skip it.

Skip nrf52840/dongle on slip-radio

---

examples/platform-specific/zoul/test-vbat.c

The issue was discovered with the build-all.sh script. The fix simply makes the example code conditional on having the right board.

Zoul: fix building of platform-specific/zoul/test-vbat example

---

examples/benchmarks/result-visualization/run-analysis.py
os/net/ipv6/sicslowpan.c
os/net/link-stats.c
os/net/link-stats.h
os/net/mac/csma/csma-output.c
os/net/mac/mac.h
os/net/mac/tsch/tsch.c

Allows to collect statistics on queue losses, which are important for network performance evaluation.

MAC: add MAC_TX_QUEUE_FULL error code, and account it in link stats separately

---

os/net/routing/rpl-classic/rpl-timers.c

If DIO messages with 0 lifetimes are accepted, it can lead to a division by zero when calculating the interval timer length. This PR simply increases the values to 1 in those cases.

Avoid division by 0 due to lifetimes and units of zero in RPL Classic

---

os/net/app-layer/snmp/snmp-ber.c

The <code>str</code> variable is incremented by <code>length - 1</code>, which will wrap if <code>length</code> equals 0.

Prevent integer wrapping in snmp-ber

---

os/net/routing/rpl-classic/rpl-icmp6.c

RPL-Classic accepts RPL Target options in DAO messages with invalid prefix lengths. Additionally, it does not check whether there are enough bytes in the packets to copy a prefix of this length. This PR adds checks for these conditions so that the DAO message can be discarded.

Check RPL Target prefix length and buffer boundary.

---

os/net/ipv6/uip-nd6.c

Fixes a possible compilation warning.

uip-nd6: Make sure that the flags variable is initialized.

---

os/net/ipv6/sicslowpan.c

Before copying <code>packetbuf_payload_len</code> bytes, we must verify that there is enough room in the buffer from the <code>uncomp_hdr_len</code> offset.

sicslowpan: Check that there is enough space in the buffer to copy the payload.

---

os/net/ipv6/uipbuf.c

When processing IPv6 extension headers in uipbuf.c, we need to check the offset before casting to a <code>uip_ext_hdr</code> pointer.

uipbuf: Do not assume that there is enough space for a following extension header

---

os/net/ipv6/sicslowpan.c

A non-functional change to refer to RFC 6282 instead of the old HC-06 Internet draft.

sicslowpan: Update variable names and documentation

---

os/services/resolv/resolv.c
os/services/resolv/resolv.h

This PR
* ~~Fixes a bug in resolv where when switching to next nameserver, the query would not be sent until `255 * retry-time` (set to 250 ms).~~
* Separated into #1676 
* Cleans up the debug-logging (removed ad-hoc `VERBOSE_DEBUG` concept) and other related fixes to make debug-logging compile
* Cleanup (afaik) unnecessary `volatile`, `register` and large variable scopes
* Minor clean-up of the log output
* ~~Some fixes to code style~~
* Run uncrustify-fix-style on resolv.c/.h

Minor cleanup in resolv service

---

os/services/resolv/resolv.c

This PR fixes a bug in resolv where when switching to next nameserver, the query would not be sent until 255 * `retry` (set to 250 ms).
This happens because `try_next_server()` sets `retries` to 0. Thus, `tmr` will be set to 0 at https://github.com/contiki-ng/contiki-ng/blob/develop/os/services/resolv/resolv.c#L623. At next call to `check_entries()`, the 0 in `tmr` will be decremented and wrap to 255 at https://github.com/contiki-ng/contiki-ng/blob/develop/os/services/resolv/resolv.c#L599. With this PR the wrap is avoided and next server queried at the first opportunity after switching to it.

Immediately try to resolve when switching DNS server

---

arch/platform/cooja/dev/cooja-radio.c

here fixed cooja-radio RADIO_PARAM_LAST_RSSI and RADIO_PARAM_LAST_LINK_QUALITY - now it reports rssi and lqi captured at packet start.
* there was used current rssi(cca) for last packet, but accidentaly, cooja updates it right after packet end, and if mote code not luck, it miss rssi at packet end, and got current strength (after packet) on air.

fix cooja-radio RADIO_PARAM_LAST_RSSI and RADIO_PARAM_LAST_LQI

---

arch/platform/nrf52840/platform.c

Configure serial-line to use USB instead of UART0 when native USB is enabled. dbg-io is already configured to output via USB when native USB is enabled.

nrf52840: configure serial-line (and shell) for USB when native USB is enabled

---

arch/cpu/msp430/Makefile.msp430
arch/platform/jn516x/Makefile.jn516x

This aligns the behavior of these ports with the documentation of C99 in the wiki.
This also fixes the compilation errors in pull request #1761 for me locally.

Compile msp430 & jn516x as gnu99 instead of gnu89

---

arch/platform/cooja/platform.c

The size of long is platform dependent
so trying to store the address of a
variable might lead to truncation. Use
intptr_t instead which is guaranteed
to fit an address.

cooja: use intptr_t for referenceVar

---

tools/docker/Dockerfile

The end of life for Java 8 is 31 Mar 2022,
use the existing Java 11 packages instead.

Dockerfile: update to Java 11

---

os/services/lwm2m/lwm2m-engine.c

The size of an enum is not fixed, so
GCC 12 complains that the snprintf might
truncate the value written into the buffer.
Increase the size of the buffer so
the regression tests compile without warnings
on Ubuntu 22.

lwm2m: fix GCC 12 truncation warning

---

tools/vagrant/bootstrap.sh

The contiker alias inside our vagrant image still points to the old docker image at `simonduq/contiki-ng`. This PR fixes this

Fix contiker alias in vagrant image

---

examples/rpl-border-router/webserver/httpd-simple.c
os/services/rpl-border-router/native/slip-config.c
os/services/rpl-border-router/native/tun-bridge.c

GCC 8 added the -Wstringop-truncation warning
which makes the regression tests fail on recent
versions of Ubuntu. Silence the compiler by
copying one character less, and add an explicit
null termination afterwards when required.

rpl-border-router: fix GCC 8 warnings

---

tests/Makefile.compile-test

Running 19-out-of-tree-build in the Docker
image on my local computer hangs without
output. The reason is that the return value
of cd is ignored in the Makefile, replacing
";" with "&&" gives us a proper failure.
The clean rule has a similar problem.
Getting the message that make could not cd
into /home/user/out-of-tree-tests can still
be confusing, so add an explanation for
the failure by adding a dependency on the directory
and make the rule for that directory echo
the expected action and then fail.
The reason this test works in the Github CI
is that build.yml ensures /home/user/out-of-tree-tests
is populated before starting docker.

tests: ensure cd is successful

---

Makefile.include

Trying to "make login PORT=/dev/ttyACM2"
in the hello-world example for a target
without installed toolchain currently
results in:
make: msp430-gcc: Command not found
make: msp430-gcc: Command not found
make: msp430-gcc: Command not found
/bin/sh: 1: test: -lt: unexpected operator
rlwrap ../../tools/serial-io/serialdump -b115200 /dev/ttyACM2
connecting to /dev/ttyACM2
Add a check that $(CC) can be found after
including Makefile.$(TARGET) to ensure
that make immediately stops even
if the target Makefile is missing
error checks for the toolchain. For sky,
this results in the error message:
make: msp430-gcc: Command not found
make: msp430-gcc: Command not found
./../Makefile.include:108: *** Target "sky" compiler "msp430-gcc" cannot be found.  Stop.

Stop with error when $(CC) is missing

---

os/net/routing/rpl-classic/rpl-dag-root.c

Fix for #1568. Tested with standalone RPL root and RPL border border.

Fix RPL classic border router prefix

---

tools/docker/Dockerfile

Important remark: ARM does not support i386 anymore so I created a workflow that builds it following arms instructions.
https://github.com/Yagoor/gcc-arm-none-eabi
I didn't update to 11.2 because it has some severe bugs. Therefore I believe we should wait before updating the toolchain to the latest and greatest.

Updated gcc on Dockerfile to 10.3 2021.10

---

Makefile.gcc

GCC 7 in Ubuntu 18 and GCC 9 in Ubuntu 20
only emits the major version when called
with -dumpversion which causes GCC_MINOR_VERSION
to become empty. GCC also has a -dumpfullversion
that will emit the entire version on GCC 7
and later, but msp430-gcc will fail with
an error message because there are no input
files.
Adding both parameters makes both msp430-gcc
and GCC 7/9 on Ubuntu provide the full version
so use that in the GCC version detection.

Fix version detection for recent gcc

---

Makefile.include

Allow the user to call make with
a specific Q on the command line.
This enables the user to see all
the calls to the tools by specifying
Q="" when calling make. It also enables
a really quiet mode if the user combines
V=1 and Q=@.

Makefile: allow overriding $(Q)

---

tests/simexec.sh

After the upgrade to Java 11, the simulation
tests get the warning:
Warning: Nashorn engine is planned to be removed from a future JDK release
Supress the warning since it is an issue with
Cooja and not relevant for the Contiki-NG tests.

tests: suppress Nashorn removal warning

---

tests/07-simulation-base/01-hello-world-sky.csc
tests/07-simulation-base/02-ringbufindex.csc
tests/07-simulation-base/07-hello-world-z1.csc
tests/07-simulation-base/22-stack-guard-sky.csc

This fixes a link failure in 02-ringbufindex
because of mismatched object types when running
tests in the 32 bit docker and a 64-bit host
using the same source tree.
Add the make clean for the sky/z1 tests as well
to reduce the risk that future cut&paste based
on existing tests reintroduces this issue.

tests: add missing clean

---

arch/platform/cooja/Makefile.customrules-cooja

This reduces the amount of output from
Cooja unless running with V=1.
Add an echo before the final link so
it's possible to diagnose whether the build
step completed when asking for Cooja output
during support requests. Example of error
message from a failing build:
Message:> make test-ringbufindex.cooja TARGET=cooja
Message:  CC        test-ringbufindex.c
...
Message:Redefining printf,sprintf,vsnprintf,etc.
Message:Linking build/cooja/mtype364.cooja
Message:/usr/bin/ld: i386 architecture of input file `build/cooja/mtype364.a(simEnvChange.o)' is incompatible with i386:x86-64 output
...

cooja: add $(Q) to the customrules

---

Makefile.include

This improves build times when source files
are unchanged. On a warm cache, my machine
gets a 98% hitrate for tests/01-compile-base:
cache hit (direct)                  1621
cache hit (preprocessed)               0
cache miss                            33
cache hit rate                     98.00 %
compile failed                         4
couldn't find the compiler             9
cleanups performed                     0
The 9 "couldn't find the compiler" are caused by
not having msp430-gcc installed on my machine,
and the failed compilations are caused by
compiler warnings.

Makefile: add support for ccache

---

arch/cpu/nrf/Makefile.nrf
arch/cpu/nrf52840/Makefile.nrf52840

Replace the echo "ERROR: .." with
a call to $(error) to ensure make
fails with a non-zero return value.

nrf: fail when missing $(NRFJPROG)

---

tests/06-script-base/code-result-visualization/00-result-visualization.csc
tests/13-ieee802154/01-panid-handling.csc
tests/13-ieee802154/02-tsch-flush-nbr-queue.csc
tests/14-rpl-lite/10-rpl-resetting-dio-timer-by-dis.csc
tests/15-rpl-classic/10-rpl-multi-dodag.csc
tests/15-rpl-classic/11-rpl-resetting-dio-timer-by-dis.csc

This fixes more non-reproducible failures
in Cooja simulations.
This is a sibling to commit 82af502b98e.

tests: add more missing cleans

---

arch/cpu/msp430/Makefile.msp430

The checks for how to compile should
be with respect to the compiler used
for the build.

msp430: configure according to $(CC)

---

arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-def.h

Prior to version 4.7, the TSCH_CONF_ASSOCIATION_POLL_FREQUENCY for the CC26xx/CC13xx was 1000.
Version 4.7 changed it to 10 with the attempt to improve the association performance (PR #1515).
After user complains on actually reduced performance the PR reverts this change.

TSCH_CONF_ASSOCIATION_POLL_FREQUENCY revert change

---

arch/platform/cooja/platform.c

Commits:
0910d705 Merge pull request #66 from pjonsson/remove-java-version
c820b9f4 Merge pull request #67 from pjonsson/update-log4j
67f5ec95 Merge pull request #63 from nfi/contrib/macos-xcode
9c4e9c75 Merge pull request #65 from pjonsson/addroffset
5777566a Merge pull request #64 from pjonsson/return-failure
709f1636 Merge pull request #62 from pjonsson/64-bit-fixes
37d84b7e Update to log4j 2.17.2
17782d47 build.xml: remove unused java_version target
f2e3b34a Read offset as address variable
8ebd233b Merge pull request #25 from MBradbury/queue-perf
14570f68 Updated MacOS config for Xcode 13+
8eae30bd Do not crash on compilation failure
96ea580d Use jlong for addresses
7a7fd5e4 Merge pull request #24 from MBradbury/exit-handler
8da69a55 Merge branch 'master' into exit-handler
1e134623 …

Update tools/cooja submodule

---

examples/6tisch/etsi-plugtest-2017/test-with-cooja-mote.csc
examples/6tisch/simple-node/rpl-tsch-cooja.csc
tests/07-simulation-base/02-ringbufindex.csc
tests/07-simulation-base/26-cooja-rpl-tsch-orchestra-perfect-link.csc
tests/13-ieee802154/01-panid-handling.csc
tests/15-rpl-classic/10-rpl-multi-dodag.csc

Cooja currently prints:
WARN [main] (Cooja.java:4314) - Replaced [APPS_DIR]/radiologger-headless with /home/user/contiki-ng/tools/cooja/apps/radiologger-headless (default: /home/user/contiki-ng/tools/cooja/apps), but could not find it. This does not have to be an error, as the file might be created later.
WARN [main] (Cooja.java:3678) - Loaded simulation may depend on not found  extension: '/home/user/contiki-ng/tools/cooja/apps/radiologger-headless'
in the regression tests. Remove the references
to the third-party module radiologger-headless
to avoid these warnings.

Fix Cooja warning in tests/examples

---

arch/cpu/msp430/isr_compat.h
arch/cpu/msp430/msp430-def.h

This makes the msp430 header files compile
with gcc 9 from Texas Instruments.

msp430: gcc 9 compilation fixes

---

tests/06-script-base/04-test-result-visualization.sh
tests/simexec.sh

Let the Cooja output echo to stdout in
the tests. This simplifies simexec.sh
and also gives a slight speedup since
the removed polling loop always slept
for 1 second per iteration.

tests: display cooja output

---

tests/00-documentation/Makefile
tests/05-compile-tools/Makefile
tests/Makefile
tests/Makefile.compile-test
tests/Makefile.script-test
tests/Makefile.simulation-test

Simultaneously doing clean and build in
parallel might cause failures that are
difficult to reproduce. Make the targets
that run clean finish cleaning before
starting a build.

tests: clean before other targets

---

Makefile.include
arch/cpu/msp430/Makefile.msp430
arch/platform/sky/Makefile.common

This has not been used for years and
there are no regression tests for this
part of the build system. Remove the build
system support as a start.

msp430: remove IAR build system support

---

arch/platform/cooja/contiki-conf.h
arch/platform/jn516x/jn516x-def.h
arch/platform/native/contiki-conf.h
os/sys/cc.h
tools/doxygen/Doxyfile

The defined macros are not used in Contiki-NG
so remove the ifdefs.

Remove unused CC_CONF_*

---

os/storage/cfs/cfs-coffee.c
os/storage/cfs/cfs.h

Fixes a potential out-of-bounds access in cfs-coffee. Firstly suggested in https://github.com/contiki-ng/contiki-ng/pull/1502, and discussed in https://github.com/contiki-ng/contiki-ng/pull/1502#discussion_r645089921.

Avoid out-of-bounds access in cfs-coffee

---

arch/platform/cooja/sys/cooja_mtarch.c
arch/platform/cooja/sys/cooja_mtarch.h

Stop assuming a 32 bit platform when __WORDSIZE
is missing and use C99 INTPTR_MAX to detect
the size of pointers. Fail with an error message
when detection fails.
Unsigned long will not fit a register on
all platforms so switch the types in
the frame struct to use uintptr_t. There is
no general guarantee uintptr_t is sufficient,
but the rest of the code uses inline assembly
for X86 and this will work on all modern
X86 platforms.

cooja: use C99 uintptr_t

---

arch/platform/cooja/platform.c

Remove the extra copy into 'mem', this
saves up to two copies.

cooja: copy directly into dst

---

Makefile.include
arch/cpu/msp430/Makefile.msp430
arch/platform/cooja/Makefile.cooja

Add detection of $(JAVA_HOME) in
the build system so Cooja does not
need to know about Contiki-NG
build-internal details.
Since this requires the build system
to know about $(JAVA), also update
platforms that use the plain string
"java" to use the new variable.

Makefile: detect $(JAVA_HOME)

---

os/net/routing/rpl-classic/rpl-icmp6.c

When there are padding options in the message, the implementation currently writes that this is an unrecognized option, which is false. Additionally, PAD1 options are incorrectly written with a length of 4294967295 bytes.

Correct debug output for DIO padding options in RPL-Classic

---

os/services/resolv/resolv.c
os/services/resolv/resolv.h

This PR fixes a variety of issues with the processing of input in the resolver module:
1. DNS names are processed with boundary checking.
2. Packets without an answer section are no longer dropped. Instead, the packet continues to be processed in order to process potential error flags for a query, and thereby be able to signal to the initiator of the query that the domain does not exist. Previously, the query could be retransmitted multiple times before timing out, even if response packets indicating a lookup failure were received.
3. The code has been changed in various ways to improve readability.
4. MDNS has been disabled by default because it is rarely used.

Resolver: fix issues with the processing of DNS responses

---

arch/platform/cooja/platform.c

This function is required to return
the JNI version for the functions we
use, and we use some that are later
than 1.1. Without the function, the JVM assumes
JNI Version 1.1.
Java 11 is the oldest supported Java version
so make the function return JNI_VERSION_10.

cooja: add a JNI_OnLoad function

---

tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh
tests/18-coap-lwm2m/08-lwm2m-qmode-ipso-test.sh
tests/18-coap-lwm2m/09-lwm2m-qmode-standalone-test.sh

The files downloaded are 19150-42000K
so the progress indicators are substantial.
Switch wget to non-verbose mode.

tests: make wget non-verbose

---

os/net/link-stats.c
os/net/link-stats.h

This fixes #1629 as well as changes the initialization of ETX. Instead of starting from the default ETX in case a link stats entry is created on sending a packet, we start with the packet's ETX. This should help the EWMA of the ETX to converge faster.
I also added a special value `LINK_STATS_RSSI_UNKNOWN` to be used instead of 0, as 0 potentially (theoretically) could be a valid RSSI value.

link stats: fix initialization of RSSI and improve initialization of ETX

---

arch/cpu/native/Makefile.native

Cooja is currently the user of map files
on the native platform, but that build configuration
resides in Cooja.

native: do not create a map file

---

os/lib/heapmem.c

In the event of double free bugs, the double linked list maintained by `heapmem` gets corrupted and causes hard-to-track-down crashes. This PR adds an asssertion to detect such bugs early on.

heapmem: detection of double free bugs

---

tests/02-compile-arm-ports/Makefile

The current simple-node test is built with
MAKE_WITH_SECURITY=0 and MAKE_WITH_ORCHESTRA=0
which was probably not the intention. Adjust
the test to build with MAKE_WITH_SECURITY=1
and MAKE_WITH_ORCHESTRA=1.

cc2538dk: fix test flags for 6tisch/simple-node

---

Makefile.embedded
Makefile.include

The build system defaults to TARGET=native so
typing "make motelist-all" gives:
TARGET not defined, using target 'native'
make: *** No rule to make target 'motelist-all'.  Stop.
Move the diagnostic motelist-all target to
Makefile.include so the user can get a listing
of the devices connected to the computer regardless
of TARGET.

native/cooja: enable motelist-all target

---

arch/cpu/native/Makefile.native

The --export-dynamic flag adds all symbols
to the dynamic symbol table. This might be
required when using dlopen like Cooja does,
but the Cooja platform has its own Makefile
and build flags.

native: do not add everything to symtable

---

arch/cpu/native/Makefile.native
tests/06-script-base/code-test-lc/Makefile
tests/06-script-base/code-test-memb/Makefile

Make predefines variables such as CC, CXX,
AS and so on, so using ?= to define
them in a Makefile will have no effect.
Switch the Makefiles to using = instead.

native: do not use ?= for make predefines

---

tests/Makefile.simulation-test
tests/simexec.sh

IMPORTANT: Merge after #1852.
Cooja now prints the simulation so remove
the echo from simexec.sh and run ant in
silent mode so only errors and warnings
are printed.
Also add a $(Q) definition and .PHONY directive
to Makefile.simulation-test while changing it.

tests: reduce output in Cooja tests

---

os/lib/circular-list.c
os/lib/circular-list.h
os/lib/dbl-circ-list.c
os/lib/dbl-circ-list.h
os/lib/dbl-list.c
os/lib/dbl-list.h
os/lib/list.c
os/lib/list.h
os/net/app-layer/coap/coap-observe.c
os/net/app-layer/coap/coap-observe.h
os/net/app-layer/coap/coap.c
os/net/ipv6/udp-socket.c
os/net/ipv6/udp-socket.h
os/net/ipv6/uip-nd6.c
os/net/ipv6/uip-nd6.h
os/net/ipv6/uip-sr.c
os/net/ipv6/uip-sr.h
os/net/mac/framer/frame802154.c
os/net/mac/framer/frame802154.h
os/net/mac/framer/frame802154e-ie.c
os/net/mac/framer/frame802154e-ie.h
os/net/mac/framer/nullframer.c
os/net/nbr-table.c
os/net/nbr-table.h
os/net/routing/rpl-classic/rpl-nbr-policy.c
os/sys/process.c
tests/10-ipv6-nbr/nbr-multi-addrs/test.c
tests/13-ieee802154/code-6tisch/common.c

Latest version of cppcheck added some additional checks for missing consts, which this PR corrects.
* I noticed all the list libraries consistently avoid the suggested consts, so maybe there is a rationale I am missing
* I put nbr-table in a separate commit because 1) The semantic of several functions might become confusing: E.g. functions to lock, unlock, remove, etc. now take _only_ const parameters, 2) I am not sure if the `data` parameter in misc. nbr-table functions are intended to allow for modification, and 3) I myself added some missing consts not found by cppcheck
* Added commit 4e07c47f20057827bec40a916a49584027e2e161 from https://github.com/contiki-ng/contiki-ng/pull/1502 since that commit is ready, while the rest of the PR needs some more attention.
A quick test reveals a …

Add consts suggested by cppcheck

---

tools/docker/Dockerfile

Cooja does not require JAVA_HOME after
commit ee1d3d9ae4f6 so stop setting JAVA_HOME
in the dockerfile.

Dockerfile: do not set JAVA_HOME

---

examples/mqtt-client/Makefile
examples/platform-specific/cc26x0-cc13x0/base-demo/Makefile

This file should always exist, require
the include to succeed.

examples: fix identify target include

---

Makefile.include
arch/platform/jn516x/Makefile.jn516x

Remove the FINALIZE_DEPENDENCY part
of the build and replace it with GCC -MP.
It seems likely that the initial commit tried to get this
functionality, but resorted to using sed for some reason.

Use GCC to generate dependencies
