- examples/libs/energest/Makefile
- examples/libs/energest/example-energest.c
- examples/libs/energest/project-conf.h
- os/sys/energest.h
- tests/01-compile-base/Makefile
- tests/02-compile-arm-ports/Makefile
- tools/viewconf.c
* Added an example for Energest
* Added the energest example to regression compile tests
* Show Energest configuration in `viewconf`
> New Energest example

- arch/cpu/native/net/tun6-net.c
This allows a native platform application to run without network.
> Platform native: Avoid trying to use the tun when the tun is not available.

- os/contiki-main.c
I am pretty certain those includes don't need to be conditional. Let's ask travis :)
> Include headers unconditionally

- arch/cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
This change significantly improved the stability of our CC26xx nodes, in terms of number of reboots per device, especially under heavy RF traffic.
> CC26xx radio IEEE mode driver: limit the time spend in waiting for transmissions to finish

- arch/cpu/cc26xx-cc13xx/Makefile.cc26xx-cc13xx
- arch/cpu/cc26xx-cc13xx/cc13x0-cc26x0-cm3.h
This pull changes the CC13xx/CC26xx CPU to use the facilities of CMSIS.
> Use CMSIS with CC13xx/CC26xx

- examples/sensniff/README.md
Just a small doc improvement for Sensniff
> Clarify sensniff doc: It is also distributed as part of Contiki-NG

- os/net/ipv6/uipbuf.c
- os/net/ipv6/uipbuf.h
Added some documentation - some of which indicate feature that can be added (and is implemented in our code-base).
> uipbuf: added some documentation

- arch/platform/native/platform.c
- tests/01-compile-base/Makefile
> Compile platform native with NULLNET

- os/lib/list.c
- tests/07-simulation-base/code-data-structures/test-data-structures.c
This PR
* Fixes #254 
* Adds lists to the data structure unit test
* Tidies-up `list.c` a little bit
> Fix list_insert bug

- arch/cpu/cc26xx-cc13xx/rf-core/ieee-mode.c
> Correctly check against minumum RX frame length

- LICENSE.md
Change Contiki to Contiki-NG in `LICENSE.md`.
> Fix project name

- arch/platform/cc2538dk/contiki-conf.h
- arch/platform/nrf52dk/contiki-conf.h
- arch/platform/openmote-cc2538/contiki-conf.h
- arch/platform/srf06-cc26xx/contiki-conf.h
- arch/platform/zoul/contiki-conf.h
- examples/6tisch/etsi-plugtest-2017/sf-plugtest.c
- examples/multicast/root.c
- os/lib/heapmem.c
- os/net/app-layer/coap/coap-callback-api.c
- os/net/app-layer/coap/coap-uip.c
- os/net/app-layer/coap/coap.c
- os/net/ipv6/uip-nd6.c
- os/net/mac/tsch/tsch-log.c
- os/services/lwm2m/lwm2m-engine.c
- os/services/lwm2m/lwm2m-json.c
- os/services/lwm2m/lwm2m-security.c
- os/services/lwm2m/lwm2m-tlv.c
- os/storage/antelope/index.c
- os/storage/antelope/index.h
- os/storage/cfs/cfs-coffee.c
- os/sys/ctimer.c
Questions:
* I used PRIu64. Is this safe @nfi ?
* How do we deal with `size_t`, `clock_time_t`, `rtimer_time_t`?
The PR does not have 100% coverage, as I think this is very difficult to achieve. I believe this to be a good start.
> Use PRI macros for safe printf and logs

- arch/platform/zoul/dev/ac-dimmer.c
- arch/platform/zoul/dev/grove-gyro.c
- arch/platform/zoul/dev/motion-sensor.c
- arch/platform/zoul/dev/tsl256x.c
- arch/platform/zoul/dev/weather-meter.c
This pull migrates various Zoul sensor drivers to use the new GPIO HAL
> Use the GPIO HAL for Zoul sensor drivers

- README.md
As per #299, this pull proposes a more standalone README, rather than the current one which assumes that the reader is familiar with the original Contiki.
We also add some nice shields...
Closes #299
> Update README wording and add shields

- arch/platform/zoul/platform.c
- examples/6tisch/6p-packet/sixp-node.c
- examples/ipso-objects/example-ipso-objects.c
- examples/ipv6-hooks/ipv6-hooks.c
- examples/platform-specific/cc2538-common/mqtt-demo/mqtt-demo.c
- examples/platform-specific/nrf52dk/mqtt-demo/mqtt-demo.c
- examples/platform-specific/zoul/Makefile
- examples/platform-specific/zoul/at-test/Makefile
- examples/platform-specific/zoul/at-test/at-master-test.c
- examples/platform-specific/zoul/orion/ip64-router/Makefile.target
- examples/platform-specific/zoul/rev-b/Makefile.target
- os/storage/antelope/aql-lexer.c
- tests/03-compile-arm-ports-02/Makefile
Solves problems found with the `build-all.sh` script.
> Fix building of examples

- os/net/mac/tsch/tsch.c
> TSCH Keepalive loop fix

- arch/platform/cooja/sys/cooja-log.c
As discussed in https://github.com/contiki-ng/contiki-ng/issues/305
> Cooja motes: larger log buffer

- examples/multicast/project-conf.h
- examples/multicast/srf06-cc26xx/module-macros.h
Reduces ND cache and routing table size, reduce queuebuf number.
Fixes #463
> Fix the multicast example for sensortags

- Makefile.include
- os/net/ipv6/uip-ds6.c
Fixes a compilation warning ...
> Fix to uip-ds6.c

- arch/platform/jn516x/platform.c
- arch/platform/sky/platform.c
Somehow missed these in https://github.com/contiki-ng/contiki-ng/pull/533
> Remove left-over instances of WITH_TINYOS_AUTO_IDS

- tools/docker/Dockerfile
This PR adds `gdb` to `Dockerfile`.
> Dockerfile: add gdb

- os/services/shell/shell-commands.c
- os/services/shell/shell-commands.h
- os/services/shell/shell.c
Introduce shell command sets, as discussed on gitter.
> Dynamic shell command registration

- os/net/mac/tsch/tsch-schedule.c
This is just a small change that's pretty self explanatory.
> TSCH: improve the readability of add_link and remove_link messages

- arch/cpu/cc2538/dev/cc2538-rf.c
As  pointed out in https://github.com/contiki-ng/contiki-ng/pull/686#discussion_r224543867
> Add missing return statement

- arch/cpu/cc2538/cc2538-def.h
- arch/platform/cc2538dk/dev/board.h
- arch/platform/openmote-cc2538/board.h
- tests/01-compile-base/Makefile
- tests/02-compile-arm-ports-01/Makefile
- tests/03-compile-arm-ports-02/Makefile
> Fix TSCH on cc2528dk and openmote-cc2538

- os/net/app-layer/mqtt/mqtt.c
https://github.com/contiki-ng/contiki-ng/issues/600 reports an a potential MQTT buffer overflow. This PR is an attempt to fix it; I would like someone more familiar with MQTT to double-check and ideally test.
Fixes #600
> MQTT buffer overflow fix

- tests/07-simulation-base/23-rpl-tsch-z1.csc
Worth further investigation when there is more time. For now this PR removes the one node that's misbehaving, in order to allow other valid PRs to be merged.
> 23-rpl-tsch-z1.csc - remove one node that does not like to be routed

- os/net/nbr-table.c
Fixes https://github.com/contiki-ng/contiki-ng/issues/789
> Check that table is non-NULL in nbr_table_add_lladdr

- os/net/mac/tsch/tsch-slot-operation.c
> TSCH: filter out frames from ourselves

- os/net/routing/rpl-classic/rpl-dag.c
I'm pretty certain the diff is self-explanatory :)
> Improve RPL logging output

- examples/libs/stack-check/example-stack-check.c
- os/sys/stack-check.c
- os/sys/stack-check.h
Changed function return value type from `uint16_t` to `int32_t`.
> Stack check: support for >64kb of RAM

- os/net/mac/tsch/tsch.c
Repost of #942 (git hub closed it!)
> Reduce noise on TSCH joining

- os/sys/rtimer.h
This pull-request re-organizes the structure and documentation of rtimer.h:
- API doc for `rtimer_set` is updated to match the current implementation. It was out of date, I think.
- Configuration macros are put together at the top of the header.
- Functions that must be defined in architecture-specific source files are put together at the bottom.
- Some platforms (e.g. `native`) define those symbols as macros, so the function declaration is now conditinal (just like gpio-hal.h).
- Add documentation on macros that must be defined in rtimer-arch.h
I don't have any idea how I should describe `RTIMER_ERR_` constants, so I added a TODO comment to them.
BTW, [the usage example of rtimer in Wiki](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Timers#the-rtimer-library) is out of …
> Re-organize structure and documentation of rtimer.h

- os/net/routing/rpl-lite/rpl-dag.c
> Fix location of misleading comment

- tests/17-tun-rpl-br/test-border-router.sh
- tests/17-tun-rpl-br/test-native-border-router.sh
Will hopefully mitigate the flakiness of some of the Travis tests
> Ping tests: tolerate losses

- arch/platform/zoul/dev/mmc-arch.c
> Fix for the SD/MMC driver of Zolertia RE-Mote

- os/dev/serial-line.c
This adds one of the commits of https://github.com/contiki-ng/contiki-ng/pull/497 , which adds support for both CR and LF in the shell.
> Cherry-pick from https://github.com/contiki-ng/contiki-ng/pull/497

- arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
> Improve read_frame and pending_packet consistency in the cc13x0 prop mode driver

- README.md
This adds a new badge with the docs build status on readthedocs to `README.md`
> Add readthedocs status badge

- os/lib/ringbufindex.c
- os/net/ipv6/sicslowpan.c
- os/net/routing/rpl-classic/rpl-dag-root.c
- os/net/routing/rpl-lite/rpl-neighbor.c
Minor fixes which seem too trivial for separate PRs...
> Minor fixes under "os"

- examples/mqtt-client/mqtt-client.c
- os/net/ipv6/uip-icmp6.c
See Issue #1136 for details. 
@g-oikonomou Can you confirm this fix works on your side? I did a test using the `.csc` files attached to Issue #1136 .
> Fix Issue #1136 (issue of mqtt-client example + rpl-lite)

- os/net/mac/tsch/tsch-timeslot-timing.c
A documentation improvement. This is based on the initial work by Rajeev Pinare.
> Add TSCH timeslot element description

- arch/platform/cooja/dev/cooja-radio.c
* Add radio energest level tracking to Cooja motes
* Fix random init for cooja motes so that each mote gets a different random seed
> Cooja mote improvements

- examples/6tisch/custom-schedule/node.c
- examples/6tisch/etsi-plugtest-2017/sf-plugtest.c
- examples/6tisch/simple-node/Makefile
- examples/6tisch/sixtop/sf-simple.c
- os/net/mac/tsch/tsch-schedule.c
- os/net/mac/tsch/tsch-schedule.h
- os/net/mac/tsch/tsch.c
- os/services/orchestra/orchestra-conf.h
- os/services/orchestra/orchestra-rule-default-common.c
- os/services/orchestra/orchestra-rule-eb-per-time-source.c
- os/services/orchestra/orchestra-rule-unicast-link-based.c
- os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-ns.c
- os/services/orchestra/orchestra.h
- tests/07-simulation-base/24-cooja-rpl-tsch-orchestra-storing.csc
- tests/07-simulation-base/25-cooja-rpl-tsch-orchestra-link-based.csc
The Orchestra link-based rule has been designed based on the insights from:
1) An Empirical Survey of Autonomous Scheduling Methods for TSCH, Atis Elsts, Seohyang Kim, Hyung-Sin Kim, Chongkwon Kim, IEEE Access, 2020.
2) ALICE: autonomous link-based cell scheduling for TSCH, Seohyang Kim, Hyung-Sin Kim, Chongkwon Kim, IEEE Access, ACM/IEEE IPSN, 2019.
It potentially offers higher performance (better energy/reliability tradeoff) compared to the other Orchestra rules, especially for applications where both upstream and downstream traffic is frequent.
> Link based Orchestra rule

- examples/6tisch/6p-packet/sixp-node.c
- examples/6tisch/etsi-plugtest-2017/sf-plugtest.c
- examples/6tisch/sixtop/node-sixtop.c
- os/net/mac/tsch/tsch-queue.c
- os/net/mac/tsch/tsch-queue.h
- os/net/mac/tsch/tsch-slot-operation.c
- os/net/mac/tsch/tsch-types.h
- os/net/mac/tsch/tsch.c
- os/services/orchestra/orchestra-rule-eb-per-time-source.c
- os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-storing.c
- os/services/shell/shell-commands.c
- tests/13-ieee802154/code-6tisch/project-conf.h
- tests/13-ieee802154/code-6tisch/test-sixp-nbr.c
Reduces memory usage and partially fixes #1054 .
> Move TSCH neighbors to a neighbor table

- os/net/ipv6/uip-ds6-route.c
- os/net/mac/tsch/tsch-packet.c
- os/net/mac/tsch/tsch.c
- os/net/routing/rpl-classic/rpl-dag.c
- os/net/routing/rpl-classic/rpl-icmp6.c
- os/net/routing/rpl-classic/rpl-of0.c
- os/services/orchestra/orchestra-conf.h
- os/services/orchestra/orchestra.c
I have been doing some sims. lately and came across some minor issues which was annoying/confusing/actual bugs. I don't believe they deserve separate PRs so I added everything here and I'll just remove the commits people don't like.
> Misc. minor fixes for mac/routing/ipv6

- os/contiki-main.c
> Log platform and board name at startup

- os/net/app-layer/mqtt/mqtt.c
- tests/02-compile-arm-ports/Makefile
> Fix uninitialised variable errors under MQTT 5

- os/net/app-layer/mqtt/mqtt.c
Properties were not written out for outgoing UNSUBSCRIBE messages as described in section 3.10.2 of the specification (https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901181). These malformed packets caused mosquitto to close the TCP connection. See my issue reported in the mosquitto repository: https://github.com/eclipse/mosquitto/issues/1765
I have added the missing lines. Works fine for me now.
> [MQTT5] Write out properties of unsubscribe messages

- os/net/mac/tsch/tsch-slot-operation.c
This fixes situation where a backed-off link never activates, due to being hidden by other links.
The scenario of the bug:
1) have pair of links on same slot configuration:
- linkA - tx|shared at slot1
- linkB - rx at slot1
2) linkA have interference, and therefore fails to transmit. backoff window is increased.
3) now, every time linkB is chosen over linkA. So linkA never updates its backoff
> TSCH: also update backoff for Tx links that are overlapped by Rx links

- os/net/mac/tsch/tsch.c
- os/services/orchestra/orchestra-rule-default-common.c
- os/services/orchestra/orchestra-rule-eb-per-time-source.c
- os/services/orchestra/orchestra-rule-unicast-link-based.c
- os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-ns.c
- os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-storing.c
- os/services/orchestra/orchestra.c
- os/services/orchestra/orchestra.h
Additions:
* log slotframe sizes when initializing Orchestra;
* log the reason why EB packet is not generated.
> TCSH: improve TSCH and Orchestra logging

- arch/platform/z1/contiki-conf.h
- tests/07-simulation-base/23-rpl-tsch-z1.csc
> TSCH: disable HW frame filtering for cc2420 radios

- os/net/app-layer/snmp/snmp-ber.c
- os/net/app-layer/snmp/snmp-message.c
#1355 introduces code style errors. This PR fixes them
> Fix SNMP code style

- .github/workflows/build.yml
Fixes https://github.com/contiki-ng/contiki-ng/issues/1424
> Only run docker push if we just built a new image

- arch/cpu/cc2538/dev/cc2538-rf.c
Just a small tidy-up of the cc2538 radio driver
Requires #1422
> Tidy-up CC2538 SHR search handling

- os/dev/radio.h
This pull-request fixes some errors in the documentation of os/dev/radio.h
> dev/radio.h: fix some documentation

- tools/vagrant/README.md
Change "fonud" to "found" if that's not intentional.
> Fix typo in README

- tools/serial-io/tunslip6.c
Apple has been moving away from kernel extensions, and tuntaposx (which tunslip6 currently relies on under macOS) is inactive and not functional on M1 hardware.
This makes running tunslip6 on new macOS versions challenging (or impossible on M1).
This PR drops TAP support on macOS and switches tunslip6 over to Apple's own tun implementation (utun). 
The default interface (if not specified) is set somewhat arbitrarily to `utun10`, as `utun0` to `utun3` seem to be in use by the OS on my machine.
Tested on Big Sur on M1.
> tunslip6: utun interface support on macOS

- arch/cpu/cc26x0-cc13x0/clock.c
As in title. Tested on custom cc1310. Inspired by simplelink arch.
> Minor optimize cc26x0-cc13x0 clock arch

- arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-def.h
- arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
- arch/cpu/cc26x0-cc13x0/rf-core/rf-core.c
- arch/cpu/cc26x0-cc13x0/rf-core/rf-core.h
This adds a number of commits that should improve the reliability of CC13xx radios.
Related to #1432 and #1401.
Pinging @lili1218 @alexrayne @rajeev1986
> CC13xx radio fixes

- arch/cpu/cc26x0-cc13x0/rf-core/ble-hal/ble-hal-cc26xx.c
- arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
- os/sys/stack-check.c
A subset of the fixes in https://github.com/contiki-ng/contiki-ng/pull/1502
> Misc code analysis fixes subset

- os/lib/hexconv.c
That one has bothered me for a while but somehow never took time to do the PR :)
> Fix hexconv_hexlify()

- os/net/ipv6/sicslowpan.c
A uip_udp_hdr pointer is cast to ip_payload before checking that it is within the buffer. This PR adds a check to see if there is enough space available from the current offset to fit a full UDP header in the buffer.
> sicslowpan: Check whether the buffer has room for a UDP header

- os/services/simple-energest/simple-energest.c
This also solves a compile issue on 64 bit systems.
> Updated simple-energest to use 64 bit values (same as energest)

- arch/cpu/msp430/Makefile.msp430
- arch/platform/cooja/Makefile.cooja
- tests/17-tun-rpl-br/Makefile
- tests/Makefile.simulation-test
Ensure the cd to the cooja directory
is successful before calling ant.
> tests: ensure Cooja is built

- examples/rpl-border-router/README.md
This is re-upload of PR #1638 due to CI issues.
> Add Markdown code format to file names

- tests/06-script-base/04-test-result-visualization.sh
The call to exit needs a natural value
as argument, change -1 to 1.
> tests: exit with legal value

- tools/git/update-submodule.sh
This script adds a list of the commits
and their titles to the commit message
of the submodule update.
> Add submodule update script

- examples/benchmarks/result-visualization/run-analysis.py
Small improvements in the output and code, including a change that replaces a parameter name obsoleted in newer versions of Python.
> improve result visualization example

- .github/workflows/build.yml
Some submodules contain lfs binaries, like CMSIS's libraries.
> Added lfs to github action

- examples/libs/unit-tests/js/ut-runner.js
The example shows how to produce a failure,
so as a whole, the test passes.
> Fix logic in unit-tests test

- os/net/mac/tsch/tsch-slot-operation.c
**The problem:** TSCH joining speed is inversely proportional to the number of channels to scan. If a large number of channels is used (for example 64, which might be needed due to regulatory limitations in sub-GHZ operation) then joining can be very slow. Configuring a join hopping sequence with a smaller number of channels does not help as EB packets are still sent out using the full channel hopping sequence.
**The solution:** if a custom joining sequence is defined, only send out EB packets using channels in that joining sequence.
This only affects networks with custom configuration: the default behavior is not changed.
When comparing the simple-node example with custom configuration (number of channels = 16, numbrer of join channels = 2) there is a marked improvement in speed. After …
> TSCH: speed up joining when a custom join hopping sequence is defined

- tools/docker/Dockerfile
This is a combination of the patches
by George Oikonomou and Niclas Finne
with some minor tweaks.
> Dockerfile: update to 64-bit Ubuntu 18.04

- .github/workflows/build.yml
> CI: update actions/checkout version

- tools/vagrant/bootstrap.sh
This reduces the differences between Vagrant and Docker.
> Align Vagrant with Docker

- os/net/ipv6/simple-udp.h
- os/net/ipv6/uip-ds6-nbr.h
- os/net/ipv6/uip-sr.h
- os/net/ipv6/uip.h
Remove a word and fix some formatting.
> ipv6: doxygen fixes

- Makefile.include
The compilation tests pass so this might
not be an issue any longer.
> Makefile: enable -Wunused-const-variable

- arch/platform/cc26x0-cc13x0/platform.c
- arch/platform/simplelink/cc13xx-cc26xx/platform.c
Some very minor logging fixes found during testing for release.
> Minor logging fixes on TI platforms

- Makefile.include
Add the CONTIKI_PROJECT-related dependency
files to DEPFILES.
> Makefile: add more DEPFILES

- os/lib/dbg-io/putchar.c
- os/lib/dbg-io/puts.c
This saves a couple of bytes on MSP430.
> dbg-io: simplify code

- doc/programming/Packet-buffers.md
- doc/programming/UDP-communication.md
- doc/project/More-about-Contiki-NG.md
> Update outdated doxygen links

- arch/cpu/msp430/Makefile.msp430
Use the MSPSim in the Cooja repository.
> msp430: update for new MSPSim location

- os/lib/heapmem.c
- os/lib/heapmem.h
- tests/08-native-runs/12-heapmem/test-heapmem.c
This PR also adds a function to check the alignment used by the heapmem module.
> Test HeapMem alignment

- arch/platform/cooja/mtype.c
Put the functionality of the JNI functions
in their own funtions and call the new functions
from the JNI functions. This is one step towards
removing the dependency on JNI.
> cooja: make JNI-functions thin wrappers

- os/net/ipv6/uip-ds6.c
- os/net/ipv6/uip-ds6.h
This PR comprises an improvement and a fix relating to stateless address autoconfiguration.
> uip: an improvement and a fix

- doc/getting-started/Docker.md
- doc/platforms/cooja.md
- doc/tutorials/Running-Contiki-NG-in-Cooja.md
Update for Gradle. Also remove the 32-bit comments, and remove the language about Cooja motes only
working on Linux.
> doc: update Cooja documentation

- tests/07-simulation-base/21-cooja-rpl-tsch-security.csc
This test fails intermittently, increase the timeout to see if that fixes the problem.
> tests: increase timeout

- arch/platform/zoul/fs/fat/diskio.c
Convert the values from one enum to
the other.
> zoul: remove implicit enum conversion

- os/net/routing/rpl-classic/rpl-dag.c
> Don't send DAO when in MOP 0

- tests/Makefile.simulation-test
Time for 07-simulation-base before:
real 116.79
user 25.92
sys 3.22
Time for 07-simulation-base after:
real 66.46
user 1.46
sys 0.15
Time for 17-tun-rpl-br before:
real 563.27
user 9.24
sys 1.29
Time for 17-tun-rpl-br after:
real 556.57
user 2.96
sys 0.69
> tests: run sim tests in single JVM

- os/net/mac/ble/ble-l2cap.c
Thanks to Simon Wörner (@SWW13) for reporting the problem.
> Check available packetbuf space before writing to it in ble-l2cap

- os/net/mac/ble/ble-l2cap.c
Thanks to Tobias Scharnowski for reporting the problem.
> Add missing NULL check in ble-l2cap

- .github/workflows/build.yml
- tools/docker/Dockerfile
And fix the build by using SourceForge for Doxygen.
> Update to ccache v4.7.2

- os/lib/list.c
- os/lib/list.h
> Move function comments from list.c to list.h

- arch/cpu/nrf/nrfx_config_nrf5340_application.h
This is the file from the nrfx templates,
except the addition+use of the NRF_PERIPH
macro.
Cherry-picked from a commit by John Kanwar.
> nrf: import nrf5340 nrfx config

- doc/project/Where-to-report-issues,-ask-questions,-etc.md
Useful for cases such as https://github.com/contiki-ng/contiki-ng/issues/2363
> Mention in doc. that github issues should be in english language only

- doc/Home.md
Make an (imperfect) easy-to-difficult order of tutorials within each category, based on student feedback.
> Rearranged the tutorial order in docs

- os/net/ipv6/uip-ds6-route.c
- os/net/ipv6/uip6.c
- os/net/mac/tsch/tsch-schedule.c
- os/net/routing/routing.h
- os/net/routing/rpl-classic/rpl-dag.c
- os/net/routing/rpl-classic/rpl-mrhof.c
A small set of minor fixes in RPL, TSCH, uip6.
> Minor code-style, logging, comments in RPL, TSCH, uIP

- arch/cpu/nrf/Makefile.nrf
Added new dependency to nrfx_flag32_allocator.c
> Bumped nrfx from v2.5.0 to v2.10.0

- os/services/shell/shell-commands.c
Thanks to Guy Farrelly for reporting the problem.
> Check whether shell command line arguments have been provided.

- examples/rpl-udp/README.md
- examples/rpl-udp/rpl-udp.robot
- examples/rpl-udp/udp-client.c
- tests/06-script-base/05-test-renode.sh
- tools/docker/Dockerfile
A test that uses Renode for testing firmware compiled for cc2538dk in emulation.
It uses the robot framework for scripting the test and is integration into the script-tests of Contiki-NG's test suite.
> Renode robot test

- doc/getting-started/Docker.md
Adding a warning for #2315 - to avoid other installs of docker than the one in the instructions.
> added NOTE on version of docker to use

- doc/project/Release-Notes-next.md
As in title. Gentle ping @atiselsts as it stems from #1673
> Orchestra default channel change release note

- doc/getting-started/Toolchain-installation-on-Linux.md
- tools/toolchain/msp430/buildmsp.sh
Revised PR for updating the script for building msp430 from source. This revised PR only includes the script and reference to it in the toolchain documentation.
> update script for building msp430 from source

- doc/tutorials/Hello,-World!.md
It is only sky/z1 that has the motelist target,
but all targets has the motelist-all target.
> doc: fix motelist target

- .github/workflows/build.yml
- tools/docker/Dockerfile
This also updates the Dockerfile
to use GraalVM 20.0.1.
Commits:
fc2fb9886 Bump info.picocli:picocli-codegen from 4.7.4 to 4.7.5
32769a0d7 Bump info.picocli:picocli from 4.7.4 to 4.7.5
e15743888 Update to Java 20
> Update tools/cooja submodule

- os/net/mac/framer/frame802154.c
Simplify an assignment and change an index type to save 20+ bytes on MSP430.
> frame802154: tweak for size savings

- os/net/routing/rpl-lite/rpl-icmp6.c
Use ?: in a couple of places to reduce the code size.
> rpl-icmp6: reduce code size

- os/net/routing/rpl-lite/rpl-timers.c
- os/net/routing/rpl-lite/rpl-timers.h
- os/net/routing/rpl-lite/rpl.h
This saves 12 bytes on MSP430.
> rpl-timers: inline rpl_timers_unschedule_state_update

- os/net/ipv6/sicslowpan.c
This PR solves a TODO in `sicslowpan.c`, namely that the lookup of compression contexts happens twice.
> 6LoWPAN: Avoid double context lookups

- .devcontainer/devcontainer.json
More information about this feature: https://github.com/features/codespaces
> Setup github codespaces using contiker

- os/sys/autostart.c
This reverts commit 9c0184eb9c4cf7f76102153ab9c4adf116539f58.
> Revert "autostart: make functions static inline"

- os/lib/ccm-star.c
- os/lib/ccm-star.h
This PR fixes style issues in `ccm-star.ch`.
> CCM*: Style fixes in software implementation

- os/net/ipv6/sicslowpan.h
This has been commented out since commit 4bc60d76d3 in 2009.
> sicslowpan: remove commented out code

- .github/workflows/codeql.yml
Allow the workflow to be triggered by pressing
a button.
> CodeQL: add manual button for trigger

- os/net/ipv6/multicast/mpl.c
- os/net/ipv6/tcp-socket.c
- os/net/ipv6/tcpip.c
- os/net/ipv6/uip-ds6.c
- os/net/ipv6/uip-nd6.c
- os/net/mac/framer/frame802154.c
- os/net/routing/rpl-classic/rpl-icmp6.c
- os/net/routing/rpl-lite/rpl-icmp6.c
Some code entered the tree as commented out. Most of the removed code has been commented out for a decade or more.
> os/net: remove commented out code

- doc/project/Code-style.md
This PR extends the code style document with an introductory text and a new section on standard compliance.
> Extend code style document

- os/net/ipv6/uip6.c
- os/net/ipv6/uipopt.h
This change concerns mostly the uipopt.h file.
> Update some uIP documentation

- tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
- tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh
- tests/18-coap-lwm2m/pytests/test-device.py
Just a quick test for updating the leshan jar file to the latest one - supporting DTLS and the latest features.
> replaced leshan jar for better DTLS testing support

- os/net/app-layer/coap/coap.c
The CoAP message parsing code is currently checking the boundary of options even when an option will not be read, causing an invalid decision to report that some messages are too small.
This PR introduces a macro for option boundary checking, and puts it only immediately before the statement that reads the option byte.
> Fix CoAP option boundary checking.

- .github/workflows/codeql.yml
This solves an issue with installing `git-lfs`.
> CI: update repositories before installation
