- Makefile.include
The current behavior of "make clean" and
several other targets that use rm is to proceed
even if the removal failed, and eventually
return 0. This patch makes make fail and return
a non-zero exit code when rm fails, for example
if the user doesn't have permissions to remove
files/directories:
examples/hello-world$ make clean
TARGET not defined, using target 'native'
rm: cannot remove 'build/native/hello-world.native': Permission denied
rm: cannot remove 'build/native/contiki-ng-native.a': Permission denied
rm: cannot remove 'build/native/obj': Permission denied
make: *** [../../Makefile.include:358: clean] Error 1
examples/hello-world$ echo $?
2
Stopping on failure is important for reproducible
regression tests.
> Makefile: stop when rm fails

- arch/platform/sky/dev/sky-sensors.c
- arch/platform/z1/dev/sky-sensors.c
This definition exists in the header files in both gcc 4.7.2 and gcc 9.3.1. Additionally, the definition in the header files is volatile.
> sky-sensors: use ADC12MCTL from SDK

- Makefile.include
This allows targets to override the cp
command. This will enable more rule
sharing for Cooja.
> Makefile: use $(CP) to copy files

- os/net/ipv6/simple-udp.c
- os/net/ipv6/simple-udp.h
fixes issue #1510 
In simple_udp_register(), the client process is never set, this PR fixes this.
> simple-udp: set the client process at registration

- arch/cpu/native/dev/eeprom.c
- arch/platform/cooja/dev/eeprom.c
- os/dev/eeprom.h
Added more error checks and switched to using return values to notify users of errors rather than calling abort()/exit(). Also modernized the code for Contiki-NG and improved the log output.
> Improved EEPROM error checking.

- tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
- tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh
- tests/18-coap-lwm2m/08-lwm2m-qmode-ipso-test.sh
- tests/18-coap-lwm2m/09-lwm2m-qmode-standalone-test.sh
Put sleep statements on the line before
the thing that needs a delay to happen.
This uncovered a couple of sleep statements
that were not needed.
Also consolidate the separate calls to rm into
a single call to shorten the test scripts and
avoid some forking.
> tests: sleep less

- arch/platform/cooja/Makefile.cooja
- arch/platform/cooja/Makefile.customrules-cooja
IMPORTANT: Merge after #1857 to preserve behavior on OS X.
The build commands executed by Cooja are
identical to the build commands executed
by the native platform. Stop overriding
the target library rule and use the existing
rule instead.
Also remove some dead, commented out, and
always true defines.
> cooja: do not override archive lib rule

- arch/platform/jn516x/Makefile.jn516x
The only target that has cygwin hacks
is jn516x, these hacks are either unused
or should be required for more targets.
Remove the hacks to enable more of the
build system to be shared in the future.
> jn516x: remove cygwin support

- arch/cpu/msp430/f1xxx/msp430.c
- arch/cpu/msp430/f2xxx/msp430.c
- arch/cpu/msp430/f5xxx/msp430.c
The assembler in GCC 9 complains about
a missing nop after interrupt state
changes. Add the nop.
> msp430: add nop in splhigh_()

- os/net/mac/csma/csma-security.c
When using link layer security on "non-TSCH" mode (e.g. cc1352 prop mode) packets are secured and decrypted, but unsecure communication is allowed.
Issue 1 in #1610 states:
in csma_security_parse_frame() unsecure frames are not dropped:
if(packetbuf_attr(PACKETBUF_ATTR_SECURITY_LEVEL) == 0) { /* No security - no more processing required */ return hdr_len; }
This should result in a FRAMER_FAILED instead.
Code has been modified with a #define to opt to reject insecure packets, or leave as the original contiki-ng default. 
#ifdef LLSEC802154_REJECT_INSECURE
return FRAMER_FAILED;
#else
/* No security - no more processing required */
return hdr_len;
#endif
> Reject unencrypted frames in csma_security_parse_frame() (Issue 1610)

- tests/Makefile.compile-test
Restrict the number of CPUs that make
can use in the compile tests.
This avoids forking 30+ compilers at
the same time which made a significant
difference in how long the CI simulation
tests that runs on a 2-core machine took.
> tests: limit compiler parallelism

- os/net/ipv6/uipbuf.h
Issue 2 in #1610 states:
The first DIO message is sent without security.
This will allow a unsecure node picking up the DIO and joining un-securely because of the first issue.
this is because output() in sicslowpan.c sets security level to 0 first time for some reason.
An optional initial security level can be provided  (UIPBUF_ATTR_LLSEC_STARTUP_LEVEL). It non is given the previous behaviour remains (#define UIPBUF_ATTR_LLSEC_LEVEL_MAC_DEFAULT               0xffff).
> Add option to set the initial security level

- Makefile.include
Make the link rule output to $(LIBNAME) and
set $(LIBNAME) to $@ which was the previous
output name.
The "interface" of passing target names through
an environment variable like Cooja does is not
ideal, but revising that interface will be less
cumbersome when the responsibility of the build
system belongs to Contiki-NG and Cooja is a regular
caller.
This commit does not change any visible behavior
for any platform. The purpose is to prepare for
making Cooja use the same build rules as other
platforms.
> Makefile: adjust link rule for Cooja compat

- arch/cpu/native/Makefile.native
The rule for building shared libraries
seem to be unused so remove it.
The rule looks like a standard formulation
for shared libraries so it probably belongs
in Makefile.include if we need it.
> native: remove unused build rule

- examples/6tisch/6p-packet/6p-packet.csc
- examples/6tisch/custom-schedule/cooja.csc
- examples/6tisch/etsi-plugtest-2017/test-with-cooja-mote.csc
- examples/6tisch/simple-node/rpl-tsch-cooja.csc
- examples/6tisch/sixtop/rpl-tsch-sixtop-cooja.csc
- examples/benchmarks/result-visualization/cooja.csc
- examples/benchmarks/rpl-req-resp/sim.csc
- examples/libs/deployment/sim.csc
- examples/libs/ipv6-uipbuf/ipv6-uipbuf-cooja.csc
- examples/libs/ipv6-uipbuf/ipv6-uipbuf-sky.csc
- examples/libs/stack-check/example-sky.csc
- examples/libs/trickle-library/trickle-library.csc
- examples/nullnet/nullnet-broadcast.csc
- examples/nullnet/nullnet-unicast.csc
- examples/rpl-udp/rpl-udp-cooja.csc
- examples/rpl-udp/rpl-udp-sky.csc
- tests/06-script-base/code-result-visualization/00-result-visualization.csc
- tests/09-ipv6/01-ping-lla-csma-w-rpl.csc
- tests/09-ipv6/02-ping-ula-csma-w-rpl.csc
- tests/09-ipv6/03-ping-lla-tsch-w-rpl.csc
- tests/09-ipv6/04-ping-ula-tsch-w-rpl.csc
- tests/09-ipv6/05-ping-lla-csma-wo-rpl.csc
- tests/09-ipv6/06-ping-ula-csma-wo-rpl.csc
- tests/09-ipv6/07-ping-lla-tsch-wo-rpl.csc
- tests/09-ipv6/08-ping-ula-tsch-wo-rpl.csc
- tests/09-ipv6/09-ping-lla-ula-csma-w-rpl.csc
- tests/09-ipv6/10-ping-lla-ula-tsch-w-rpl.csc
- tests/09-ipv6/11-ping-lla-ula-csma-wo-rpl.csc
- tests/09-ipv6/12-ping-lla-ula-tsch-wo-rpl.csc
Add -j$(CPUS) to the Cooja make commands to speed up
builds.
Discovered that some tests clean for the wrong
TARGET while changing these files, so fix that
at the same time.
The tests all make clean to ensure there is nothing
laying around in the build tree from earlier tests,
and the example result-visualization is used by
the tests so add a make clean in that file.
> tests/examples: fix TARGET for clean and add -j

- os/lib/dbg-io/strformat.h
The format_str function declared just before
this function has the attribute so add it
to format_str_v for consistency. The GCC
documentation explicitly mentions using 0
as the third argument to the format attribute
for va_list functions such as vprintf.
The attribute does not change code generation,
it just informs the compiler that -Wformat checking
should be applied to the arguments of the function.
> dbg-io: add format attribute to format_str_v

- tools/coffee-manager/build.xml
The jar target depends on the compile target, but
the faulty srcdir on the compile target makes
the jar target infer the files it needs and recompiles
them.
> Fix coffee-manager build srcdir

- Makefile.include
- arch/platform/cooja/Makefile.cooja
Allow the platforms to specify makefiles that
should be included and give an error message when
the include fails.
> cooja: detect missing Makefile.customrules-cooja

- tools/docker/Dockerfile
More detailed numbers below, but ccache
gets a 99.99% hitrate when running the three
first test suites under tests/ with a warm
cache. The high hitrate halves the time it
takes to complete the tests on my computer.
time -p (cd 01-compile-base/ && make && cd ../02-compile-arm-ports/ && make && cd ../04-compile-nxp-ports/ && make)
Time without ccache:
real 157.10
user 820.20
sys 116.13
Time for first run on empty cache:
real 170.16
user 947.49
sys 182.50
Cache statistics after first run:
cache hit (direct)                     1
cache hit (preprocessed)            2682
cache miss                         13575
cache hit rate                     16.50 %
cleanups performed                     0
files in cache                     43371
cache size                         273.1 MB
Time for second …
> Dockerfile: install ccache

- arch/cpu/arm/cortex-m/Makefile.cortex-m
This is needed for submodules that provide their own CMSIS
> Allowed overriding of CMSIS_PATH

- examples/libs/unit-tests/code-unittests/test-examples.c
- os/services/unit-test/unit-test.c
- os/services/unit-test/unit-test.h
- tests/07-simulation-base/code-data-structures/test-data-structures.c
- tests/07-simulation-base/code-ringbufindex/test-ringbufindex.c
- tests/08-native-runs/12-heapmem/test-heapmem.c
- tests/10-ipv6-nbr/nbr-multi-addrs/test.c
- tests/13-ieee802154/code-6tisch/common.c
- tests/13-ieee802154/code-flush-nbr-queue/common.c
- tests/13-ieee802154/code-panid-handling/test-panid-handling.c
A few minor changes of the unit test module, including
1. Update the comments.
2. Switch unit test result type to boolean.
3. Switch timer to clock_t to avoid wrapping rtimer values.
4. Report the number of assertions executed in a unit test.
> Improvements of the unit test library

- examples/libs/unit-tests/00-unit-tests.csc
This example is called from the regression
tests and they need to be reproducible, add
a make clean. Also add -j$(CPUS) to get some
speedup over sequential execution.
> examples: add clean + -j to unit-tests

- tests/02-compile-arm-ports/Makefile
Having the test in the compilation suite
results in multiple ant invocations that
create cooja.jar at the same time. This
gives strange error messages about truncated
zip files and manifests.
Remove the test from the arm compilation testsuite
for now, simulation tests should be in 07-simulation-base.
> tests: disable the unit-test example

- Makefile.include
- arch/platform/cooja/Makefile.cooja
Filter out files that do not work
on the platform.
This discovered that slip.c is added
by Makefile.cooja and Makefile.include
so remove it from Makefile.cooja.
> cooja: only build used modules

- os/lib/dbg-io/strformat.c
Fix definition of LARGEST_SIGNED for
systems without long long.
Also switch POINTER_INT to use the
C99 uintptr_t.
> dbg-io: fix int definitions

- arch/cpu/arm/cortex-m/Makefile.cortex-m
- arch/cpu/nrf52832/Makefile.nrf52832
- arch/platform/jn516x/Makefile.jn516x
The mapfile is only used by Cooja and MSPSim in Contiki-NG nowadays.
> Remove unused map flags

- tests/17-tun-rpl-br/Makefile
The tests depend on cooja.jar so make
sure the file is built before starting
the tests.
This should not be the root cause of the
intermittently failing CI tests, but
this patch removes one source of
non-determinism.
> tests: build Cooja first in tun-rpl-br

- arch/platform/native/Makefile.native
- tests/08-native-runs/13-coffee.sh
- tests/08-native-runs/13-coffee/Makefile
- tests/08-native-runs/13-coffee/test-coffee.c
This test is based on the old test for Coffee in Contiki, but it is updated to use the unit-test module. Additionally, we make it possible to configure which CFS back end to use on the native platform, rather than always compiling with cfs-posix.
> Add a Coffee test

- arch/cpu/arm/cortex-m/Makefile.cortex-m
The linker parameter --cref prints things
to the map file if that is generated. Remove
the flag now since it goes to stdout without
mapfile.
This change belonged in commit db8c04e6c85d.
> cortex-m: remove mapfile leftovers

- tools/serial-io/tunslip6.c
Print the errno relating to the failed
connect rather than the (potential) errno
from close. If close succeeded, errno is
undefined.
> tunslip6: print connection error info

- os/net/mac/tsch/tsch.c
The problem is that not only the scanning consumes 100% radio at the moment, but also 100% CPU because timers can be added with zero timeout on some platforms, and also potentially in the past (due to `etimer_reset` behavior). This PR aims to reduce that.
> TSCH scanning: limit the etimer frequency to 1/CLOCK_SECOND to reduce CPU usage during the scanning

- tools/docker/Dockerfile
The plugdev group is mentioned on
the Toolchain installation for Linux
on the wiki so add the docker user
to that group.
> Dockerfile: add user to plugdev group

- tools/docker/Dockerfile
Many Contiki-NG users are outside the US,
switch the packages to be downloaded from
a mirror that is closer to the user.
> Dockerfile: use nearby mirrors for packages

- tools/docker/Dockerfile
- tools/docker/files/cooja
as per discussion in issue #1497 and contribution from @pjonsson :
- new version of cooja script which periodically prints an invisible character to keep windows docker from terminating the session for inactivity
- script copied from docker file to avoid echo'ing ~500 characters
> Fix cooja windows closing after few minutes #1497

- examples/benchmarks/result-visualization/README.md
- examples/benchmarks/result-visualization/run-cooja.py
- tests/10-ipv6-nbr/01-test-nbr-multi-addrs.sh
- tests/17-tun-rpl-br/04-border-router-traceroute.sh
- tests/17-tun-rpl-br/test-border-router.sh
- tests/17-tun-rpl-br/test-native-border-router.sh
- tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
- tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh
- tests/18-coap-lwm2m/08-lwm2m-qmode-ipso-test.sh
- tests/18-coap-lwm2m/09-lwm2m-qmode-standalone-test.sh
- tests/Makefile.script-test
- tests/Makefile.simulation-test
- tests/simexec.sh
This depends on: https://github.com/contiki-ng/cooja/pull/131, https://github.com/contiki-ng/cooja/pull/129 and one more patch on top of those.
Remove the knowledge of Cooja build system
from Contiki-NG and just call ant on the run
target in Cooja instead.
This ensures that Cooja is rebuilt when
the sources have been updated.
Also reduce the number of calls to rm while
I'm touching these files.
> tests: use Cooja build file

- os/net/ipv6/multicast/mpl.c
- os/net/ipv6/multicast/mpl.h
This fixes the issue described in #1700 where the multicast address flags are not correctly masked off from the scope when handling MPL domain addresses.
Currently the only multicast addresses that MPL will work with are addresses where the flags are set to zero. These addresses are meant to be reserved for well-known multicast addresses, so it forces users who want to dynamically assign a multicast group, to use an address space that is not intended to be used for dynamically assigned addresses.
Also included are a few code style issues picked up by `uncrustify` when checking the changes for creating this PR.
> Fixed multicast IPv6 address handling in MPL

- tests/17-tun-rpl-br/04-border-router-traceroute.sh
- tests/17-tun-rpl-br/test-border-router.sh
- tests/17-tun-rpl-br/test-native-border-router.sh
The tests try to establish a connection with
tunslip6 before Cooja starts listening, increase
the delay from 20 to 30 seconds.
> tests: fix intermittent 17-tun-rpl tests

- tools/docker/Dockerfile
- tools/readthedocs/conf.py
This upgrades Sphinx from v1.8.6 to v5.0.1.
The front page (index.html) looks the same,
and the API documentation is produced
by Doxygen which is not updated.
> Dockerfile: update Sphinx to Python3

- Makefile.include
This adjusts the build rules to mostly match
the blog post that was linked in the initial
commit 7a228fea41f7. There are two adjustments
compared to the blog post:
1) Our SOURCEFILES can contain sources in any
language, so we need to filter out the ones
that can get automatic dependencies generated.
2) No dependency on $(DEPDIR)/%.d for the object
build rules because that changes the build
for Cortex-M due to a .SECONDEXPANSION.
Before this patch, make would try to include
$(OBJDIR)/%.c as Makefiles for dependencies.
There should never have been any c files in
$(OBJDIR), but this behavior might explain
why the CUSTOM_RULE_C_TO_O does not have
dependency generation.
The lack of dependency on $(DEPDIR)/%.d is an issue,
but things are no worse than before this patch.
> Makefile: only include *.d for deps

- arch/platform/cooja/Makefile.cooja
This aligns the implementation of the quickstart
rule with the other parts of the build system
that calls Cooja.
> cooja: switch quickstart rule to use ant

- tools/doxygen/Makefile
Only doclatex and docroot are used
by Doxyfile, remove the other variables.
The generated html is identical before/after
this commit.
> doxygen: remove cygwin support

- tools/docker/Dockerfile
The only remaining Python 2 script
in the repository is the jn516x motelist.
This shrinks the image from 4.31G to 4.23G.
> Dockerfile: remove Python 2

- tools/docker/Dockerfile
Combining these RUN lines and removing
the cache reduces the size listed by
"docker images" from 4.31G to 4.24G.
> Dockerfile: remove pip cache

- tools/docker/Dockerfile
This is required for upgrading to Ubuntu 20.
> Dockerfile: update to renode 1.13.0

- os/net/app-layer/coap/coap-engine.c
The parameters are already documented in the header
file.
> coap: fix doxygen multiple param warning

- os/net/ipv6/uip-arch.h
The function is already declared in net/ipv6/uip.h
which is included at the top of the header.
This is not the only duplicate declaration in this
header file, but this is the only declaration that
causes a Doxygen warning so remove this and leave
the others for after the release.
> ipv6: remove duplicate uip_chksum declaration

- arch/platform/zoul/dev/antenna-sw.h
- arch/platform/zoul/dev/led-strip.h
These functions do not return anything,
so remove the return tag.
> zoul: remove faulty doxygen return doc

- arch/platform/cc26x0-cc13x0/sensortag/bmp-280-sensor.c
- arch/platform/cc26x0-cc13x0/sensortag/sensor-common.h
These functions do not return anything.
> sensortag: remove faulty doxygen return doc

- os/net/ipv6/uip.h
The doxygen documents a commented out function,
so turn the documentation into a regular comment.
> uip6: disable doxygen for disabled function

- arch/cpu/cc2538/rtimer-arch.c
- arch/cpu/cc26x0-cc13x0/rtimer-arch.c
- arch/cpu/nrf52832/rtimer-arch.c
- arch/cpu/nrf52840/rtimer-arch.c
- arch/cpu/simplelink-cc13xx-cc26xx/dev/rtimer-arch.c
- os/sys/rtimer.h
This moves the doxygen descriptions to the os/sys/rtimer.h file so that the param list is described only once. Seems to remove the doxygen warning on the rtimer codebase.
> fixed doxygen comments on rtimer arch code.

- os/services/simple-energest/simple-energest.c
As in title - fixes compilation failure for at least simplelink platform.
> Add missing include in simple-energest

- tools/docker/Dockerfile
As we can see on #1845, the mirror://mirrors.ubuntu.com/mirrors.txt is not working.
I tried locally and it also does not work.
@pjonsson I can see that you added it. Is it okay to revert it?
> Use default mirror in docker build

- tests/00-documentation/Makefile
- tools/doxygen/Doxyfile
Tell doxygen to be quiet instead of piping
output to /dev/null.
> doxygen: turn on quiet mode

- arch/cpu/cc26x0-cc13x0/ble-addr.c
- arch/cpu/cc26x0-cc13x0/ble-addr.h
There are multiple definitions of ble_addr_to_eui64
in the tree. Align the implementations so
cc26x0-cc13x0 implementation behaves the same way
as the simplelink-cc13xx-cc26xx implementation.
> Align ble_addr_to_eui64 implementations

- arch/cpu/simplelink-cc13xx-cc26xx/rf/sched.c
Radio off can be called in interrupt context, especially by the TSCH code. On the SimpleLink platform radio off is calling `rf_yield` which in turn calls `etimer_stop` for the frequency recalibration timer, but timer operations are not safe in interrupt context, as the timers are stored in linked lists, data structure vulnerable to race conditions.
This PR changes the logic to avoid calling the `etimer_stop`  from this interrupt context.
> simplelink: avoid calling etimer_stop in interrupt context

- arch/platform/cooja/slip-arch.c
The file uses slip_input_byte which resides
in slip. Slip uses the rxbuf from uIP, and
that is not available with NULLNET.
> cooja: disable slip-arch with NULLNET

- tools/docker/Dockerfile
This is not required with Python 3.8.
> Dockerfile: remove pc_ble_driver workaround

- arch/platform/native/Makefile.native
These modules do not work on Native.
> native: exclude spi.c and stack_check.c

- os/net/ipv6/tcp-socket.c
The functions in tcpip.c are conditionalized
on UIP_TCP, so the symbols used by tcp-socket.c
cannot be taken for granted.
The build system does not offer conditional
builds based on configuration, so add an #if
around the contents of tcp-socket.c for now.
> ipv6: conditionalize tcp-socket on UIP_TCP

- arch/platform/jn516x/Makefile.customrules-jn516x
- arch/platform/jn516x/Makefile.jn516x
The platform specific rules should be
defined at the stage of the customrules
inclusion, not at the target makefile
inclusion.
The output of:
env RELSTR=test make NUMCORES=1 Q=''
in 04-compile-nxp-ports is identical
before/after this patch.
> jn516x: add a customrules file

- examples/lwm2m-ipso-objects/Makefile
The serial-protocol.c contains functionality
that is used by example-server.c in the same
directory.
> lwm2m-ipso-objects: do not build unused file

- examples/benchmarks/rpl-req-resp/Makefile
- examples/benchmarks/rpl-req-resp/node.c
This PR enabled building the `rpl-req-resp` benchmark example on Simplelink by removing it from the PLATFORMS_EXCLUDE list.
> examples/benchmarks/rpl-req-resp: enable building for Simplelink

- .github/workflows/build.yml
This adds the ccache action to CI runs.
The directory is mounted under /home/user/.ccache,
which is how the ccache action configures things.
Some speedups in CI on a warm cache (before/after):
01-compile-base: 1m36s/10s
02-compile-arm-ports: 11m3s/2m30s
07-simulation-base: 4m35s/3m41s
17-tun-rpl-br: 12m48s/12m51s
The first two tests only compiles, and they
both get >99.9% hitrate for the cache so the speedup
is significant.
The third test compiles and performs some work,
so the 100% hitrate for the cache gives a smaller
speedup.
The fourth test gets a 100% hitrate for the cache,
but most of the time is spent on other things.
The increased time for the second run is not
caused by ccache, most likely the second
runner was a slower machine.
> CI: add ccache action

- examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/cc26x0-web-demo.h
This ensures the snprinted values fit
in the buffer.
> cc26x0-web-demo: increase buffer size

- os/net/mac/tsch/sixtop/sixp-trans.c
The function returns a sixp_trans_mode_t,
so use an enum value from that enum.
> sixtop: return right enum value

- arch/cpu/cc2538/Makefile.cc2538
- arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
- arch/cpu/msp430/Makefile.msp430
- arch/cpu/nrf52832/Makefile.nrf52832
- arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
- arch/platform/jn516x/Makefile.customrules-jn516x
Some platforms have special build rules in their Makefiles, add ccache support to those too.
> Add missing ccache calls

- os/storage/antelope/aql-parser.c
NONE is an enum value from token, but
PARSER_ARG returns an aql_status_t value.
Use the PLE_ERROR return value instead
since that is the right type and will still
give a failure with AQL_ERROR().
> antelope: use aql_status_t return value

- arch/platform/zoul/dev/adc-zoul.c
Clang gives a warning about integer in
boolean context, make the comparison
explicit instead.
> adc-zoul.c: fix compiler warning

- os/services/at-master/at-master.c
Use != instead of inverting the LHS before
comparing it to a value.
This fixes a -Wlogical-not-parentheses warning
with Clang.
> at-master: fix compiler warning

- Makefile.include
- arch/cpu/arm/cortex-m/Makefile.cortex-m
This is preparation for making cortex-m use
the link rule in Makefile.include.
The output from
env RELSTR=test make NUMCORES=1 Q=''
on 02-compile-arm-ports is identical before/after
this patch.
> Makefile: add support for --start/end-group

- tests/Makefile.compile-test
Mirror the logic from Makefile.simulation-test
so make exits with an error upon failure. This
also removes the output per test when it passes,
this is convenient for the 100 tests in
02-compile-arm-ports.
> tests: return error from make for compile tests

- os/net/app-layer/snmp/snmp-api.h
Redefinition of a typedef is a C11 feature.
These typedefs are identical, so remove one
of them.
> snmp: stop redefining typedef

- os/net/app-layer/mqtt/mqtt-prop.c
Perform the error checks on input values
before declaring the variables that
are used in the function. Also stop casting
the return value of memb_alloc since it
already returns a void *.
This does not change the behavior of the function.
> mqtt-prop.c: declare variables later

- os/services/orchestra/orchestra-conf.h
- os/services/orchestra/orchestra-rule-eb-per-time-source.c
- tests/07-simulation-base/26-cooja-rpl-tsch-orchestra-perfect-link.csc
**The problem:** there is an intention to logically separate the channel offsets that are used for EB packets, for broadcast packets, and for unicast packets. However, the max unicast channel offset is set to 255. The real channel is calculated as `offset % hopping_sequence_size`. As typical hopping sequences are much shorter than 256 elements, in many cases unicast packet are going to use the same physical channels as EB and broadcast packets, leading to potential collisions between these types of packets.
**The solution:** the PR makes the range of channel offsets dependent on the hopping sequence size. This will not work as intended if the hopping sequence is changed at the runtime to have a smaller number of channels. However, this is not typical for most networks.
Of course, keeping …
> Orchestra: optimize channel offsets of unicast slotframes

- Makefile.identify-target
Make fails in strange ways if called with
TARGET="native ". Since both $(TARGET)
and $(BOARD) are typically set by the user
when invoking make, check that they do not
contain trailing whitespace.
> Makefile: detect faulty $(TARGET)/$(BOARD)

- arch/cpu/arm/Makefile.arm
- examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/Makefile
The flag entered the repository through
the nrf52832 port. Why that flag was added
to the nRF5 SDK in the first place is unclear:
https://devzone.nordicsemi.com/f/nordic-q-a/53021/reason-for--fno-builtin-introduced-in-sdk-7
The flag is a sledgehammer, -fno-builtin-printf
disables -Wformat warnings, and optimizations
for general purpose functions such as strcmp/memcmp,
general purpose floating point functions,
and typical bit operation functions such as
clz/ctz/popcount.
> arm: remove -fno-builtin

- os/net/mac/tsch/sixtop/sixp-trans.c
Redefinition of a typedef is a C11 feature.
These typedefs are identical, so remove one
of them.
> sixtop: stop redefining typedef

- Makefile.include
Un-nest some if/else and add some comments so
it is obvious that the target makefile process is:
1) identify target makefile (in-tree or from $TARGETDIRS)
2) ensure exactly one target makefile was found for the target
3) include the found makefile
Also wrap the check for existence of the compiler
so "make clean" always works.
Besides making "make clean" always work, everything
else works like before.
> Makefile: tweak target_makefile logic

- arch/cpu/nrf52832/Makefile.nrf52832
Targets that have their own way of constructing
the list of object files to be built cause issues
with completing the dependency management in
the build system.
Since all files are compiled with the same flags,
there is no strong reason to "partition" the build
and hamper build parallelism. Add the source files
from the SDK to CONTIKI_SOURCEFILES instead of
constructing something special for this architecture.
All object files are still built with the same flags
as before this patch, the only thing that has changed
is that the object files are passed directly to the linker
instead of first making a library that is passed to the linker.
> nrf52832: remove $(NRFLIB)

- arch/platform/cooja/Makefile.cooja
Cooja cannot find the information required
in the map file when objects are compiled
with -fno-common. This is the default
with GCC 10/Clang 11 and later, so add
the -fcommon to our build for now.
> cooja: add gcc 10 support on Linux

- tools/vagrant/bootstrap.sh
The nearby mirrors work great in Sweden,
but there were intermittent CI failures
for the docker image.
This reverts commit 2f8dd337ed3f000c210fe44903ddc5a7ecfa69e4.
> Revert "vagrant: use nearby mirrors"

- arch/cpu/arm/cortex-m/Makefile.cortex-m
- arch/cpu/arm/cortex-m/Makefile.customrules-cortex-m
Move definitions to align the customrules for
cortex-m with the rules in Makefile.include.
This is preparation for making cortex-m-based
platforms be able to link without custom rules.
The compiler invocations are identical before/after
this commit.
> cortex-m: align build with Makefile.include

- arch/cpu/cc2538/Makefile.cc2538
- arch/platform/sky/Makefile.common
- arch/platform/z1/Makefile.common
The file cfs-coffee.c comes from
os/storage/cfs, so stop adding that file to
the architecture specific build files.
> Makefile: do not add cfs-coffee in arch

- doc/getting-started/Toolchain-installation-on-Linux.md
This variable is no longer required
by Cooja.
> doc: remove $JAVA_HOME section

- os/net/nbr-table.c
Calling remove_key with NULL causes
a write of 0 into used_map[-1]
and locked_map[-1].
> nbr-table.c: do not remove NULL key

- .github/workflows/build.yml
The tests take 15 minutes under normal
circumstances and the default github timeout
is 6 hours. Set a reasonable timeout so
a slow test will complete within the timeout,
but a myserious failure will be killed
before one has to leave the office.
> CI: lower the workflow timeout

- os/net/mac/tsch/sixtop/sixp-nbr.c
Use the same return type for the funtion
and the declaration.
> sixtop: align return type with decl

- tests/17-tun-rpl-br/04-border-router-traceroute.sh
The "traceroute6" line goes into the log
for some versions of traceroute6. Filter
that line out when counting the number
of hops.
> tests: fix validation for new traceroute6

- arch/cpu/arm/cortex-m/Makefile.cortex-m
- arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
There is a performance penalty of forcing
the linker to resolve circular dependencies
so only enable it on platforms that needs
the support.
> cortex-m: do not add LD_*_GROUP by default

- Makefile.include
- arch/platform/cooja/Makefile.cooja
- arch/platform/cooja/redefine.syms
- os/lib/dbg-io/printf.c
- os/lib/dbg-io/putchar.c
- os/lib/dbg-io/puts.c
- os/lib/dbg-io/snprintf.c
- os/lib/dbg-io/sprintf.c
This removes the non-errorchecked symbol
renaming done through objcopy and uses
the --wrap parameter to ld instead.
MacOS X does not come with objcopy so
the symbol renaming has never been
active on that platform.
> cooja: wrap dbg-io funs and call them

- Makefile.include
- arch/cpu/cc2538/Makefile.cc2538
- arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
- arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
Put this definition in one place instead
of having a copy around in multiple targets.
> Makefile: move FORCE to Makefile.include

- tests/17-tun-rpl-br/04-border-router-traceroute.sh
- tools/docker/Dockerfile
More recent versions of iptuils-tracepath
do not contain traceroute6. The traceroute
package is the obvious replacement, but
that gives "* * *" as one or several results
in 17-tun-rpl-br.
The traceroute6 in traceroute most likely
uses a different way of probing hosts and
that doesn't work with Cooja and/or some
component in the regression tests.
Rather than diagnosing the exact issue,
install mtr-tiny and use that since it
works out of the box for the regression
tests.
> Dockerfile: replace traceroute6 with mtr

- tools/docker/Dockerfile
This is possible now that we are using a 64 bits docker image
Before and after. The git hash is the same, just the date is different.
```bash
❯ contiker
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
user@b08f5ae283d1:~/contiki-ng$ renode --version
Renode, version 1.13.0.15726 (e7f96b97-202207170844)
user@b08f5ae283d1:~/contiki-ng$ ^C
user@b08f5ae283d1:~/contiki-ng$ logout
❯ contiker
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
user@83d75c1fdb78:~/contiki-ng$ renode --version
Renode, version 1.13.0.13110 (e7f96b97-202204300716)
user@83d75c1fdb78:~/contiki-ng$
```
> Use renode deb from releases instead of building from source

- os/net/mac/ble/ble-l2cap.c
While the bounds check is performed on `l2cap_channel_count`, only the lower byte is checked due to the uint8_t data type. Afterwards, the expression for `i` is re-calculated without the explicit data type, which means without truncation into 8 bits. Instead, the full 16-bit value is used as the channel index. This pointer will point out-of-bounds of the channel array.
This leads to a large 16 out-of-bounds channel id to be used as an index into the array for large CID inputs.
Sample value: 0xff41 -> 0xff41 - 0x41 = 0xff00 == 0x00 (as uint8_t)
This results in out-of-bounds memory to be interpreted as a channel object, and this memory to potentially be corrupted in the following call to `input_l2cap_frame_flow_channel`, which fills the out-of-bounds memory (the supposed channel object) …
> Fix l2cap_channels OOB in get_channel_for_cid

- .github/workflows/build.yml
An unusually long docker image build will
make the tests timeout, so increase the timeout
slightly.
> CI: increase the workflow timeout

- Makefile.include
- arch/cpu/arm/Makefile.arm
- arch/platform/jn516x/Makefile.jn516x
The .PRECIOUS directive is a sledgehammer that keeps faulty intermediate files around. Tell make to not remove intermediate results instead with the .SECONDARY directive.
> Makefile: remove .PRECIOUS

- os/lib/ringbufindex.h
- os/net/mac/tsch/sixtop/sixtop-conf.h
- os/net/mac/tsch/tsch-adaptive-timesync.h
- os/net/mac/tsch/tsch-asn.h
- os/net/mac/tsch/tsch-conf.h
- os/net/mac/tsch/tsch-const.h
- os/net/mac/tsch/tsch-log.h
- os/net/mac/tsch/tsch-packet.h
- os/net/mac/tsch/tsch-queue.h
- os/net/mac/tsch/tsch-roots.h
- os/net/mac/tsch/tsch-rpl.h
- os/net/mac/tsch/tsch-schedule.h
- os/net/mac/tsch/tsch-security.h
- os/net/mac/tsch/tsch-slot-operation.h
- os/net/mac/tsch/tsch-stats.h
- os/net/mac/tsch/tsch-types.h
- os/net/mac/tsch/tsch.h
- os/services/ip64/ip64-dhcpc.h
- os/services/orchestra/orchestra-conf.h
- os/services/orchestra/orchestra.h
- os/services/tsch-cs/tsch-cs.h
- os/sys/cc-gcc.h
- os/sys/log-conf.h
- os/sys/log.h
All identifiers that begin with an underscore
followed by a capital letter or by another
underscore are reserved in C. Use other names
for headerguards.
> Stop defining reserved identifiers

- .github/workflows/build.yml
Using the git commit hash on the Dockerfile
ignores the content of the files copied into
the docker image. Compute a hash of everything
and use that to identify the docker image
instead.
> CI: use hashFiles for docker image name

- arch/cpu/cc2538/Makefile.cc2538
- arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
- arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
- arch/platform/cooja/Makefile.cooja
- arch/platform/jn516x/Makefile.customrules-jn516x
Align the architecture specific build rules
with the rules in Makefile.include. This
prevents make from throwing in an extra
mkdir for a directory that already exists.
> Makefile: fix arch compilation dependencies

- tests/Makefile.compile-test
The build system changes removed some printouts
from make which mangles the test output when
not running in the CI. Add the newline to echo
instead so one test per line is printed.
> tests: fix printout

- Makefile.include
- arch/platform/cooja/slip-arch.c
Use the new build system support to exclude
the file instead.
> cooja: exclude slip-arch.c with NULLNET

- tools/docker/Dockerfile
Switch to the Ubuntu mono packages
and let the renode package install
the dependencies it needs. This ensures
the image is as small as possible
even when the renode dependencies change.
This change also removes the warning
about key handling that is printed
in red when building images.
> Dockerfile: use Ubuntu mono packages

- Makefile.include
- arch/platform/zoul/Makefile.zoul
- examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/Makefile
- examples/snmp-server/Makefile
Defines such as `CONTIKI_VERSION_STRING` and `DATE` are different on almost every make invocation. Only pass these defines to files that need them, so ccache can get a direct hit for the other files.
> Only pass non-constant defines to objects that need them

- tests/07-simulation-base/20-cooja-rpl-tsch-orchestra.csc
- tests/07-simulation-base/24-cooja-rpl-tsch-orchestra-storing.csc
- tests/07-simulation-base/25-cooja-rpl-tsch-orchestra-link-based.csc
- tests/07-simulation-base/27-cooja-rpl-tsch-orchestra-root-rule.csc
ContikiMoteType emits a warning because
it does not parse the firmware tag. Remove
the tag from the simulation files.
> tests: fix Cooja warning

- arch/cpu/msp430/Makefile.msp430
The flag is already added to CFLAGS
a few lines below this definition.
> msp430: only pass -Wall once

- arch/cpu/arm/Makefile.arm
The hex and bin files are not required
for the target according to the comment,
so stop building them.
This is preparation to remove the customrules
for Cortex-M, but it also saves IO load
on the IO-limited CI machines.
> arm: remove false dependencies

- Makefile.include
- arch/cpu/msp430/Makefile.msp430
- doc/project/Release-Notes-next.md
Add a build system option "LTO" so examples
can be built with "make <options> LTO=1".
Targets that do not support the option can
define NO_LTO_TARGET to have the PLATFORM_ACTION
set to skip when LTO is enabled.
The only targets that do not support
LTO are the msp430-based ones, the toolchain
recognizes the switch but crashes on every
program in the regression tests.
The size for hello-world in the docker container
without LTO:
text	   data	    bss	    dec	    hex	filename
118948	   2952	1110912	1232812	 12cfac	hello-world.native
and with LTO:
text	   data	    bss	    dec	    hex	filename
48579	   1728	  56568	 106875	  1a17b	hello-world.native
> Makefile: add link-time-optimization option

- arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
- arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
The dependency generation in Makefile.include will ensure the object file is up to date with respect to its dependencies.
> Stop rebuilding ccfg.o unless config has changed

- arch/platform/cooja/platform.c
The file is compiled with -DCLASSNAME="Lib1",
so remove the word CLASSNAME from places
where it is not substituted.
The path Java_org_contikios_cooja_corecomm
does not carry any significant information
in the context of platform.c, so remove
the path too.
Beyond the removed confusion about whether
CLASSNAME will be replaced by the preprocessor,
this change also makes most lines fit within
80 characters.
> cooja: shorten function names

- doc/project/Release-Notes-next.md
- tools/docker/Dockerfile
There are no mosquitto packages on the PPA
for this version of Ubuntu so use the packages
in Ubuntu instead. These are version 2.0.11
instead of 2.0.14, but 08-native-runs still
passes with this version.
> Dockerfile: upgrade to Ubuntu 22.04 LTS

- .github/workflows/build.yml
Reduce the fetch-depth from the entire
history down to 2 now that the Docker
image hash is computed based on file
content rather than the git hash.
A fetch-depth of 2 should be enough to
detect which files that were changed
in a PR, for example for running additional
checks such as code-formatting or similar
on them.
> CI: reduce fetch-depth

- .github/workflows/build.yml
The Cooja dist/build directories are
12M in total, so cache them to avoid
rebuilds in many of the tests.
> CI: cache Cooja build artifacts

- arch/cpu/nrf52832/Makefile.nrf52832
Make sure the output directory exists
before writing files to it.
> nrf52832: fix assemble rule

- arch/cpu/msp430/Makefile.msp430
This saves 2-8 bytes of text and a few bytes
of bss for the tests in 01-compile-base.
Before:
47905	    880	   6758	  55543	   d8f7	build/sky/snmp-server.sky
46545	    908	   5734	  53187	   cfc3	build/z1/snmp-server.z1
41803	    326	   5742	  47871	   baff	build/z1/hello-world.z1
42995	    314	   6766	  50075	   c39b	build/sky/example-stack-check.sky
44663	    334	   6094	  51091	   c793	build/sky/border-router.sky
29413	    300	   4504	  34217	   85a9	build/sky/slip-radio.sky
32037	    268	   5660	  37965	   944d	build/sky/nullnet-broadcast.sky
32037	    276	   5660	  37973	   9455	build/sky/nullnet-unicast.sky
After:
47903	    880	   6756	  55539	   d8f3	build/sky/snmp-server.sky
46540	    906	   5720	  53166	   cfae	build/z1/snmp-server.z1
41795	    324	   5728	  47847	   bae7 …
> msp430: sort sections by alignment

- arch/cpu/nrf/Makefile.nrf
- arch/cpu/nrf52832/Makefile.nrf52832
- arch/cpu/nrf52840/Makefile.nrf52840
Libraries should be linked through
TARGET_LIBFILES, not LDFLAGS.
> nrf: use TARGET_LIBFILES for libraries

- os/lib/dbg-io/strformat.c
These shifts require 18 bits which is more
than a 16 bit int, change type to uint32_t.
> dbg-io: 16-bit fixes

- Makefile.include
- arch/cpu/native/Makefile.native
The intermediate archives are no longer
built so remove the now unused AROPTS.
> Makefile: remove unused $(AROPTS)

- Makefile.include
- arch/cpu/cc2538/Makefile.cc2538
This avoids rebuilding the linker script
unless dependencies have changed.
> Makefile: add dep generation for $(LDSCRIPT)

- tests/08-native-runs/10-snmp-server.sh
The 10-snmp-server.sh test fails intermittently
in the CI, keep the server running for the entire
test and stop redirecting the output so
the timestamps can be seen when it fails.
> tests: tweak 10-snmp-server.sh

- arch/platform/cooja/platform.c
Give meaningful names to the macros and their parameters for JNI methods, and add comments that explain their purpose.
Also remove some commented out code and fix some style issues since I'm updating the file.
> cooja: platform.c docs+style fixes

- Makefile.include
- arch/cpu/nrf52832/Makefile.nrf52832
Sort in GNU Make is documented to remove
duplicates so use that instead of defining
a recursive function.
> Makefile: use sort to remove duplicates

- arch/cpu/msp430/Makefile.msp430
The debug info is not required for Cooja
to work in the regression tests, so build
a release build by default.
This is a sibling to commit 80b8223a22.
> msp430: do release builds by default

- Makefile.include
- arch/platform/cooja/Makefile.cooja
This is required to avoid renumbering
the motes needlessly.
> cooja: add dep generation for mtypeNNN.o

- tools/docker/Dockerfile
The latest version of nrfutil does not
require to manually install the older
version of protobuf.
> Dockerfile: remove nrfutil workaround

- arch/cpu/cc2538/Makefile.cc2538
- arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
- arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
Use the rule in Makefile.include for building object files. This makes the dependency generation work, and that is a requirement for avoiding rebuilds in a future patch.
> Fix dependency generation for ieee-addr.c

- .github/workflows/build.yml
- doc/getting-started/Docker.md
- tools/docker/print-dockerhash.sh
Switch to a user-runnable computation of the hash for the docker image.
> CI: use different hash for Dockerfile

- tools/docker/Dockerfile
Use GraalVM as the JVM. This saves 50 Mb
of space for the Docker image and runtime
on the tests:
Runtime for 07-simulation-base before:
real 144.14
user 269.64
sys 16.18
After:
real 133.04
user 242.39
sys 19.22
> Dockerfile: use graalvm instead of openjdk

- arch/cpu/nrf/arm/hardfault-handler.c
Naked functions are only supposed to contain
inline assembly, and this function contains
regular C statements. Remove the naked
attribute for the non-assembly version
of the function.
> nrf: remove naked in hardfault-handler.c

- tests/08-native-runs/10-snmp-server.sh
Print everything to the log as it happens
so we can pinpoint the issue with intermittently
failing tests.
> tests: provide more output for failing test

- tools/docker/Dockerfile
Most of these packages seem to have been installed
with the addition of renode to the docker image.
Remove the packages from the list and let
apt-get install the required dependencies.
Also document what most of the remaining packages
are used by.
> Dockerfile: let apt-get install deps

- Makefile.include
Ubuntu ships clang-14, but OS X contains
clang-13. Add the possibility to override
the Clang version through $(CLANG_CC).
> Makefile: allow overriding Clang version

- os/net/ipv6/tcp-socket.h
- tests/07-simulation-base/code-ipv6/tcp-client/Makefile
- tests/07-simulation-base/code-ipv6/tcp-client/tcp-client.c
- tests/07-simulation-base/code-ipv6/tcp-server/Makefile
- tests/07-simulation-base/code-ipv6/tcp-server/tcp-server.c
* Add explicit socket closing and de-registration.
* Improve output and buffer management.
* Minor documentation fixes.
* Disable RPL routing because we use link-local addresses.
> Minor TCP test improvements

- tools/docker/files/cooja
Make the Cooja script forward its arguments
to ant. This makes it possible to quickstart
simulations through the cooja script.
> Dockerfile: forward arguments to Cooja

- .github/workflows/build.yml
- tools/docker/Dockerfile
Nothing apparent that affects Contiki-NG in the issues fixed, but looks like a nice improvement over v4.6.1.
> Update to ccache v4.6.2

- arch/cpu/cc2538/lpm.c
- arch/cpu/cc26x0-cc13x0/rf-core/rf-switch.h
Clang with -Wall gives a -Wempty-body
warning in these places, add a newline
to make it obvious that the loop does
nothing.
Uncrustify does not change this formatting.
> Fix -Wempty-body warning

- .github/workflows/build.yml
- Makefile.include
- arch/cpu/msp430/Makefile.msp430
- arch/platform/cooja/Makefile.cooja
- examples/benchmarks/result-visualization/run-cooja.py
- tests/Makefile.simulation-test
- tools/docker/files/cooja
This switches to using the Gradle build system
for Cooja. This will make it easier to update
dependencies without having to store every JAR
in the repository.
> cooja: use gradle instead of ant

- tools/docker/Dockerfile
Add a separate non-default Java 17 to
the docker image. This simplifies the work
on making Cooja work with Java 17.
> Dockerfile: add Java 17

- arch/platform/cooja/Makefile.cooja
LIBNAME is not set, for example, in quickstart mode or for clean.
> cooja: only add dependences based on LIBNAME when LIBNAME is available.

- .github/workflows/build.yml
There are 16 runners so reduce the cache
size according to the size of the largest
test. Also document how to tune the cache
size.
> CI: reduce ccache cache size

- Makefile.include
- arch/cpu/msp430/Makefile.msp430
- examples/benchmarks/result-visualization/run-cooja.py
- tests/Makefile.simulation-test
This ensures the right version of gradle
is used for building.
Add a cooja submodule update in this PR to ensure that the gradle distribution is cached in the CI.
> cooja: use gradlew to build

- tests/17-tun-rpl-br/01-border-router-cooja.csc
- tests/17-tun-rpl-br/02-border-router-cooja-tsch.csc
- tests/17-tun-rpl-br/03-border-router-sky.csc
- tests/17-tun-rpl-br/04-border-router-traceroute.csc
- tests/17-tun-rpl-br/07-native-border-router-cooja.csc
- tests/17-tun-rpl-br/08-border-router-cooja-frag.csc
- tests/17-tun-rpl-br/09-native-border-router-cooja-frag.csc
Cooja currently adds this loop implicitly
at the end of all user scripts, and that
prevents a nice shutdown of Cooja.
Add the infinite loop to the tests that
requires it, to make way for changing
Cooja to shutdown nicely.
> tests: make non-termination explicit

- examples/6tisch/simple-node/project-conf.h
SimpleLink CC13xx/CC26xx prints a message in the regression
tests that it disables LOG_CONF_LEVEL_FRAMER. Stop
defining LOG_CONF_LEVEL_FRAMER for those configurations.
> 6tisch/simple-node: disable LOG_CONF_LEVEL_FRAMER

- tools/docker/Dockerfile
- tools/docker/files/cooja
The Gradle wrapper is now used everywhere,
so remove the software from the image.
> Dockerfile: remove gradle

- arch/platform/cooja/Makefile.cooja
Only run Cooja quickstart on Cooja simulation files. Also, avoid build warnings when, for example, running `make TARGET=cooja viewconf`.
> cooja: simplify Cooja quickstart rule

- Makefile.include
- arch/platform/cooja/Makefile.cooja
- tools/docker/files/bash_aliases
This is a makefile change and a new alias in the docker image so it's possible to type
cscmake sim.csc
from anywhere in the tree to quickstart Cooja with sim.csc.
> Simplify starting Cooja on a simulation file

- arch/platform/cooja/Makefile.cooja
- arch/platform/cooja/mtype.c
- arch/platform/cooja/platform.c
By moving the JNI functionality from platform.c to its separate file, the Cooja platform can be built similarly to other platforms, enabling test compilation for Cooja even if Cooja can not use the resulting binary.
> Enable the Cooja platform to build without using Cooja

- arch/platform/cooja/Makefile.cooja
Prevent building Cooja target binaries
from outside of Cooja.
Simulations can still be quickstarted
by using the native target (or any other
target than Cooja), or inside the docker
image:
cscmake file.csc
> cooja: only allow building from Cooja

- tests/Makefile.simulation-test
The build phase in Cooja tests is rarely
interesting, so make the build system quiet
by default for them.
The tests will still output everything when
running in the CI since the CI variable is set
to true.
> tests: reduce output of Cooja tests

- arch/cpu/nrf/Makefile.nrf
- arch/cpu/nrf/Makefile.nrf52840
- arch/cpu/nrf/Makefile.nrf5340_application
- arch/cpu/nrf/Makefile.nrf5340_network
- arch/platform/nrf/nrf52840/dongle/Makefile.dongle
- arch/platform/nrf/nrf52840/dongle/nrf52840-dongle-conf.h
- arch/platform/nrf/platform.c
- doc/platforms/nrf.md
- tests/02-compile-arm-ports/Makefile
Default USB to 0 on nrf boards except dongle because it only supports USB
Added documentation to the new compilation option
> Improved USB build on nrf port and added documentation

- os/sys/stack-check.c
The stack check init makes an assumption about the stack boundary by using the address of the local variable as a boundary. This assumption holds as long as no other local variable or function is executed within this function.
```c
void
stack_check_init(void)
{
uint8_t *p;
/* Make this static to avoid destroying it in the while loop */
static void *stack_top;
/* Use address of this local variable as a boundary */
stack_top = &p;
/* Note: this is expected to be called before the WDT is started! */
p = &_stack;
while(p < (uint8_t *)stack_top) {
*p++ = STACK_FILL;
}
#if STACK_CHECK_PERIODIC_CHECKS
/* Start the periodic checker process */
process_start(&stack_check_process, NULL);
#endif
}
```
That is not guaranteed, the compiler can replace the while loop with a messet and break the …
> Make stack check boundary volatile to prevent optimization

- .github/workflows/build.yml
A clean build of 02-compille-arm-ports now
takes 0.13Gb, so increase the cache size.
> CI: adjust cache size

- Makefile.include
Allow Cooja to select a different BUILD_DIR
through environment variables.
This is a way to ensure that the CI tests
work without requiring "make clean" in every
csc file.
> Makefile: enable Cooja to change BUILD_DIR

- os/net/app-layer/snmp/snmp-api.h
This is already typedefed in snmp-mib.h.
> snmp: remove double typedef

- tools/docker/Dockerfile
This is required for the Gecko SDK.
> Dockerfile: install git-lfs

- arch/cpu/cc2538/cc2538-def.h
- arch/cpu/cc2538/rtimer-arch.c
Currently, there is a magic number in the `rtimer_arch_schedule` implementation for CC2538 SoCs.
> CC2538: Eliminate magic number

- arch/platform/zoul/dev/grove-gyro.c
GROVE_GYRO_ERROR is defined as -1, so use a signed type that can represent the value.
> zoul: fix return type of grove_gyro_read_reg

- arch/platform/zoul/dev/rtcc.c
AB08_ERROR is defined as -1, so use a signed
type that can represent the value.
> zoul: fix return type of ab08_read_reg

- arch/platform/cooja/Makefile.cooja
- arch/platform/cooja/cooja.ld
Define helper symbols to inform Cooja about
start addresses and sizes of segments.
> cooja: use linker for section info

- arch/cpu/nrf/sys/linkaddr-arch.c
NRF_FICR is not available in non-secure mode when
building with TrustZone, so use a dummy address
for the non-secure TrustZone build for now.
This restores the behavior for non-secure TrustZone builds to how it was before commit 7d62acf0ee287.
> nrf: make linkaddr-arch.c build with TrustZone

- arch/cpu/nrf/dev/watchdog-arch.c
The first line in nrfx_wdt_init is NRFX_ASSERT(p_config) to ensure that a null config is not passed in.
Mirror the behavior of the nrf52840 port and pass
in a default config to the watchdog.
> nrf: init watchdog properly

- arch/platform/cooja/Makefile.cooja
These flags are no longer required after
the mapfile dependency was removed from
Cooja.
> cooja: remove non-required build flags

- arch/cpu/simplelink-cc13xx-cc26xx/dev/gpio-hal-arch.c
- arch/cpu/simplelink-cc13xx-cc26xx/dev/gpio-hal-arch.h
- arch/cpu/simplelink-cc13xx-cc26xx/dev/rtimer-arch.c
Some bug-fixes and improvements to the GPIO HAL:
1. Fixed a bug where the MCU does not wakeup from standby on DIO edges, and thus interrupts may be lost.
* The PIN driver does indeed configure wakeup on DIO edges [here](https://github.com/contiki-ng/coresdk_cc13xx_cc26xx/blob/master/source/ti/drivers/pin/PINCC26XX.c#L350), but the same wakeup-selector WU1 is re-purposed to RTC_CH1 in [rtimer-arch.c:153](https://github.com/contiki-ng/contiki-ng/blob/develop/arch/cpu/simplelink-cc13xx-cc26xx/dev/rtimer-arch.c#L153). This PR switches the wake-up for RTC_CH1 to WU3 (WU2 is used by BATMON). Happy to hear any comments on this solution.
2. Fixed a bug in the PIN-to-HAL config conversion which caused IRQ and pull-config not to be included.
3. cc13xx/cc26xx pins have independent output and input …
> Fixes to simplelink GPIO HAL

- os/net/ipv6/uip-nd6.c
Add a NULL pointer check to the return value of `uip_ds6_nbr_add` in the SLLAO link-layer address change case of Router Solicitation messages.
> fix rs_input missing NULL pointer check

- os/lib/memb.c
- os/lib/memb.h
- os/net/mac/csma/csma-output.c
- os/net/queuebuf.c
- os/net/queuebuf.h
Presently, the function `memb_numfree` returns `int`, suggesting that an error might occur. However, this function cannot fail and, in the code base, nobody is checking for errors anyway. Therefore, this PR changes the return type to `size_t`.
> memb: Confine return type of memb_numfree

- .github/workflows/build.yml
This makes it possible to find the cache
by searching for cooja in the cache information
webinterface.
> CI: rename cooja cache key

- arch/platform/cooja/dev/cooja-radio.c
This PR adds some missing getters to the `get_value` function of the Cooja radio driver.
> Cooja: Getters for channel information

- os/net/linkaddr.c
- os/net/linkaddr.h
- os/net/mac/framer/frame802154.c
- os/net/mac/framer/frame802154.h
- os/net/packetbuf.c
- os/net/packetbuf.h
Small improvement to use the bool datatype in comparisons of link layer addresses.
> Replace int with bool in comparisons of link layer addresses

- doc/tutorials/Cooja-simulating-a-border-router.md
The build system was changed, so pick some other
embedded target that is not Cooja.
Fixes #2280.
> doc: update Cooja border router tutorial

- os/net/app-layer/coap/coap-transactions.c
As in title, I only found one such occurrence.
H/T https://www.thingsquare.com/blog/articles/rand-may-call-malloc/ by @adamdunkels. 
Note I was unable to reproduce the described issue with cc13x0-cc26x0 and the coap-examples.
> Prefer OS random_rand() over rand()

- tools/docker/Dockerfile
The nordicsemi website gives a 404 on the old
URL, the download page gives this new URL for
these files.
> Dockerfile: update nrf-tools URL

- .github/workflows/build.yml
- doc/getting-started/Docker.md
- tools/docker/Dockerfile
- tools/docker/files/remap-user.sh
Give the docker user the same uid/gid as
the host user. This removes the recursive
chown calls in the Github CI.
> Dockerfile: support uid/gid != 1000

- os/lib/list.c
- os/lib/list.h
The intention of the const on the parameters
of the list functions is that they do not
modify that argument. Putting const on the list_t
type makes the type void **const rather than
the intended void *const *.
> list: put const in right place

- Makefile.include
- examples/benchmarks/result-visualization/run-cooja.py
- tests/Makefile.simulation-test
Cooja uses the parameter --[no-]gui to decide
whether to use headless mode. This makes it possible to pass simulation files directly to Cooja without passing -nogui/-quickstart.
Parameter names also use double dashes.
> Update for Cooja long parameter names

- Makefile.include
- arch/cpu/cc2538/Makefile.cc2538
Move the cc2538 preprocessing rule so
all targets can use it. This is preparation
for adding TrustZone support.
The output of:
cimake NUMCORES=1 Q=''
for 02-compile-arm-ports is identical
before/after this patch.
> Makefile: add ld script preprocessing rule

- arch/cpu/arm/Makefile.arm
Add an option TRUSTZONE_SECURE_BUILD that controls whether -mcmse should be passed to the compiler.
This is a build-internal option to prepare for
making it possible to build Contiki-NG with TrustZone.
> arm: enable building secure code

- os/net/routing/rpl-classic/rpl-dag.c
In rpl-lite, the default value for the prefix information lifetime is set to infinity. Previously, in rpl-classic, this value was not set at all and thus was 0. A value of 0 does not make sense, since the lifetime of the prefix then would be 0 seconds. We now do the same thing as rpl-lite.
> Fix the lifetime value of the default prefix information option in rpl-classic

- arch/cpu/nrf/Makefile.nrf5340_application
This runs the linker script through the preprocessor. There are only constants in the linker script right now so the only thing that changes is the location of the linker script when invoking the final link.
This is preparation for adding TrustZone support
where the secure and non-secure areas must be
at separate addresses.
> nrf5340: preprocess linker script

- arch/cpu/cc26x0-cc13x0/dev/soc-trng.c
Switch to interrupt-safe `process_poll()`, fixes #1752. Tested on cc1310 launchpad.
> Remove process_post() in cc26xx-cc13xx TRNG ISR

- os/net/mac/csma/csma-output.c
- os/net/mac/csma/csma.c
- os/net/mac/framer/framer-802154.c
- os/net/mac/mac-sequence.c
- os/net/mac/mac-sequence.h
- os/net/mac/tsch/tsch.c
- os/services/rpl-border-router/native/border-router-mac.c
The motivation behind this PR is to eliminate duplicate code and to avoid special handling for DSN=0.
> mac-sequence: Set destination sequence number (DSN) in mac-sequence.c

- doc/project/Organization.md
Fixes #1771 . The current doc. points to the maintainers team which it seems [github does not intend to be public](https://docs.github.com/en/organizations/organizing-members-into-teams/changing-team-visibility): _"People who are not members of the organization cannot view any teams."_. This PR takes a simple approach and links to the organization members instead - which is correct as long as all members are maintainers, as today. Ping @joakimeriksson to make sure I remember the board-part correctly.
> Fix broken maintainers link in doc.

- os/lib/circular-list.c
- os/lib/circular-list.h
- os/lib/dbl-circ-list.c
- os/lib/dbl-circ-list.h
- os/lib/dbl-list.c
- os/lib/dbl-list.h
In #2012, @pjonsson describes and fixes an issue with the `const` placement in the list library. This PR fixes the same issue for the remaining lists: circular-list, dbl-circ-list, and dbl-list.
> Correct const placement in remaining lists

- os/net/ipv6/uipopt.h
The configuration options `UIP_CONF_REASSEMBLY` and `UIP_REASSEMBLY` are leftovers from Contiki uIP stack that are not referenced anywhere in the code. For IPv6 reassembly (different from 6LoWPAN reassembly!) use `UIP_CONF_IPV6_REASSEMBLY` instead.
> remove unused configuration option UIP_CONF_REASSEMBLY

- os/net/mac/tsch/tsch.c
Currently on RSSI data from network-layer packets is used. I see no reason to not to use RSSI data from EB packets as well. Could help in some situations, when the other types of packets are not sufficiently frequent, or have not started being received yet.
> TSCH: use RSSI data from received EB packets in the link stats module

- arch/cpu/simplelink-cc13xx-cc26xx/cc13xx-cc26xx-conf.h
As in title. Mimics cc26x0-cc13x0.
> Allow overriding NETSTACK_CONF_RADIO for simplelink platforms

- arch/cpu/cc26x0-cc13x0/rf-core/prop-mode.c
- arch/cpu/cc26x0-cc13x0/rf-core/rf-core.c
- arch/cpu/cc26x0-cc13x0/rf-core/rf-core.h
Fixes https://github.com/contiki-ng/contiki-ng/issues/1089
When the radio receives a lot of packes the rx buffer becomes full and the radio stops listening. 
before when handling the rf_core_rx_is_full flag this was logged:
```
RXQ was full, re-enabling radio!
rf_cmd_prop_rx: send_cmd ret=0, CMDSTA=0x00000c23, status=0x0000
```
The current implementation of rf_is_on tested if the status of the rx command is ACTIVE but if an error occurs in the rx command then the radio is still on and just not listening. The different usages of this function indicate that sometimes we want to know if the rx command is in the ACTIVE state and other times we just want to know if the radio is on.
So I decided to hold a flag that is set if the radio is turned on and is cleared when the radio is turned off. …
> Fix rx problem on cc1310 radio

- os/net/routing/rpl-classic/rpl-icmp6.c
As in title, gave me trouble when making binaries for the FIT IoT-lab.
> Fix include of random-lib in rpl-icmp6

- os/net/mac/ble/ble-l2cap.c
- os/net/mac/ble/ble-l2cap.h
Thanks to @SWW13 and @Scepticz for reporting the issue.
> Prevent buffer overflows due to misconfigured BLE MTU.

- os/net/ipv6/uip.h
Currently, the macro `uip_is_addr_mac_addr_based` does not adapt to the configured length of MAC addresses. When using IEEE 802.15.4 short addresses, there are out-of-bounds reads and missed chances for suppressing IIDs.
> 6LoWPAN: Fix compression of IEEE 802.15.4 short address-based IIDs

- os/storage/antelope/storage-cfs.c
https://github.com/contiki-ng/contiki-ng/blob/406ae7da30fb5fadacf0d646a4dc4ac0513a2dec/os/storage/antelope/storage.h#L47-L49
The macro `INDEX_NAME_LENGTH` does not count the trailing null char.
> antelope,storage-cfs: Fix length of filename array

- os/net/mac/tsch/tsch.h
This resolves 'deprecated-non-prototype' errors when building with some modern compilers.
> tsch: fix callback function signatures

- examples/6tisch/etsi-plugtest-2017/sf-plugtest.c
- examples/6tisch/sixtop/sf-simple.c
- os/net/mac/tsch/tsch-packet.c
- os/net/mac/tsch/tsch-schedule.c
- os/net/mac/tsch/tsch-schedule.h
- os/services/orchestra/orchestra-rule-special-for-root.c
- os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-storing.c
@atiselsts Since there is a legitimate use for a function that checks whether a link exists based solely on slot offset (a.k.a., "timeslot"), it would be better to rename the functions `tsch_schedule_remove_link_by_timeslot` and `tsch_schedule_get_link_by_timeslot` to reflect the changes introduced in #1162 , where these functions were modified to operate on timeslot and channel offset, instead of just timeslot.
> Renamed get and remove tsch link functions

- os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-ns.c
Develop got broken after merging #2040 due to one call of the renamed TSCH schedule functions was missed. This PR fixes. ~Not sure why the test did not fail in #2040 but too late to investigate this now😴~ Test did not fail in #2040 because it was rebased the day before the offending changes was added in #1540 🤦‍♂️ Memo to self: Re-run CI (or rebase) PRs that have been stale for a while before merging.
> Add missing renaming of TSCH schedule function per PR#2040

- Makefile.include
GCC 12 gives -Warray-bounds warnings
when writing to an address, and
Jakub Jelinek points out this breaks
a lot of existing code. GCC 13 is
supposed to be better in this
respect.
The binutils bundled with ARM GCC 12.1
also gives warnings about RWX-segments.
Disable the warning for now so the code
can build, and put in a FIXME with a
link to the blog post describing the rationale
and solution.
> arm: silence some GCC 12 warnings

- os/lib/heapmem.c
- os/lib/heapmem.h
This PR removes a GCC 12 compiler warning, which is a false positive.
> heapmem: include the code only if the arena size is configured

- arch/platform/cooja/contiki-conf.h
Cooja motes implement the LED HAL API (thanks to https://github.com/contiki-ng/contiki-ng/pull/1044), but do not have the right defines in place, so it end up being unused.
> add PLATFORM_HAS_LEDS to coojamote header files

- arch/cpu/cc2538/cc2538.lds
ARM GCC 12 gives a warning that disappears
when adding a space between the variable name
and the equals sign.
> cc2538.lds: fix spacing

- arch/platform/zoul/dev/grove-gyro.c
- arch/platform/zoul/dev/rtcc.c
- arch/platform/zoul/dev/servo.c
- examples/platform-specific/zoul/test-bmp085-bmp180.c
- examples/platform-specific/zoul/test-grove-light-sensor.c
- examples/platform-specific/zoul/test-grove-loudness-sensor.c
- examples/platform-specific/zoul/test-pm10-sensor.c
- examples/platform-specific/zoul/test-rotation-sensor.c
1. Fix some logical operators
2. The comparison uint16_t != -1 is always true. Should use an int to save the return value of a function that returns an int.
> Fix incorrect comparisons

- os/net/ipv6/uip6.c
This PR adds boundary checks in the processing of TCP options. Without these checks, it is possible to inject a TCP packet that causes out-of-bounds memory access.
In addition, the PR refactors duplicate TCP option processing code into a separate function.
> Add boundary checks in TCP option processing.

- os/net/ipv6/sicslowpan.c
The reassembly context contains an unused variable.
> 6LoWPAN: Remove unused variable from reassembly context

- arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-conf.h
- arch/cpu/cc26x0-cc13x0/dev/cc26xx-uart.c
- arch/platform/cc26x0-cc13x0/platform.c
- examples/sensniff/cc26x0-cc13x0/target-conf.h
Renames `CC26XX_UART_CONF_*` defines in cc26x0-cc13x0 to `TI_UART_CONF_*`, which is what the simplelink platform uses - thus easing portability between the two platforms. I am happy to discuss the deprecation strategy - if we want to be more lenient we could e.g. assign the old define to the new (and optionally issue a warning).
> Use TI_UART_CONF_* for both TI platforms

- arch/cpu/arm/Makefile.arm
- arch/cpu/native/Makefile.native
- arch/platform/cooja/Makefile.cooja
This will make the linker warn if there are
multiple definitions of the same symbol that
end up in a common block.
This should not happen in practice since
GCC 10 enabled -fno-common by default, so
adding the warning is low risk.
> Makefile: add --warn-common to LDFLAGS

- arch/platform/cooja/Makefile.cooja
After removing JNI, mtype.c can be built the same
way as the other files in the platform.
> cooja: build mtype.c as regular file

- doc/getting-started/Docker.md
Use the package names from docker.com, and make it possible to just cut and paste the code blocks into the shell for running commands.
> doc: update Docker documentation

- os/net/app-layer/coap/coap-uip.c
- os/net/ipv6/multicast/esmrf.c
- os/net/routing/rpl-classic/rpl-dag-root.c
- os/net/routing/rpl-classic/rpl-icmp6.c
Check return values of following functions for null:
- udp_new
- rpl_get_any_dag
- rpl_get_instance
This closes #2421.
> os/net: fix null pointer dereference

- arch/platform/cooja/contiki-conf.h
This replacement for #2432 only fixes the typo in the green led configuration. The author has not responded for some time, and https://github.com/contiki-ng/cooja/pull/1298 fixed the led colors in Cooja, making the other changes in #2432 unnecessary.
Thanks to asereq for finding the issues and suggesting a solution.
> Fix typo in Cooja led configuration

- arch/cpu/cc2538/dev/aes.c
Fix storing the address of a local variable in non-local memory:
https://github.com/contiki-ng/contiki-ng/blob/8518cbaff6a717d02444b686a75cdb240648fbf4/arch/cpu/cc2538/dev/aes.c#L116
> Fix stack address escape

- arch/platform/cooja/sys/cooja-log.c
Also fix to not insert SLIP END between each byte.
> Make SLIP support in Cooja log output configurable and fix issue with too many added SLIP END

- arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
- arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-conf.h
- arch/cpu/cc26x0-cc13x0/ccfg-conf.h
- arch/platform/cc26x0-cc13x0/launchpad/cc1310/board.h
- arch/platform/cc26x0-cc13x0/launchpad/cc1350/board.h
- arch/platform/cc26x0-cc13x0/launchpad/cc2640r2/board.h
- arch/platform/cc26x0-cc13x0/launchpad/cc2650/board.h
- arch/platform/cc26x0-cc13x0/sensortag/cc1350/board.h
- arch/platform/cc26x0-cc13x0/sensortag/cc2650/board.h
- arch/platform/cc26x0-cc13x0/srf06/cc13x0/board.h
- arch/platform/cc26x0-cc13x0/srf06/cc26x0/board.h
- doc/platforms/srf06-cc26xx.md
- doc/project/Release-Notes-next.md
- examples/platform-specific/cc26x0-cc13x0/base-demo/project-conf.h
- examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/project-conf.h
- examples/sensniff/cc26x0-cc13x0/target-conf.h
The two TI platforms are not aligned when it comes to configuring the CCFG: cc26x0-cc13x0 platform uses `CCXXWARE_CONF` prefix, while simplelink platform uses `CCFG_CONF` prefix. This PR refactors such that they both use `CCFG_CONF`, making it easier to move an application between the two platforms.
Using same deprecation-strategy as in #2311
> Use CCFG_CONF_* for both TI platforms

- arch/cpu/cc2538/Makefile.cc2538
- arch/cpu/cc2538/dev/cc2538-rf.c
- arch/cpu/cc2538/dev/cc2538-sram-seeder.c
- arch/cpu/cc2538/dev/cc2538-sram-seeder.h
- arch/cpu/cc2538/soc.c
- arch/platform/cooja/dev/moteid.c
- examples/libs/csprng/Makefile
- examples/libs/csprng/example.c
- examples/libs/csprng/project-conf.h
- os/dev/radio.h
- os/lib/csprng.c
- os/lib/csprng.h
- os/lib/iq-seeder.c
- os/lib/iq-seeder.h
- tests/02-compile-arm-ports/Makefile
This PR adds a CSPRNG, which, e.g., will come in handy when generating cryptographic keys or hash chains. For generating cryptographic random numbers, it uses AES-128 in OFB mode. For generating an initial seed, it uses an exchangeable `csprng_seeder`.  This PR also includes implementations of `csprng_seeder`s for CC2538-based platforms, such as the `cc2538_sram_seeder`, which extracts seeds from power-up SRAM states. For the time being, this CSPRNG does not provide forward and backward security, i.e., once its internal state leaks to an attacker, he can predict past and future outputs of the CSPRNG. This could be changed by calling the configured `csprng_seeder` not only at startup, but also at runtime once in a while.
> Cryptographically-Secure Pseudo-Random Number Generator (CSPRNG)

- os/net/app-layer/http-socket/http-socket.c
- os/net/app-layer/http-socket/websocket-http-client.c
strncpy needs one more character at the end to ensure it copies the string into the buffer including null termination. This PR will reserve room for null-termination.
> fixed size of strncopy to allow null termination

- os/net/ipv6/uip.h
This code has been commented out since
it got committed in 2008.
> uip.h: remove commented out code

- os/sys/cc-gcc.h
- os/sys/cc.h
Allow annotating functions that should run
before and after main.
This will turn out to be convenient for parsing
command line options in environments that can
support that.
> cc.h: add constructor/destructor attributes

- os/sys/process.c
this patch inspirited by a couple of hours debuging nontrivial aplication bug - servicing protothreads are strangely hungs, and later i see that them not even starts as planed. process_start fails without any side-effects. and that was fails, since protothread try start service just processing event PROCESS_EVENT_EXITED, on same service exited.
What happend in current implementation:
1) all running-processes notifyes about exiting process. If some of them wants to restart exiting-process, `process_start` fails, since exiting-process still in running-list
2) exiting-process removes from runnig-list. 
With this patch have:
1) exiting-process notifyes with PROCESS_EVENT_EXITED.
2) exiting-process removes from runnig-list. 
3) all running-processes notifyes about exiting process. And there …
> fix process exiting - vs immediate restart process after exiting.

- Makefile.include
Clang-15 is available in Ubuntu 22.04,
so bump the default to that.
> Makefile: bump default Clang version

- arch/cpu/gecko/Makefile.gecko
Add the same exception as the other
cpu Makefiles contain for Clang.
> Makefile.gecko: fix build for Clang

- arch/cpu/nrf52840/dev/uart0.c
- arch/cpu/nrf52840/dev/uart0.h
This is the function called from platform.c.
> nrf52840: align uart0_init with prototype

- tests/06-script-base/code-test-lc/Makefile
- tests/06-script-base/code-test-memb/Makefile
The tests should not pick up various things
installed on the build machine.
> tests: remove -I/usr/local/include

- arch/platform/cooja/contiki-conf.h
Cooja needs to know the size of types,
so use a type that is the same size
on 32/64-bit host platforms.
> cooja: use fixed-size clock_time_t size

- arch/platform/cooja/platform.c
There is no point with having a return
statement at the end of a void function,
so remove it.
> cooja: remove spurious return

- os/services/shell/shell-commands.c
Cast to an unsigned long so architectures
with a small clock_time_t builds without
warnings.
> shell-commands: fix printf format specifiers

- os/storage/antelope/storage-cfs.c
The i variable is only used in debug
mode, so add a read to silence a compiler
warning.
> antelope: fix compiler warning

- os/net/routing/rpl-classic/rpl-timers.c
Cast the printed variable so platforms
with a small clock_time_t builds without
warnings.
> rpl-timers: fix printf format specifier

- examples/mqtt-client/mqtt-client.c
Cast the clock_time_t to an unsigned
long, so architectures with a small
clock_time_t builds without warnings.
> mqtt-client: fix printf format specifier

- arch/cpu/native/net/tun6-net.c
- arch/platform/native/platform.c
- os/services/rpl-border-router/native/slip-dev.c
- os/services/rpl-border-router/native/tun-bridge.c
The build support for Cygwin was removed
after 4.8, so remove the ifdefs in the code
too.
> Remove __CYGWIN__ ifdefs

- .github/workflows/build.yml
Set SOURCE_DATE_EPOCH to the time
of the latest commit to get more
reproducible builds. GCC 7, Docker 24,
and various other build tools
supports this.
https://reproducible-builds.org/docs/source-date-epoch/
> CI: set SOURCE_DATE_EPOCH

- os/services/rpl-border-router/native/module-macros.h
This is the only place SELECT_CALLBACK
is mentioned in the Contiki-NG source
code.
> rpl-border-router: remove unused define

- os/dev/button-hal.h
Put the larger member earlier to avoid
inserting padding. This reduces the size
of the data segement between 4 and 20 bytes
on the ARM tests.
> button-hal.h: avoid struct padding

- arch/cpu/msp430/msp430-def.h
These types are not used in the msp430
platforms, so remove them.
> msp430: remove typedefs for u8_t & friends

- tools/docker/print-dockerhash.sh
Ensure the script fails if things cannot
run.
> print-dockerhash.sh: add set -o pipefail

- os/net/mac/tsch/tsch-adaptive-timesync.c
This avoids a warning with GCC 13.
> tsch: fix printf format specifiers

- examples/rpl-border-router/border-router.c
This file was created in 2017, fix the copyright
year to that instead of "201".
> border-router.c: fix copyright year

- arch/cpu/native/rtimer-arch.c
- arch/platform/native/contiki-conf.h
There is no WIN32 support, so remove
the ifdefs.
> native: remove WIN32 ifdefs

- os/services/rpl-border-router/native/border-router-mac.c
Include max session ID in error message.
> border-router: include max in error message

- os/dev/slip.c
This saves 2 bytes bss on MSP430.
> slip.c: remove unused variable

- examples/coap/coap-example-server/resources/res-mirror.c
- examples/coap/coap-plugtest-server/resources/res-mirror.c
Stop assigning to a variable that is
not read.
> examples/coap: remove unread variable

- os/net/routing/rpl-classic/rpl-timers.c
The return value is ignored, so remove
the statement.
> rpl-classic: remove duplicate read

- os/net/routing/rpl-lite/rpl-neighbor.c
Initialize the variable once, pick the the init
in the for-loop since that is a smaller scope.
> rpl-lite: remove duplicate initialization

- tests/01-compile-base/Makefile
Missed the flag on the first attempt, sorry. This is what the simulation tests build, and what makes the size tip over with #2574.
> tests: make simple-node larger on z1

- examples/6tisch/simple-node/node.c
Remove the double variable initialization to avoid a warning from Clang static analyzer. Also remove a block+indentation level since we now use C99.
> simple-node: remove double variable initialization

- arch/platform/native/contiki-conf.h
This function is already declared by
the libc header.
> native: stop declaring libc functions

- os/services/rpl-border-router/native/border-router-cmds.c
Remove an always-true if, convert the helper functions to use a regular return value, and invert the if-statement to remove an empty body.
> border-router-cmds: use regular return value

- tools/docker/Dockerfile
The PPA for GraalVM has not been updated
for a year, and does not respond to/review
pull requests.
GraalVM has also restructured their releases
to be latest LTS+latest current, so download
the GraalVM release directly from Github and
install that in the image.
> Dockerfile: update to GraalVM 17.0.7

- os/services/lwm2m/lwm2m-security.c
Put the variable in the branches where
it is actually read, and remove the remaining
assignments.
> lwm2m-security: reduce scope of variable

- examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/Makefile
- examples/platform-specific/cc26x0-cc13x0/cc26x0-web-demo/httpd-simple.c
The source string is potentially longer
than the destination, so ensure there
is a null termination of the resulting
string.
> cc26x0-web-demo: ensure null termination

- os/net/ipv6/uip-icmp6.h
Put the smallest members last, so
the padding is put at the end of
of the struct and minimized.
> uip-icmp6.h: avoid holes in struct

- os/net/mac/tsch/tsch-adaptive-timesync.c
This saves 12 bytes of text on some
MSP430 tests.
> tsch-adaptive-timesync: invert condition

- os/sys/process.c
Put the smallest member last to avoid
inserting padding on some architectures.
This reduces the text size on MSP430 with
a couple of bytes.
> process.c: avoid struct padding

- os/sys/energest.c
- os/sys/energest.h
Make the energest functions static inline
functions in the header so the cost of
disabled energest 0. This saves 12 bytes
text on MSP430.
> energest: inline functions when disabled

- arch/cpu/arm/arm-def.h
- arch/cpu/msp430/f1xxx/clock.c
- arch/cpu/msp430/f5xxx/clock.c
- arch/cpu/msp430/msp430-def.h
- arch/platform/cooja/contiki-conf.h
- arch/platform/native/contiki-conf.h
- arch/platform/zoul/orion/enc28j60-arch-gpio.c
- doc/programming/Porting-Contiki-NG-to-new-platforms.md
- doc/project/Release-Notes-next.md
- os/sys/clock.h
Use a similar construct as rtimer
for defining the size of clock_time_t.
> Centralize clock_time_t definition

- os/sys/autostart.h
- os/sys/cc.h
Variadic arguments to macros is a part of C99,
so this is no longer required.
> Remove CC_NO_VA_ARGS

- os/net/packetbuf.c
- os/net/packetbuf.h
Each commit saves 2 bytes of text on MSP430, a bit more on ARM.
> packetbuf: remove unused return values

- os/net/mac/framer/framer-802154.c
This saves 2 bytes of text on the MSP430 tests.
> framer: assign without if-statement

- arch/platform/cooja/sys/cooja_mt.c
The old thread code initialized the stack.
This shouldn't be required, so remove
the code.
> cooja: remove old stack scrambling

- os/net/linkaddr.c
- os/net/linkaddr.h
This saves 8 bytes of text on the MSP430 tests.
> linkaddr: make linkaddr_set_node_addr static inline

- arch/cpu/native/net/tun6-net.c
The printf family of functions are not safe to use in a signal handler, so switch to using write and strcpy/strncat instead.
> native: use safe functions in signal handler

- os/sys/ctimer.c
- os/sys/ctimer.h
- os/sys/etimer.c
- os/sys/etimer.h
- os/sys/stimer.c
- os/sys/stimer.h
- os/sys/timer.c
- os/sys/timer.h
If a timer has expired is clearly a boolean
question, so change the return type to reflect
that.
As a bonus, this saves 10-20 bytes of
text on the MSP430 tests.
> timers: change *_expired() to return bool

- arch/cpu/cc2538/dev/cc2538-rf.c
This PR removes redundant conditions from a `PROCESS_YIELD_UNTIL` in `cc2538-rf.c`.
> cc2538-rf: Simplification

- arch/platform/cooja/Makefile.cooja
- arch/platform/cooja/dev/rs232.c
- arch/platform/cooja/sys/cooja-log.c
- os/lib/dbg-io/printf.c
- os/lib/dbg-io/putchar.c
- os/lib/dbg-io/puts.c
- os/lib/dbg-io/snprintf.c
- os/lib/dbg-io/sprintf.c
There is no support for printing floats
in dbg-io, so stop using that.
The issues that f45a8c5327 tried to
avoid are not present on my computer,
which could be explained by 64-bit support
in Cooja, FFI instead of JNI, or using
-Wl,--wrap for wrapping the printf-family
of functions.
Fixes #2566
> cooja: fix printf for floats

- os/sys/stimer.c
- os/sys/stimer.h
This saves 16 bytes of text for all MSP430 tests, and another 12 bytes of text for slip-radio.sky.
> stimer: make functions static inline

- doc/project/Code-style.md
The current code-style states variables should always be declared at the start of the function. We have moved passed C89 so this is not required to compile, the style has not been enforced for a long time, and my reading of the community opinion is to declare variables as locally as possible. Update the code-style accordingly.
> Code-style: Declare variables as locally as possible

- examples/libs/stack-check/example-stack-check.c
- os/sys/stack-check.c
- os/sys/stack-check.h
Use the C99 type size_t to represent
pointer differences.
This reduces the size of the text segment
on MSP430 by 100+ bytes.
> stack-check: 64-bit fixes

- .github/workflows/build.yml
- tests/04-renode-simulation/01-rpl-udp.sh
- tests/04-renode-simulation/Makefile
PR https://github.com/contiki-ng/contiki-ng/pull/2535 adds a second set of test jobs for macOS.
There seems to be more Linux runners than macOS runners available, so split out the Renode
tests into a separate category, so the Renode tests can be limited to only run on Linux in the CI.
Also make some tweaks to the test itself, display logs on the console instead of a file, and stop
producing logs since the test framework no longer relies on those.
I get a lot of warnings that look like `[WARNING] server/sysbus: [cpu: 0x204DD4] (tag: 'ADC') ReadDoubleWord from non existing peripheral at 0x400D7018, returning 0x0.`, but those are not new.
> tests: make separate Renode category

- .github/workflows/build.yml
- tests/19-out-of-tree-build/Makefile
- tests/Makefile.compile-test
The out-of-tree-test is a copy of
examples/hello-world with a special
definition of CONTIKI.
Make the copy dynamically in the test
instead, so the test can be run without
cloning a separate repository.
This removes the need for the CI to
clone a separate repository, to pass
special arguments to Docker to mount
the repository in the right place,
and ensures the hello-world code has been
updated with any API changes in Contiki-NG.
> tests: internalize out-of-tree test

- .github/workflows/build.yml
When a PR gets updated, cancel any CI jobs
from the previous run. Let merge jobs complete
their runs, even if more PRs are merged after.
> CI: cancel jobs when updating PRs

- os/sys/ctimer.c
- os/sys/ctimer.h
This saves 46 bytes of text on all MSP430
tests.
> ctimer: make ctimer_set static inline

- os/sys/etimer.c
- os/sys/etimer.h
This saves 30-100+ bytes on MSP430 tests.
> etimer: make etimer_expired static inline

- os/net/netstack.c
- os/net/netstack.h
This saves 6 bytes of text on the MSP430
tests.
> netstack: make netstack_init static inline

- examples/benchmarks/rpl-req-resp/node.c
- examples/libs/deployment/node.c
- os/services/deployment/deployment.h
- os/sys/node-id.c
- os/sys/node-id.h
There is a single use of this code
in contiki-main, make it static inline
in the header instead.
This saves 8 bytes of text on all MSP430
tests.
> Make node_id_init static inline

- os/sys/rtimer.c
- os/sys/rtimer.h
This is a single-statement function,
so make it a macro instead.
This saves 6 bytes of text on all
MSP430 tests.
> rtimer: make rtimer_init a macro

- os/lib/ringbufindex.c
- os/lib/ringbufindex.h
This saves 18 bytes of text on simple-node
on Z1, which is the example that frequently
runs out of space.
> ringbufindex: make accessors static inline

- os/net/app-layer/mqtt/mqtt-prop.c
- os/net/app-layer/mqtt/mqtt-prop.h
Switch the argument order around
so the argument before ", ..."
is not an enum that undergoes default
argument promotion.
> mqtt: remove undefined behavior

- arch/platform/cooja/mtype.c
This will remove the platform-dependent
parsing of section starts/sizes in Cooja.
> cooja: add macOS segment helpers

- tests/Makefile.compile-test
Add a second round of (optional) tests using
Clang. This will allow the CI to ensure that
code builds without warnings with Clang.
This PR is just the test infrastructure
support, there are still quite a few PRs with
warning fixes to be merged before the check
can be enabled in the CI.
This commit also makes it possible to run
the tests with:
make Q=''
and see the compiler invocations the same way
that one would when building an example.
This PR also removes the "make magic", which
makes the test framework ready for running
tests in parallel; the limitation now resides in the main
build system (https://github.com/contiki-ng/contiki-ng/pull/2473).
> Makefile.compile-test: add Clang warning check

- arch/platform/zoul/contiki-conf.h
- os/net/mac/tsch/tsch-conf.h
- os/net/mac/tsch/tsch.c
GCC 12/13 will warn on most platforms
since this check is always false. Zoul
does however have a dynamic size, so
put the check under ifdef ZOUL.
> tsch: fix GCC 12/13 warning

- examples/6tisch/simple-node/Makefile
- os/net/ipv6/uip-ds6.h
Put the smaller members later in
structs to avoid padding.
This saves 16 bytes of bss and ~50 bytes
of text on MSP430. Most ARM tests also
save ~30 bytes of bss.
> uip-ds6: avoid padding in structs

- arch/cpu/msp430/dev/hwconf.h
- arch/cpu/msp430/msp430-def.h
- arch/platform/cooja/contiki-conf.h
- arch/platform/native/contiki-conf.h
- arch/platform/sky/dev/sky-sensors.c
- arch/platform/z1/dev/sky-sensors.c
- os/lib/hexconv.c
- os/net/app-layer/coap/coap-engine.c
- os/net/ipv6/uip-nameserver.c
- os/net/mac/framer/frame802154.c
- os/sys/cc.h
The inline keyword is available in C99,
so use that instead.
> Remove CC_CONF_INLINE

- Makefile.include
- arch/cpu/msp430/Makefile.msp430
- tests/01-compile-base/Makefile
- tests/Makefile.compile-test
- tools/docker/Dockerfile
This ensures that some parts of the code base remain warning-free with Clang.
> tests: enable Clang warning checks for 01-compilation-base

- os/net/routing/rpl-lite/rpl-types.h
Put the smaller members later in
structs to avoid padding.
> rpl-types: avoid padding in rpl_dag

- tests/02-compile-arm-ports/Makefile
Remove most tests that are not buildable
on the platform, but keep one to ensure
the functionality doesn't break in the build
system.
> tests: remove unbuildable tests

- Makefile.include
- arch/cpu/msp430/Makefile.msp430
This will give a compilation error when
the compiler inserts padding for alignment
in structs.
This functionality should be enabled in
the compilation tests, but there are still
numerous holes in the structs in Contiki-NG,
so only add the infrastructure to find the holes
for now.
> Makefile: add detection of holes in structs

- Makefile.include
- arch/platform/cooja/Makefile.cooja
Removing JNI removed many failure cases from
the build system, so it is now safe to build
binaries targeting Cooja from the shell.
The binaries built from the shell are named
in the same way that they are for other targets.
Cooja will not use these libraries though,
and instead generate a random name that has
not previously been used.
> cooja: allow building outside Cooja

- tests/06-script-base/02-test-lc-addrlabels.sh
- tests/06-script-base/03-test-memb.sh
- tests/06-script-base/04-test-result-visualization.sh
- tests/06-script-base/run-test-lc.sh
- tests/08-native-runs/01-test-data-structures.sh
- tests/08-native-runs/02-mqtt-client-31.sh
- tests/08-native-runs/03-mqtt-client-31-valgrind.sh
- tests/08-native-runs/04-mqtt-client-311.sh
- tests/08-native-runs/05-mqtt-client-311-valgrind.sh
- tests/08-native-runs/06-mqtt-client-5.sh
- tests/08-native-runs/07-mqtt-client-5-valgrind.sh
- tests/08-native-runs/08-native-ping.sh
- tests/08-native-runs/09-native-coap.sh
- tests/08-native-runs/11-aes-ccm.sh
- tests/08-native-runs/12-heapmem.sh
- tests/08-native-runs/13-coffee.sh
- tests/08-native-runs/mqtt-client.sh
- tests/10-ipv6-nbr/01-test-nbr-multi-addrs.sh
- tests/17-tun-rpl-br/test-border-router.sh
- tests/17-tun-rpl-br/test-native-border-router.sh
- tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
- tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh
- tests/18-coap-lwm2m/08-lwm2m-qmode-ipso-test.sh
- tests/18-coap-lwm2m/09-lwm2m-qmode-standalone-test.sh
- tests/20-packet-parsing/packet-injector.sh
The build system regulates how much information
that is printed when compiling, so stop piping
output to files when possible. This provides
timestamps in the CI logs.
Also add -j4 on calls to make to get some
parallelism, and stop tests early
with either executing the shell with -e
or adding "|| exit 1" to the make commands.
> tests: stop producing unused logs

- os/sys/rtimer.c
When calling `rtimer_set` from within the rtimer ISR, `rtimer_arch_schedule` gets called twice, even though there is code that tries to prevent this from happening. This PR provides a fix through small changes to `rtimer.c`.
> rtimer issues: redundant calls to rtimer_arch_schedule

- tools/toolchain/msp430/buildmsp.sh
There is a bug in the configure script in
gmp-4.8.3 that prevents building when flex
is installed. Fix the M4 value.
> buildmsp.sh: fix build when flex is installed

- tests/06-script-base/01-test-lc-switch.sh
- tests/06-script-base/02-test-lc-addrlabels.sh
- tests/06-script-base/03-test-memb.sh
- tests/06-script-base/04-test-result-visualization.sh
- tests/06-script-base/Makefile
- tests/06-script-base/run-test-lc.sh
Use Makefile.compile-tests to compile and run
the tests.
This will automatically clean each test, and
select the right number of cores for make -j.
> tests/script-base: enable full parallelism

- tests/20-packet-parsing/Makefile
- tests/20-packet-parsing/packet-injector.sh
Use Makefile.compile-tests to compile and run
the tests.
This will automatically clean each test, and
select the right number of cores for make -j.
> tests/packet-injector: enable full parallelism

- tests/20-packet-parsing/packet-injector.sh
These are not required, so remove them
to speed up the tests.
> tests: remove sleep statements

- os/lib/heapmem.c
Though the [API documentation](https://docs.contiki-ng.org/en/develop/_api/group__heapmem.html) says that calling `heapmem_free` with a NULL argument is fine, heapmem prints warnings when doing so.
> heapmem: Suppress warning when calling heapmem_free(NULL)

- tests/02-compile-arm-ports/Makefile
Create a temporary directory for the out-of-tree
tests when not running in the CI. The CI runs
in a clean environment, so that uses a fixed
location to improve ccache hit rate.
> tests: use mktemp for out-of-tree-test

- os/net/nbr-table.c
> nbr-table: remove extra code

- tests/08-native-runs/01-test-data-structures.sh
- tests/08-native-runs/08-native-ping.sh
- tests/08-native-runs/09-native-coap.sh
- tests/08-native-runs/10-snmp-server.sh
- tests/08-native-runs/Makefile
- tests/08-native-runs/mqtt-client.sh
- tests/08-native-runs/run-one.sh
- tests/Makefile.compile-test
Use Makefile.compile-tests to compile and run
the tests.
This will automatically clean each test, and
select the right number of cores for make -j.
> tests/native-runs: enable full parallelism

- tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
- tests/18-coap-lwm2m/07-lwm2m-standalone-test.sh
- tests/18-coap-lwm2m/08-lwm2m-qmode-ipso-test.sh
- tests/18-coap-lwm2m/09-lwm2m-qmode-standalone-test.sh
- tests/18-coap-lwm2m/Makefile
Use Makefile.compile-tests to compile and run
the tests.
This will automatically clean each test, and
select the right number of cores for make -j.
> tests/coap-lwm2m: enable full parallelism

- os/sys/process.c
These are already 0/NULL, so stop
initializing them again.
This saves 18-20 bytes on MSP430.
> process: avoid zero-init global vars

- os/net/ipv6/psock.h
Reorganize the members of the psock struct
to avoid padding.
> psock: avoid padding in psock

- arch/cpu/native/Makefile.native
- arch/platform/native/platform.c
This PR adds functionality for seeding the CSPRNG on the native platform, at least when run on Linux or macOS.
> CSPRNG: Support for native platform on Linux and macOS

- arch/cpu/nrf/Makefile.nrf
- arch/cpu/nrf52840/Makefile.nrf52840
Verify image after programming to avoid a warning when programming nrf devices.
> nrf: verify image programming

- os/sys/process.c
Make it possible to configure a function that should be called after a process poll has been requested. This is useful, for example, by platforms that require an additional action to wake up the system from sleep.
This is in preparation for TrustZone support in Contiki-NG.
> Add configurable callback after a process poll has been requested

- os/lib/ringbuf.c
- os/lib/ringbuf.h
This saves 12 bytes on some MSP430 tests.
> Make ringbuf_init static inline

- tools/docker/Dockerfile
The Python version of nRF Util has been
deprecated:
https://devzone.nordicsemi.com/nordic/nordic-blog/b/blog/posts/nrf-util-unified-command-line-utility
Refs #2657
> Dockerfile: upgrade to nRF Util 7.6

- Makefile.include
- arch/cpu/msp430/Makefile.msp430
- os/sys/cc.h
GCC can perform static analysis on code.
Add support to the build system for
using that.
Run with:
make ANALYZE=1
> Add support for static analysis

- Makefile.include
Give a readable error message when passing
a non-existent BOARD argument to make.
Without this, nrf (and other targets) will error
out with a cryptic error message along the lines of:
../../../arch/cpu/nrf/Makefile.: No such file or directory
> Makefile.include: error on faulty BOARD argument

- os/net/routing/rpl-lite/rpl-ext-header.c
This saves 2-6 bytes on MSP430.
> rpl-ext-header: reduce code size

- os/net/ipv6/sicslowpan.c
Add an assert so gcc -fanalyzer understands
that prefix is only null when prefcount is 0.
> sicslowpan.c: fix -fanalyzer warning

- examples/dev/button-hal/Makefile
- tests/02-compile-arm-ports/Makefile
The two Gecko boards that are supported only
have two leds, and the gpio-hal example requires
three leds.
Compile the button-hal example instead.
> tests/compile-arm-ports: switch gecko tests

- arch/cpu/arm/cortex-m/cm3/Makefile.cm3
Clang does not add crti.o and other files when
linking with the Contiki-NG build system, so
stop passing -nostartfiles to avoid a warning
about unused command line arguments.
> Makefile.cm3: avoid -nostartfiles with Clang

- examples/cplusplus/Makefile
There is no C++ compiler with the GCC used
by Contiki-NG.
> examples/cplusplus: exclude MSP430 platforms

- arch/cpu/simplelink-cc13xx-cc26xx/Makefile.cc13xx-cc26xx
GCC documents the flag as "interpreted by the linker", so pass the flag directly to the linker instead.
This fixes a number of compilation errors
in the ARM tests for Clang.
> simplelink: pass --entry to linker

- tests/compile-all/Makefile
- tests/compile-all/build.sh
Spawning 40+ compilers on a small machine
is slow, so limit the parallelism to
the -j argument that make is invoked with.
> tests/compile-all: limit parallelism

- os/services/rpl-border-router/embedded/Makefile.embedded
The "connect-router" target allows arguments,
so use the same mechanism for connect-router-cooja.
> rpl-border-router: enable tunslip6 args

- .clang-tidy
- Makefile.include
- arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0
Add clang-tidy to the rules for compiling
C/C++ files, and a minimal clang-tidy
configuration where almost everything
is disabled by default.
The functionality can be tested with:
make TIDY=1
> Makefile: add support for clang-tidy

- tests/08-native-runs/run-one.sh
Allow tests to be called something other than
test-*.native.
> tests/08-native-runs: allow name specification

- tools/docker/Dockerfile
This uses an optimized build which should
speed up compilation. There is also a macOS
binary available that is built in the same
CI pipeline.
> Dockerfile: update to new MSPGCC

- arch/cpu/cc2538/dev/sha256.c
This PR disables the `DMA_IN_DONE` when computing SHA-256 hashes. We only need the `RESULT_AV`, which is issued when the result is available.
> SHA-256: Disable unnecessary interrupt

- arch/cpu/nrf/Makefile.nrf
- arch/cpu/nrf/Makefile.nrf52840
- arch/cpu/nrf/Makefile.nrf5340_application
- arch/cpu/nrf/Makefile.nrf5340_network
Makefile.cortex-m adds "-T $(LDSCRIPT)",
so add "-L $(NRFX_ROOT)/mdk" to LDFLAGS
before that.
This fixes a link issue with finding
nrf_common.ld for nrf52840 boards
when using Clang.
> nrf: add mdk to LDFLAGS early

- arch/cpu/nrf/sys/clock-arch.c
This is an optimization in preparation for TrustZone support #2740 to avoid switching between secure and normal world for each clock tick.
> nrf-clock: only request etimer poll when an etimer has expired

- Makefile.include
- arch/cpu/arm/Makefile.arm
- arch/cpu/msp430/Makefile.msp430
- doc/project/Contributing.md
- doc/project/Release-Notes-next.md
GCC 5.5 and later default to -std=gnu11, and
only MSP430-based targets are compiled with
an older GCC. There is partial C11 support
in GCC 4.7.x though, so enable that on all
platforms.
In practice, this means generic code is
limited to the C11 features supported
by GCC 4.7.x, but platform specific
code for non-MSP430-based targets can use
any feature available in C11.
> Compile as C11

- Makefile.include
Just add a .d extension to the source file name.
This avoids filtering in the build system, and
avoids name collisions for the dependency files
generated for C/C++/assembly source files.
> Makefile: simplify DEPFILES definition

- os/net/ipv6/multicast/esmrf.c
These memory buffers overlap, so use memmove.
> esmrf: use memmove instead of memcpy

- Makefile.include
Disable the same warnings for ARM GCC 13
as for 12, and update the comments to reflect
the still insufficient precision of
the underlying analysis.
> Makefile.include: fix for ARM GCC 13

- os/sys/stack-check.c
GCC 13 on ARM warns that the address of
the stack is stored in a variable. The warning
is right, but that is the intention. Disable
the warning for that assignment.
> stack-check: disable GCC 13 warning

- os/lib/ccm-star.c
This PR revises both sanity checks in the `aead` function. One of them presumably remained from an older version. The other hinders the reuse of the implementation. The changes build upon #2754.
> CCM*: Revise sanity checks

- os/lib/ringbuf.c
CodeQL flags sign checks of bitwise operations,
and suggests comparing with != 0 instead of > 0.
Since all the types are unsigned, that should
give the same result, but without CodeQL warnings.
> ringbuf: remove sign check warning

- arch/platform/cooja/dev/eeprom.c
- arch/platform/cooja/platform.c
This is an empty function on the Cooja target,
so remove the function.
> cooja: stop calling eeprom_init

- examples/storage/antelope-shell/shell-db.c
This is similar to the cast required
for printf a couple of lines below.
> antelope-shell: cast void argument

- os/lib/ringbufindex.c
CodeQL flags sign checks of bitwise operations,
and suggests comparing with != 0 instead of > 0.
Since all the types are unsigned, that should
give the same result, but without CodeQL warnings.
> ringbufindex: remove sign check warning

- .github/workflows/codeql.yml
Some warnings are in groups, and
some warnings are "top level". The
warnings that commit d27496db93
tried to filter out are at the top
level, so update the names for that.
> CodeQL: fix filter names

- .github/workflows/codeql.yml
The reports in Security are created from
the results of this workflow, the reports
are not a display of the sarif file itself.
Decrease the retention days for the sarif
file since there is no direct use of it.
> CodeQL: decrease retention-days

- os/net/app-layer/mqtt/mqtt.c
CodeQL flags sign checks of bitwise operations,
and suggests comparing with != 0 instead of > 0.
Since all the types are unsigned, that should
give the same result, but without CodeQL warnings
> mqtt: remove sign check warning

- os/net/ipv6/udp-socket.c
The buffer is only used when there is a callback,
so only perform the memcpy under the same
circumstances.
> udp-socket: only memcpy when required

- .github/workflows/build.yml
- .readthedocs.yaml
- tools/docker/Dockerfile
- tools/doxygen/Doxyfile
Update the Doxyfile to the same version,
and restore the default value of
EXPAND_ONLY_PREDEF to avoid mqtt.h
warnings from Doxygen not understanding
that MQTT_5 is set.
> Update to Doxygen 1.10.0

- os/lib/heapmem.c
- os/lib/heapmem.h
- tests/08-native-runs/12-heapmem/test-heapmem.c
Beside keeping track of the peak heap usage, this PR also includes an extended test for the maximum heap usage, and some minor style and documentation fixes.
> heapmem: keep track of peak heap usage

- arch/platform/cooja/dev/moteid.c
Building upon #2639 and #1653, this PR improves the CSPRNG output in Cooja. Currently, the first cryptographic random numbers do not look random since the CSPRNG is fed with a seed of insufficient length.
> CSPRNG: Use SHA-256 to generate more random csprng_seeds in Cooja

- arch/cpu/cc2538/dev/cc2538-ccm-star.c
- os/lib/ccm-star.h
This PR brings a faster CCM* driver for CC2538-based platforms. Executing Test vector C.2.2.2.1 from IEEE 802.15.4-2020 one thousand times took 113ms with the old and 90ms with the new CCM* driver. Besides, an issue with the old CCM* driver for the CC2538 is that it freezes on certain inputs (e.g., a_len = 0 and a_len = 0 & m_len = 0). This is also being fixed.
> CC2538: Faster CCM* driver and freeze fix

- os/lib/assert.h
- os/sys/cc.h
This avoids the risk of circular includes when using static_assert() in certain header files.
> cc.h: move static_assert from lib/assert.h

- arch/cpu/cc26x0-cc13x0/rf-core/ble-hal/rf-ble-cmd.c
- arch/cpu/cc26x0-cc13x0/rf-core/ble-hal/rf-ble-cmd.h
> Add missing include of inttypes.h in rf-ble-cmd.c

- arch/cpu/cc26x0-cc13x0/dev/gpio-hal-arch.c
This PR
* Enable support for setting hysteresis for GPIOs
* Clear any existing events before enabling interrupts via `gpio_hal_arch_pin_cfg_set()` (making it identical to `gpio_hal_arch_interrupt_enable()`).
> Minor GPIO HAL enhancements for cc26x0-cc13x0

- .gitignore
- Makefile.include
- doc/getting-started/The-Contiki-NG-build-system.md
- doc/tutorials/CoAP.md
- doc/tutorials/Hello,-World!.md
- doc/tutorials/LWM2M-and-IPSO-Objects.md
- doc/tutorials/MQTT.md
- doc/tutorials/RPL-border-router.md
- doc/tutorials/Timers-and-events.md
- examples/rpl-udp/rpl-udp.resc
- examples/rpl-udp/rpl-udp.robot
- os/services/rpl-border-router/native/Makefile.native
- tests/07-simulation-base/01-hello-world-sky.csc
- tests/07-simulation-base/07-hello-world-z1.csc
- tests/07-simulation-base/22-stack-guard-sky.csc
- tests/07-simulation-base/23-rpl-tsch-z1.csc
- tests/07-simulation-base/26-tsch-drift-z1.csc
- tests/07-simulation-base/31-data-structures-sky.csc
- tests/08-native-runs/08-native-ping.sh
- tests/08-native-runs/09-native-coap.sh
- tests/08-native-runs/10-snmp-server.sh
- tests/08-native-runs/mqtt-client.sh
- tests/08-native-runs/run-one.sh
- tests/17-tun-rpl-br/03-border-router-sky.csc
- tests/18-coap-lwm2m/06-lwm2m-ipso-test.sh
- tests/18-coap-lwm2m/08-lwm2m-qmode-ipso-test.sh
- tests/20-packet-parsing/packet-injector.sh
This change simplifies the distclean rule, and
avoids overwriting the binary in . when
building the same firmware for two different boards.
Long term, this change will enable more
parallelism in the build system since
the same binary can be built for two different
boards at the same time.
This also improves build performance slightly
since it avoids one copy of the binary for
each target.
This commit requires removing old binaries
from the tree for tests to pass. A dry run
of git clean will show the files:
git clean -n tests examples
> Makefile: stop putting target in .

- Makefile.include
This fixes:
$ make distclean
TARGET not defined, using target 'native'
/bin/sh: 1: [: =: unexpected operator
discovered by @kkrentz.
> Makefile.include: fix missing quotes

- os/lib/aes-128.c
- os/lib/aes-128.h
- os/lib/ccm-star.c
- os/lib/ccm-star.h
- os/lib/csprng.c
- os/lib/csprng.h
- os/lib/sha-256.c
- os/lib/sha-256.h
This PR moves crypto-related files into a common crypto group.
> doxygen: Move crypto-related files to the crypto group

- arch/cpu/native/net/tun6-net.c
- os/services/rpl-border-router/native/slip-config.c
- os/services/rpl-border-router/native/tun-bridge.c
The code in tun-bridge.c and tun6-net.c is nearly identical. Share the simple parts, and align the rest in preparation for sharing more code in the future.
> border-router: share code with native

- os/net/app-layer/coap/coap-conf.h
- os/net/app-layer/coap/coap-engine.c
As in title. The resource is still enabled by default. Disabling saves almost 500 bytes code space on cc13xx-cc26xx.
> Allow disabling CoAP well known resource

- os/dev/nullradio.c
The prepare function does not do anything,
so remove the call to it.
> nullradio: remove no-op call

- tools/doxygen/Doxyfile
This PR fixes that the documentation test fails when adding elaborate doxygen documentation to `PT_THREAD` function pointers.
> doxygen: Help doxygen resolve the PT_THREAD macro

- os/lib/csprng.c
- os/lib/csprng.h
This PR changes the CSPRNG to use size_t, which is more appropriate.
> CSPRNG: Use size_t

- os/net/app-layer/coap/coap-block1.c
- os/net/app-layer/coap/coap-conf.h
- os/net/app-layer/coap/coap-engine.c
- os/net/app-layer/coap/coap-separate.c
- os/net/app-layer/coap/coap.c
- os/net/app-layer/coap/coap.h
A set of minor improvements to CoAP:
* Make the inclusion of error-messages in payload optional. This saves ~300 bytes on cc13xx-cc26xx platform when disabled. By default it is still enabled, thus no changes in behavior after this PR.
* Add missing `const` for some CoAP APIs
* Use `_CONF_` for the recently added `WELL_KNOWN_RESOURCE_ENABLED` option
> CoAP minor improvements

- os/net/ipv6/uip-packetqueue.c
- os/net/ipv6/uip-packetqueue.h
~~The `next`-field in `struct uip_packetqueue_packet` is a pointer to `struct uip_ds6_queued_packet`. This datatype is not declared or defined anywhere. Seems straight-forward that this should be a pointer to a `struct uip_packetqueue_packet`.~~
A set of minor improvements:
* Remove unused `next` and `handle` from `struct uip_packetqueue_packet`
* Modernize logging, code-style
* Fix inclusions and missing consts
Closes https://github.com/contiki-ng/contiki-ng/issues/1186
> Minor improvements in packetqueue

- os/net/app-layer/snmp/snmp-ber.c
The `snmp_ber_decode_string_len_buffer` function does not properly verify the the packet size when de-referencing the `in` pointer, allowing for an out of bounds read of 1 byte in some scenarios. I originally disclosed this issue via email and was instructed to file a PR.
This PR fixes the issue by adding a check that will return if `snmp_packet->used == 0` before the de-reference, which will prevent this out of bounds read from occurring.
> Added snmp_packet->used validation check in snmp_ber_decode_string_len_buffer

- os/net/app-layer/snmp/snmp-message.c
The `snmp_message_decode` function does not properly verify the packet size when de-referencing the `in` pointer, allowing for an out-of-bounds read of 1 byte to occur in some scenarios. I originally disclosed this issue via email and was instructed to file a PR.
This PR fixes the issue by adding a check that will return if `snmp_packet->used == 0` before the de-reference, which will prevent this out of bounds read from occurring.
> Added additional snmp_packet->used verification check in snmp_message_decode

- os/sys/ctimer.c
Shortens `ctimer_expired` by using `list_contains`
> ctimer: Simplification of ctimer_expired

- os/services/unit-test/unit-test.c
- os/services/unit-test/unit-test.h
This PR turns unit test functions into protothreads. This allows unit tests to call protothreads and wait for them to finish.
> unit-test.ch: Enable tests to use protothread functions

- os/services/rpl-border-router/native/border-router-native.c
Fix an issue where the border router could clear the network configuration by reinitializing the RPL network if the MAC address is received multiple times from the slip radio.
> border-router: only allow MAC address to be set once at startup

- os/net/routing/rpl-classic/rpl-ext-header.c
- os/net/routing/rpl-classic/rpl-private.h
- os/net/routing/rpl-classic/rpl-timers.c
- os/net/routing/rpl-classic/rpl.h
- tests/15-rpl-classic/js/13-rpl-dao-garbled.js
This PR
1. Proposes a workaround to RPL issue #2377 
2. ~~Adds a test that showcases #2377~~ The test for the issue was added separately in #2548. This PR simply reverts the logic in the test such that it passes only if the issue is resolved.
In short, #2377 describes how No-Path DAOs that are sent when detecting RPL forwarding error will have garbled content and the receiver will discard it with error-log: `icmpv6 bad checksum`. The workaround adds a small delay (next tick) to the generation of the DAO, and this resolves the issue. I am no uIP/RPL expert and I have not identified the root cause as to why the content is garbled (see some ideas in #2377). As such, I will have no trouble if we don't merge this and rather leave it for others to work onward from.
For further details see …
> Workaround for DAO having garbled content after RPL forwarding error

- arch/platform/zoul/Makefile.zoul
The Zolertia Firefly devices appear as `/dev/tty.usbserial*` on macOS.
> zoul: add serial device pattern for motelist to search for Zolertia devices

- os/services/rpl-border-router/native/Makefile.native
- os/services/rpl-border-router/native/border-router-cmds.c
Serial communication is handled by the native border-router and starting serial-shell will cause any shell commands to be executed twice.
> rpl-border-router: avoid starting serial-shell

- arch/platform/cooja/Makefile.cooja
Other Contiki-NG platforms add to `CONTIKI_TARGET_SOURCEFILES`  in their own Makefile.
Cooja simply sets the variable `CONTIKI_TARGET_SOURCEFILES`. 
This breaks user application code that sets `CONTIKI_TARGET_SOURCEFILES` from the application Makefiles.
> Cooja platform: append to CONTIKI_TARGET_SOURCEFILES rather than set them

- arch/platform/native/platform.c
- os/contiki-main.c
- os/services/rpl-border-router/native/slip-config.c
- os/sys/platform.h
This is a different approach for the infrastructure parts of https://github.com/contiki-ng/contiki-ng/pull/755.
This pull request allows each compilation unit to specify their own command line options, and switches the border-router to use the new API.
The compilation units add their options before `main` is run, and parsing command line options is the first thing that happen inside `main`, so command line options can be used to configure things before processes are started.
The code uses `getopt_long_only` so legacy parameters (`-v0`..`-v5`) still work. The `getopt_long_only` function is widely available, but if the SDK for some platform does not provide that function, users can put in the code from newlib/picolibc or one of the BSDs and things should work.
This PR is already quite a few …
> Add early command line parsing

- tools/docker/files/rtd_requirements.txt
This hopefully fixes the documentation
build failure on macOS.
> rtd_requirements.txt: install standard-imghdr

- os/net/routing/rpl-classic/rpl-icmp6.c
The `dio_input` function has multiple out of bounds reads. The incoming data buffer is indexed multiple times without any checks to ensure the index is within bounds. A similar issue was fixed in this [PR](https://github.com/contiki-ng/contiki-ng/pull/2484) for rpl-lite, but no such fix is present for rpl-classic.
This PR fixes the issue by placing multiple checks throughout the function to ensure the index does not exceed the bounds of the incoming data buffer.
> Added size checks in dio_input to prevent multiple out of bounds reads

- os/net/mac/ble/ble-l2cap.c
The `input_l2cap_frame_flow_channel` does not properly verify the size of the provided source buffer when copying data into the `l2cap_channel_t` struct. This could lead to out of bounds reads using a crafted packet.
This PR fixes the issue by adding two checks before each copy that ensures the source data buffer has enough size to preform the copy.
> Added additional source data check in input_l2cap_frame_flow_channel

- os/net/ipv6/uip-nd6.c
The `ns_input` function does not properly ensure the size of the data buffer is large enough when preforming a cast. This can lead to out of bounds reads with a crafted packet.
This PR fixes the issue by ensuring the header size plus the size of the struct does not exceed the data size.
> Added additional size check in ns_input to prevent out of bounds cast

- os/net/ipv6/uip-nd6.c
This PR enables IPv6 checks on incoming neighbor discovery messages, updates the code style and error messages of the module, and moves a recently introduced NS packet length check to the beginning of the function
> uip-nd6.c: always use IPv6 checks
